### PR TITLE
Yair/new transactions

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/30)

### CODE REVIEW

**Comment by anatgstarkware** [comment]
*[`src/transaction.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/30#-NR3PW159PX85jKP-BTO:-NR3PW159PX85jKP-BTP:b-h9xgbh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/7a48f40c9f9d5abf46486d0caa1c39e8468dbb6b/src/transaction.rs#L85)):*
> ```XML
>     pub transaction_hash: TransactionHash,
>     pub max_fee: Fee,
>     pub version: TransactionVersion,
> ```

I find it weird that a struct called DeclaredV1Transaction has a version field



_Code quote:_
```XML
DeclareV1Transaction
```

**Comment by dan-starkware** [comment]
*[`src/transaction.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/30#-NRh3x3wCuRfVf05_rQT:-NRh3x3wCuRfVf05_rQU:b-wohpja) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e3b35adfcfffa868359617657654eeff32fec353/src/transaction.rs#L95)):*
> ```XML
>     pub signature: TransactionSignature,
>     pub nonce: Nonce,
>     pub class_hash: ClassHash,
> ```

Consider refactor, maybe something similar to

pub struct CommonDeclareTransactionFields{...}

pub struct DeclareTransactionV1 {
    #[serde(flatten)]
    pub common_fields: CommonDeclareTransactionFields,
}



_Code quote:_
```XML
    pub transaction_hash: TransactionHash,
    pub max_fee: Fee,
    pub signature: TransactionSignature,
    pub nonce: Nonce,
    pub class_hash: ClassHash,
    pub sender_address: ContractAddress,
```

**Comment by dan-starkware** [comment]
*[`src/transaction.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/30#-NRh3x3wCuRfVf05_rQT:-NRh4fzn2hIGDlYYaSrI:b-2pkwmz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e3b35adfcfffa868359617657654eeff32fec353/src/transaction.rs#L95)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider refactor, maybe something similar to

pub struct CommonDeclareTransactionFields{...}

pub struct DeclareTransactionV1 {
    #[serde(flatten)]
    pub common_fields: CommonDeclareTransactionFields,
}

</blockquote></details>

Can also use in V2?

**Review by dan-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/30)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @giladchase, and @yair-starkware)

**Pull request merged**
