### PR TITLE
feat(transaction): implement external transactions

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/external_transaction.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuO6jyE70mkhrIlXEHa:-NuO6jyE70mkhrIlXEHb:b-1fcjpo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b39fda04128e00b4fa9c32907a4782172ffb405b/src/external_transaction.rs#L15)):*
> ```XML
> 
> /// An external transaction.
> #[derive(Debug, Clone, Eq, PartialEq, Deserialize, Serialize)]
> ```

Alphabetize x11
___
*[`src/external_transaction.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuO76tg7QZ_Z4Ep_qNS:-NuO76tg7QZ_Z4Ep_qNT:b-c0b9bg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b39fda04128e00b4fa9c32907a4782172ffb405b/src/external_transaction.rs#L108)):*
> ```XML
> 
> /// An invoke transaction that can be added to Starknet through the Starknet gateway.
> /// It has a serialization format that the Starknet gateway accepts in the `add_transaction`
> ```

Consider update/remove x4

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/external_transaction.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuT1_Ra8W3dcyPzY66N:-NuT1_Ra8W3dcyPzY66O:bckzdmo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b39fda04128e00b4fa9c32907a4782172ffb405b/src/external_transaction.rs#L7)):*
> ```XML
> // use serde_repr::{Deserialize_repr, Serialize_repr};
> use crate::core::{ClassHash, CompiledClassHash, ContractAddress, Nonce};
> use crate::data_availability::DataAvailabilityMode;
> ```

I think the original `DataAvailabilityMode` enum expects deserialization from structured formats rather than direct numbers (0, 1), so deserialization with numeric values doesn't work. By using `#[repr(u8)]` on an enum, it is treated as `u8` values. `Deserialize_repr` and `Serialize_repr` enable the direct mapping of these numbers.



_Code snippet:_
```XML
// original
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum DataAvailabilityMode {
    L1 = 0,
    L2 = 1,
}

// new
#[derive(Clone, Debug, Deserialize_repr, Serialize_repr, Eq, PartialEq)]
#[repr(u8)]
pub enum DataAvailabilityMode {
    L1 = 0,
    L2 = 1,
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`src/external_transaction.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuT1_Ra8W3dcyPzY66N:-NuT4zGj1GDpErYQCo9B:bdye6gk) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b39fda04128e00b4fa9c32907a4782172ffb405b/src/external_transaction.rs#L7)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I think the original `DataAvailabilityMode` enum expects deserialization from structured formats rather than direct numbers (0, 1), so deserialization with numeric values doesn't work. By using `#[repr(u8)]` on an enum, it is treated as `u8` values. `Deserialize_repr` and `Serialize_repr` enable the direct mapping of these numbers.
</blockquote></details>

Thank you for the excellent debug!
Updated accordingly.
___
*[`src/external_transaction.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuO6jyE70mkhrIlXEHa:-NuT6YeU7EJLWjR1GDQa:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b39fda04128e00b4fa9c32907a4782172ffb405b/src/external_transaction.rs#L15)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Alphabetize x11
</blockquote></details>

Done.
___
*[`src/external_transaction.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuO76tg7QZ_Z4Ep_qNS:-NuT6eR4Bg2orAeagj0Y:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b39fda04128e00b4fa9c32907a4782172ffb405b/src/external_transaction.rs#L108)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Consider update/remove x4
</blockquote></details>

Done.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`Cargo.toml` line 27 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuTBvIV6tO8n3TyW_U9:-NuTBvIV6tO8n3TyW_UA:b6i7dh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/Cargo.toml#L27)):*
> ```TOML
> strum_macros = "0.24.3"
> thiserror = "1.0.31"
> serde_repr = "0.1"
> ```

@giladchase 
PTAL

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYqaQB2w0CeQHbh0KE:-NuYqaQB2w0CeQHbh0KF:b-6w90ip) (no related file):*
Missing unit test.

___
___
*[`src/external_transaction.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYnwIl2RMIpWf5a-fi:-NuYnwIm-GtbAU5XpyS2:bb76mu4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L4)):*
> ```XML
> 
> use serde::{Deserialize, Serialize};
> use serde_repr::{Deserialize_repr, Serialize_repr};
> ```

Why?



_Code quote:_
```XML
use serde_repr::{Deserialize_repr, Serialize_repr};
```
___
*[`src/external_transaction.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYnxxI5SIFybdkj9od:-NuYnxxI5SIFybdkj9oe:ba3dfmt) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L6)):*
> ```XML
> use serde_repr::{Deserialize_repr, Serialize_repr};
> 
> // use serde_repr::{Deserialize_repr, Serialize_repr};
> ```

Remove.



_Code quote:_
```XML
// use serde_repr::{Deserialize_repr, Serialize_repr};
```
___
*[`src/external_transaction.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYqUDM3_jIrEmgpyxP:-NuYqUDM3_jIrEmgpyxQ:bsdqj13) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L25)):*
> ```XML
>     Invoke(ExternalInvokeTransaction),
> }
> ```

Why are the "type" fields needed? Can you add a short example of usage? Should have appeared in a unit test.
Is this the best way to implement the "one of schema" equivalent in Rust?
___
*[`src/external_transaction.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYpvE2BHsrmnZMnbB2:-NuYpvE2BHsrmnZMnbB3:b-svvaut) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L157)):*
> ```XML
> #[derive(Clone, Debug, Deserialize_repr, Eq, PartialEq, Serialize_repr)]
> #[repr(u8)]
> pub enum DataAvailabilityMode {
> ```

Why [duplicate](https://github.com/starkware-libs/starknet-api/blob/6f9e4680f798b5e6cd600649dbfecba9a7f1ef7e/src/data_availability.rs#L7)?



_Code quote:_
```XML
DataAvailabilityMode
```

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: all files reviewed, 8 unresolved discussions (waiting on @ayeletstarkware, @giladchase, and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYtDA50aS4TTXxDTbf:-NuYtDA50aS4TTXxDTbg:b-682dsk) (no related file):*
Can you please link to the JSON RPC schema of the transactions?

___

**Review by ayeletstarkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYqaQB2w0CeQHbh0KE:-NuZ9sfj2N9_Fwamoo0y:b-a4lgrs) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Missing unit test.
</blockquote></details>

I will add in a separate PR.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYtDA50aS4TTXxDTbf:-NuYvEP7EcfjfH2duxsh:bxflxbt) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you please link to the JSON RPC schema of the transactions?
</blockquote></details>

Sure.

[Declare](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1985)
[Deploy account](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L2430)
[Invoke](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L2688)

___
___
*[`src/external_transaction.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYnwIl2RMIpWf5a-fi:-NuYxLSQ2HIi2dpWLIiV:bx1snl0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L4)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

It's a trait used for `serde_repr`. In the external transaction, I used `#[repr(u8)]` in `DataAvailabilityMode` enum to serialize a `u8` value into an enum value.
___
*[`src/external_transaction.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYqUDM3_jIrEmgpyxP:-NuZ3GLc7d5ybQjzn-_-:by5mv9n) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L25)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why are the "type" fields needed? Can you add a short example of usage? Should have appeared in a unit test.
Is this the best way to implement the "one of schema" equivalent in Rust?
</blockquote></details>

Following Gilad's suggestion, I replaced it with:
`#[serde(tag = "type")]`
I think we can also replace the version. WDYT?
___
*[`src/external_transaction.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYpvE2BHsrmnZMnbB2:-NuZ4muZ5TgkM2gTu_It:bbw5tsi) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L157)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why [duplicate](https://github.com/starkware-libs/starknet-api/blob/6f9e4680f798b5e6cd600649dbfecba9a7f1ef7e/src/data_availability.rs#L7)?
</blockquote></details>

Her, I've added `#[repr(u8)]`.
To serialize `u8` to the enum field.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`src/external_transaction.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYqUDM3_jIrEmgpyxP:-NucYvI24N-jV7dE2oDL:b-n8j5en) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L25)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Following Gilad's suggestion, I replaced it with:
`#[serde(tag = "type")]`
I think we can also replace the version. WDYT?
</blockquote></details>

Reverted.
It's a bit problematic for deserialization.
Added a task on Monday:
https://starkware.monday.com/boards/3670745608/pulses/6389958271

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYqaQB2w0CeQHbh0KE:-NucZSQq41IxnT-2Cenp:b-gvx24u) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I will add in a separate PR.
</blockquote></details>

[PR](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-)

___

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`src/external_transaction.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NusDsR42drUzWtAGLdB:-NusDsR42drUzWtAGLdC:bwm02kc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fe34a8038f8678d117e789bdd6319dd28352c839/src/external_transaction.rs#L53)):*
> ```XML
>     #[default]
>     Declare,
> }
> ```

is discussed offline, these can be removed, along with the `type` field, and replaced with 
```rust
#[serde(tag = "type")]
```
and possibly 
```rust
#[serde(rename_all = "lowercase"]
```
or something equivalent.
If there are issues, consult the [serde docs](https://serde.rs/container-attrs.html) for more and/or ping me about it.



_Code quote:_
```XML
/// The type field of a deploy account transaction. This enum serializes/deserializes into a
/// constant string.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub enum DeployAccountType {
    #[serde(rename = "DEPLOY_ACCOUNT")]
    #[default]
    DeployAccount,
}

/// The type field of an invoke transaction. This enum serializes/deserializes into a constant
/// string.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub enum InvokeType {
    #[serde(rename = "INVOKE_FUNCTION")]
    #[default]
    Invoke,
}

/// The type field of a declare transaction. This enum serializes/deserializes into a constant
/// string.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub enum DeclareType {
    #[serde(rename = "DECLARE")]
    #[default]
    Declare,
}
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`src/external_transaction.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYpvE2BHsrmnZMnbB2:-NusFJMVBULaWDgVxve1:b-xra5r6) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L157)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Her, I've added `#[repr(u8)]`.
To serialize `u8` to the enum field.
</blockquote></details>

What is the motivation for the change, that is, can't we keep using the existing implementation?
Is it just to change deserialization? 

If it's just for deserialization, AND it is absolutely necessary, then we should remove this duplication and implement custom deserialization for the original DataAvailabilityMode, that supports deserde from both L1/L2 and from 0/1.

The most readable way to do this IMO, is to do this:
```rust
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(try_from = "Deserializer")]
pub enum DataAvailabilityMode {
    L1 = 0,
    L2 = 1,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum Deserializer {
    Num(u8),
    Text(String),
}

impl TryFrom<Deserializer> for DataAvailabilityMode {
    type Error = <some error>

    fn try_from(value: Deserializer) -> Result<Self, Self::Error> {
        match value {
            Deserializer::Num(0) => Ok(DataAvailabilityMode::L1),
            Deserializer::Num(2) => Ok(DataAvailabilityMode::L2),
            Deserializer::Text(text) if &text == "L1" => Ok(DataAvailabilityMode::L1),
            Deserializer::Text(text) if &text == "L2" => Ok(DataAvailabilityMode::L2),
            _ => Self::Error(
                "Data availability must be either 'L1' or '0' for L1, or 'L2' or '1' for L2.",
            ),
        }
    }
}
```
Either that or the regular custom deserizlier, which is less readable IMO, your call.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`src/external_transaction.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYqUDM3_jIrEmgpyxP:-NuscQvZ5-kiJz_YfrSy:ba1k1bu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L25)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Reverted.
It's a bit problematic for deserialization.
Added a task on Monday:
https://starkware.monday.com/boards/3670745608/pulses/6389958271
</blockquote></details>

What problem are you hitting in deserde? ping me if its too complex for here.
I'd like to solve this one, the current implementation is very close to reimplementing serde's tag="type".
___
*[`src/external_transaction.rs` line 134 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NusciT9-c-85dDgFpI4:-NusciT9-c-85dDgFpI5:b-ijjzcp) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fe34a8038f8678d117e789bdd6319dd28352c839/src/external_transaction.rs#L134)):*
> ```XML
>     pub version: TransactionVersion,
>     pub r#type: DeclareType,
> }
> ```

I saw that InternalTransaction was held a DeclareTransaction instance instead of some of the fields here, can't we do the same here?
Motivation: to not duplicate the field names.



_Code quote:_
```XML
pub struct ExternalDeclareTransactionV3 {
    pub contract_class: ContractClass,
    pub resource_bounds: ResourceBoundsMapping,
    pub tip: Tip,
    pub signature: TransactionSignature,
    pub nonce: Nonce,
    pub compiled_class_hash: CompiledClassHash,
    pub sender_address: ContractAddress,
    pub nonce_data_availability_mode: DataAvailabilityMode,
    pub fee_data_availability_mode: DataAvailabilityMode,
    pub paymaster_data: PaymasterData,
    pub account_deployment_data: AccountDeploymentData,
    pub version: TransactionVersion,
    pub r#type: DeclareType,
}
```

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-:-NuxRRO95_TJJb64hTni:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYtDA50aS4TTXxDTbf:-NuxOnco41ujO2KIuAoL:b-ak2vc) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Sure.

[Declare](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1985)
[Deploy account](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L2430)
[Invoke](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L2688)
</blockquote></details>

Should we link to this inside the external transaction docstrings?

___
___
*[`src/data_availability.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxNWhA5sx4IjKSHoBQ:-NuxNWhA5sx4IjKSHoBR:bxu6gyg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/data_availability.rs#L36)):*
> ```XML
>         }
>     }
> }
> ```

Add short docstring explaining what this does, and why.



_Code quote:_
```XML
#[derive(Deserialize)]
#[serde(untagged)]
enum Deserializer {
    Num(u8),
    Text(String),
}

impl TryFrom<Deserializer> for DataAvailabilityMode {
    type Error = StarknetApiError;

    fn try_from(value: Deserializer) -> Result<Self, Self::Error> {
        match value {
            Deserializer::Num(0_u8) => Ok(DataAvailabilityMode::L1),
            Deserializer::Num(1_u8) => Ok(DataAvailabilityMode::L2),
            Deserializer::Text(text) if &text == "L1" => Ok(DataAvailabilityMode::L1),
            Deserializer::Text(text) if &text == "L2" => Ok(DataAvailabilityMode::L2),
            _ => Err(StarknetApiError::OutOfRange {
                string: "Data availability must be either 'L1' or '0' for L1, or 'L2' or '1' for \
                         L2."
                .to_string(),
            }),
        }
    }
}
```
___
*[`src/external_transaction.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYnwIl2RMIpWf5a-fi:-NuxO69Z2a8JpfEAFeFT:bze417e) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L4)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It's a trait used for `serde_repr`. In the external transaction, I used `#[repr(u8)]` in `DataAvailabilityMode` enum to serialize a `u8` value into an enum value.
</blockquote></details>

Stale.
___
*[`src/external_transaction.rs` line 134 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NusciT9-c-85dDgFpI4:-NuxO2HeD-xxLEISfooj:bnjoe47) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fe34a8038f8678d117e789bdd6319dd28352c839/src/external_transaction.rs#L134)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It doesn't have the same fields. For example: `ClassHash`.
</blockquote></details>

:sob: 
___
*[`src/external_transaction.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxPLwiDbpPwweJM27Y:-NuxPLwiDbpPwweJM27Z:b26m1p4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/external_transaction.rs#L1)):*
> ```XML
> use std::collections::HashMap;
> ```

Organize the items by importance, it should be consistent.

For example, the unversioned tx types (lik `ExternalInvokeTransaction`) should be bunched together, because they all have equal importance, rather than spread in between other items.
Whether their chunk should appear before the versioned types or after, I leave to you to decide :)
___
*[`src/external_transaction.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxOS_K9OGkyCFZuMA_:-NuxOS_K9OGkyCFZuMAa:b-yubwf3) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/external_transaction.rs#L17)):*
> ```XML
> #[serde(tag = "type")]
> pub enum ExternalTransaction {
>     /// A declare transaction.
> ```

Also the other ones in this enum, the variant name is self-explanatory.
___
*[`src/external_transaction.rs` line 30 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxOfR56ZlSDUSmgMWK:-NuxOfR56ZlSDUSmgMWL:b-2jef2g) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/external_transaction.rs#L30)):*
> ```XML
> /// A deploy account transaction that can be added to Starknet through the Starknet gateway.
> /// It has a serialization format that the Starknet gateway accepts in the `add_transaction`
> /// HTTP method.
> ```

Should we link to the 



_Code quote:_
```XML
/// A deploy account transaction that can be added to Starknet through the Starknet gateway.
/// It has a serialization format that the Starknet gateway accepts in the `add_transaction`
/// HTTP method.
```
___
*[`src/external_transaction.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxP2TOAAWd1X3_xUeC:-NuxP2TOAAWd1X3_xUeD:bmi8ppe) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/external_transaction.rs#L54)):*
> ```XML
>     #[serde(rename = "0x3")]
>     V3(ExternalDeployAccountTransactionV3),
> }
> ```

:100: 



_Code quote:_
```XML
#[serde(tag = "version")]
pub enum ExternalDeployAccountTransaction {
    #[serde(rename = "0x3")]
    V3(ExternalDeployAccountTransactionV3),
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/220)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYtDA50aS4TTXxDTbf:-NuxpVWdDnbnLuQL6v8S:buzajyg) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should we link to this inside the external transaction docstrings?
</blockquote></details>

I'll handle you non-blocking comments in a different PR.

___
___
*[`src/data_availability.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxNWhA5sx4IjKSHoBQ:-Nuxpb4D8R3_E4gZeF5u:buzajyg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/data_availability.rs#L36)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add short docstring explaining what this does, and why.
</blockquote></details>

I'll handle you non-blocking comments in a different PR.
___
*[`src/external_transaction.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuYnwIl2RMIpWf5a-fi:-NuxTbh44OR6IfOYW5SP:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e1f10e150ac5cf74928677e06b57062f7ea88da2/src/external_transaction.rs#L4)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Stale.
</blockquote></details>

Done.
___
*[`src/external_transaction.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxPLwiDbpPwweJM27Y:-NuxpcGCDnB-7LPs4Mn5:buzajyg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/external_transaction.rs#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Organize the items by importance, it should be consistent.

For example, the unversioned tx types (lik `ExternalInvokeTransaction`) should be bunched together, because they all have equal importance, rather than spread in between other items.
Whether their chunk should appear before the versioned types or after, I leave to you to decide :)
</blockquote></details>

I'll handle you non-blocking comments in a different PR.
___
*[`src/external_transaction.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxOS_K9OGkyCFZuMA_:-NuxpdYU8ZyGwRXCp0Et:buzajyg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/external_transaction.rs#L17)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also the other ones in this enum, the variant name is self-explanatory.
</blockquote></details>

I'll handle you non-blocking comments in a different PR.
___
*[`src/external_transaction.rs` line 30 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/220#-NuxOfR56ZlSDUSmgMWK:-NuxpeGA0ljemALLJjkB:buzajyg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51bc38a6027fab8bc0ba561db6e19570d15bce62/src/external_transaction.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should we link to the
</blockquote></details>

I'll handle you non-blocking comments in a different PR.

**Pull request merged**
