### PR TITLE
Add DeployAccountTransactionV3.

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/126#-NcvNjOT7ocPTqDScBkz:-NcvNjOT7ocPTqDScBl-:b-t4bab5) ([raw file](https://github.com/starkware-libs/starknet-api/blob/03a63bff75258e38cc1048bb9d537fb5fdb48528/src/transaction.rs#L182)):*
> ```XML
>     pub nonce_data_availability_mode: DataAvailabilityMode,
>     pub resource_bounds: ResourceBounds,
>     pub tip: Tip,
> ```

For consistency with the previous versions.



_Suggestion:_
```XML
    pub resource_bounds: ResourceBounds,
    pub tip: Tip,
    pub signature: TransactionSignature,
    pub nonce: Nonce,
    pub class_hash: ClassHash,
    pub contract_address_salt: ContractAddressSalt,
    pub constructor_calldata: Calldata,
    pub nonce_data_availability_mode: DataAvailabilityMode,
    pub fee_data_availability_mode: DataAvailabilityMode,
```
___
*[`src/transaction.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/126#-NcvNyiu5hqeAoh8aF47:-NcvNyivBc5Dz-3myRFy:b-qtt68p) ([raw file](https://github.com/starkware-libs/starknet-api/blob/03a63bff75258e38cc1048bb9d537fb5fdb48528/src/transaction.rs#L218)):*
> ```XML
>             Self::V3(_) => None,
>         }
>     }
> ```

I think we should implement this in Blockifier.



_Code quote:_
```XML
    pub fn max_fee(&self) -> Option<Fee> {
        match self {
            Self::V1(tx) => Some(tx.max_fee),
            Self::V3(_) => None,
        }
    }
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`src/transaction.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/126#-NcvNjOT7ocPTqDScBkz:-Nd-GrY70PA-wRKPxgvD:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/03a63bff75258e38cc1048bb9d537fb5fdb48528/src/transaction.rs#L182)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For consistency with the previous versions.
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 218 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/126#-NcvNyiu5hqeAoh8aF47:-Nd-HUpY3qCFcTGgrX1x:b-gm1wj) ([raw file](https://github.com/starkware-libs/starknet-api/blob/03a63bff75258e38cc1048bb9d537fb5fdb48528/src/transaction.rs#L218)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we should implement this in Blockifier.
</blockquote></details>

Done.
Removed

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126#-:-Nd-LD1Q6sfIBIWIl9ds:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/126#-Nd-LCGc5FPFVqJRarDz:-Nd-LCGc5FPFVqJRarE-:bno2j0r) (no related file):*
Blocking until we're ready to begin the upgrade process. 

___

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

___
*[`src/transaction.rs` line 159 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/126#-NdxSthtCn-iO3KsDCq2:-NdxSthtCn-iO3KsDCq3:b-wucedg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a2a0d44a44885b0bb4520ed810be8ece95dc8ba3/src/transaction.rs#L159)):*
> ```XML
> #[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub struct DeployAccountTransactionV3 {
>     pub resource: Resource,
> ```

Revert, use the bounds mapping instead.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @MohammadNassar1)

**Comment by barak-b-starkware** [comment]
Merged in [this](https://github.com/starkware-libs/starknet-api/pull/135) PR.

**Pull request closed without merging**
