### PR TITLE
Adding transaction V3

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`src/transaction.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaHBVKe7_ChY2Cgy46a:-NaHTPBx1pAIMkecjwJK:b-hvilbj) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bd1ba0b15571ceff588d4f5de393c0c1f1450493/src/transaction.rs#L69)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the meaning of that?
</blockquote></details>

To mark a particular variant of an enum as the default variant.
I enable the enum to derive the Default trait; basically, it is needed to get DeclareTransactionVX::default(), DeployAccountTransactionVX::default(), and InvokeTransactionVX::default().
___
*[`src/transaction.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaHEgAXBEsFQGlJwplp:-NaHRsYtE3TIBP-EgpLW:b-xw71cy) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bd1ba0b15571ceff588d4f5de393c0c1f1450493/src/transaction.rs#L84)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you choose it to have explicitly the three fields of `AccountParamsV0 `? Why not to have a field of type `AccountParamsV0 ` in this struct?
</blockquote></details>

Actually I think it is the same as we did in `DeclareTransactionV1` and `DeclareTransactionV2`, we have added explicitly the fields in both structs.

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaHEgAXBEsFQGlJwplp:-NaLFNJu2K6XDCcG0qJk:b-emhaka) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bd1ba0b15571ceff588d4f5de393c0c1f1450493/src/transaction.rs#L84)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Actually I think it is the same as we did in `DeclareTransactionV1` and `DeclareTransactionV2`, we have added explicitly the fields in both structs.
</blockquote></details>

IIUC we want to avoid that. That is the main reason to create this struct. WDYT?
Maybe V0 is not necessarily included inside V3 and then the current code is indeed better.

**Review by noaov1 — CHANGES_REQUESTED** [review]
Can you please add a pre-PR that adds all the new structs\enums (`StorageDomain`, `ResourceBounds`)?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-:-Naaz-0OEbwB2rcLqF-g:b40obz9)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-Naa_0VH-KjTrvYI6BF-:-Naa_0VI-xlg8zorXj_M:boa2qaa) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L99)):*
> ```XML
>     pub fee_da_mode: StorageDomain,
>     pub max_resouce_amount: Resources,
>     pub max_price_per_resource_unit: Resources,
> ```

Where `String` should be an enum of the resources names and `Bounds` is composed of two `u128` fields: `max_amount`, `max_price_per_unit`.



_Suggestion:_
```XML
    pub ResourceBounds: HashMap<String,(u128,u128)>,
```
___
*[`src/transaction.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaadWsuD4rfjq3QG8ZY:-NaadWsuD4rfjq3QG8ZZ:b-7zi8ni) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L100)):*
> ```XML
>     pub max_resouce_amount: Resources,
>     pub max_price_per_resource_unit: Resources,
>     pub tip: Tip,
> ```

WDYT?



_Suggestion:_
```XML
 pub tip: Fee
```
___
*[`src/transaction.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaadzjKCY--1aILDQp-:-NaadzjKCY--1aILDQp0:b-ytasln) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L111)):*
> ```XML
>         (tip, Tip)
>     );
> }
> ```

I think that it can be confusing to have getters for a simple struct with public fields but it's a non-blocking note.



_Code quote:_
```XML
impl AccountParamsV3 {
    implement_account_params_v3_getters!(
        (nonce_da_mode, StorageDomain),
        (fee_da_mode, StorageDomain),
        (max_resouce_amount, Resources),
        (max_price_per_resource_unit, Resources),
        (tip, Tip)
    );
}
```
___
*[`src/transaction.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaaeFwn6LbVwdpPAwF_:-NaaeFwo9XBLwaXe-O9_:buv1a16) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L121)):*
> ```XML
>         })*
>     };
> }
> ```

Why are we returning a reference?



_Code quote:_
```XML
macro_rules! implement_account_params_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(pub fn $field(&self) -> &$field_type {
            match self {
                Self::V0(tx) => &tx.$field,
                Self::V3(tx) => &tx.$field,
            }
        })*
    };
}
```

**Review by MohammadNassar1 — COMMENTED** [review]
Done.
https://github.com/starkware-libs/starknet-api/pull/111

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-:-NabNcQo8nOxodPXe3NF:b-v4tmxq)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @noaov1)

___
*[`src/transaction.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaHEgAXBEsFQGlJwplp:-NabFoi7DX-x9KlaAf8D:blpfgpr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bd1ba0b15571ceff588d4f5de393c0c1f1450493/src/transaction.rs#L84)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

IIUC we want to avoid that. That is the main reason to create this struct. WDYT?
Maybe V0 is not necessarily included inside V3 and then the current code is indeed better. 
</blockquote></details>

Following Elin suggestion, we'll keep the current code. Otherwise, we need to add c-tor functions as well.
___
*[`src/transaction.rs` line 99 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-Naa_0VH-KjTrvYI6BF-:-NabNw8O3PWVSt8-Dwyq:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L99)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where `String` should be an enum of the resources names and `Bounds` is composed of two `u128` fields: `max_amount`, `max_price_per_unit`.
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 100 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaadWsuD4rfjq3QG8ZY:-NabI1Xf9v8tuMBgALz_:byqels2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L100)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Agree :)
___
*[`src/transaction.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaadzjKCY--1aILDQp-:-NabIYybBHbfLPAi3ZKa:boswqek) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that it can be confusing to have getters for a simple struct with public fields but it's a non-blocking note.
</blockquote></details>

Agree with you!
Maybe we need to remove the AccountParamsV0 getter as well, WDYT?
___
*[`src/transaction.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaaeFwn6LbVwdpPAwF_:-NabIgix9aJVdpuTtPx4:b-e01zek) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L121)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why are we returning a reference?
</blockquote></details>

Correct, changed to clone!

**Review by noaov1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaadzjKCY--1aILDQp-:-NafsVbD8hlS9iVmwVaa:b-ufm0c9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L111)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Agree with you!
Maybe we need to remove the AccountParamsV0 getter as well, WDYT?
</blockquote></details>

Great :)
___
*[`src/transaction.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NafueWU0Y_q5GY10plm:-NafueWU0Y_q5GY10pln:bavfquh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ad3f543202e5eb2fe4d6fb5a5face791f710c5fd/src/transaction.rs#L165)):*
> ```XML
>         )*
>     };
> }
> ```

Can you please explain why you decided to have 3 macros (and not 1)?
Do you have an idea in mind how it will work when we want to add getters to `V3` fields?



_Code quote:_
```XML
macro_rules! implement_declare_tx_account_params_getters {
    ($(($field:ident, $field_type:ty)),*) => {
        $(
            pub fn $field(&self) -> $field_type {
                match self {
                    Self::V0(tx) => tx.account_params.$field.clone(),
                    Self::V1(tx) => tx.account_params.$field.clone(),
                    Self::V2(tx) => tx.account_params.$field.clone(),
                    Self::V3(tx) => tx.account_params.$field.clone(),
                }
            }
        )*
    };
}
```
___
*[`src/transaction.rs` line 190 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaftbS28sRBzsqm7DrS:-NaftbS28sRBzsqm7DrT:ba3dfna) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ad3f543202e5eb2fe4d6fb5a5face791f710c5fd/src/transaction.rs#L190)):*
> ```XML
>     pub account_params: AccountParamsV0,
>     pub class_hash: ClassHash,
>     pub version: TransactionVersion,
> ```

Remove?



_Code quote:_
```XML
pub version: TransactionVersion,
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`src/transaction.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaadzjKCY--1aILDQp-:-NagLD3QBAT0KIpC5Ky3:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/20a0ea34cb201b1128d98cb27a7a35e979a1c4ca/src/transaction.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Great :)
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NafueWU0Y_q5GY10plm:-NagKInN8UdxGwX1grFy:b-q2xnit) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ad3f543202e5eb2fe4d6fb5a5face791f710c5fd/src/transaction.rs#L165)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why you decided to have 3 macros (and not 1)?
Do you have an idea in mind how it will work when we want to add getters to `V3` fields?
</blockquote></details>

Since other transactions have different transactions versions, and different AccountParams versions.
___
*[`src/transaction.rs` line 190 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaftbS28sRBzsqm7DrS:-NagYJQ4APikBsjuzVMM:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ad3f543202e5eb2fe4d6fb5a5face791f710c5fd/src/transaction.rs#L190)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/lib.rs` line 25 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-Nak2Em61P2kEP8PKw6O:-Nak2Em76il917whKDn0:bhjqkge) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9119623ad755709a8cdd406a746b8e46a1ee85d1/src/lib.rs#L25)):*
> ```XML
>     InnerDeserialization(#[from] InnerDeserializationError),
>     #[error("An InvokeFunction transaction (version = 0) cannot have a nonce.")]
>     InvalidTransactionNonce,
> ```

Why is it needed?



_Code quote:_
```XML
    #[error("An InvokeFunction transaction (version = 0) cannot have a nonce.")]
    InvalidTransactionNonce,
```
___
*[`src/transaction.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NafueWU0Y_q5GY10plm:-NakecYy5Ra1LESZb5lQ:bca5lkj) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ad3f543202e5eb2fe4d6fb5a5face791f710c5fd/src/transaction.rs#L165)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Since other transactions have different transactions versions, and different AccountParams versions.
</blockquote></details>

Wasn't it also true before? How does the AccountParams versions affect?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`src/transaction.rs` line 165 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NafueWU0Y_q5GY10plm:-NalRt_y5kq5dig5iBqv:b-7751lc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ad3f543202e5eb2fe4d6fb5a5face791f710c5fd/src/transaction.rs#L165)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Wasn't it also true before? How does the AccountParams versions affect?
</blockquote></details>

No, since now we have different AccountParams versions.
I managed to solve it.
___
*[`src/lib.rs` line 25 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-Nak2Em61P2kEP8PKw6O:-Nal2ej69urAFZeP_6g8:b-ey0mkz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9119623ad755709a8cdd406a746b8e46a1ee85d1/src/lib.rs#L25)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

It's not needed. It pops up when rebasing.
Removed.

**Review by noaov1 — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 169 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaqQyYe-UT3Mg4jZv__:-NaqQyYe-UT3Mg4jZv_a:b-w2qrry) ([raw file](https://github.com/starkware-libs/starknet-api/blob/aba94122c5647110c5cb32829234e2047d552286/src/transaction.rs#L169)):*
> ```XML
>             Self::V3(tx) => tx.transaction_params.nonce,
>         }
>     }
> ```

Maybe add a getter to the `compiled_class_hash` field?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`src/transaction.rs` line 169 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-NaqQyYe-UT3Mg4jZv__:-NavkDP96ObIWmqP2KtN:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/aba94122c5647110c5cb32829234e2047d552286/src/transaction.rs#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe add a getter to the `compiled_class_hash` field?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/108#-:-Nb8etYt5TZE_auKukIt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
