### PR TITLE
Add TryFrom<StarkFelt> for u64.

### PR DESCRIPTION
**Pull request by ArniStarkware**
Used to extract integers from felts.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/87)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
Will solve the following issue: https://reviewable.io/reviews/starkware-libs/blockifier/604#-NYYUEMbEbZRbWbc0gLD

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/87)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @dafnamatsry, and @elintul)

___
*[`src/hash.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/87#-NYm27f25n_t86o4-Io8:-NYm27f36bol0TraqnXh:b-vir6qv) ([raw file](https://github.com/starkware-libs/starknet-api/blob/690c0296ee42aee019816cd81425cdfc3c802604/src/hash.rs#L209)):*
> ```XML
> // TODO(Arni, 1/1/2024): Remove impl TryFrom<StarkFelt> for u64. Implement arethmetic operations on
> //  StarkFelt.
> impl TryFrom<StarkFelt> for u64 {
> ```

Do we want these for the rest of the `uX` (is there motivation to do so I mean)? 

If so, there is a macro Dori wrote called `impl_from_through_intermediate` that will generate the remaining `impl`s.



_Code quote:_
```XML
impl TryFrom<StarkFelt> for u64 {
```
___
*[`src/hash.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/87#-NYm9ShqBH0aMww2WHOg:-NYm9ShqBH0aMww2WHOh:bcx65aq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/690c0296ee42aee019816cd81425cdfc3c802604/src/hash.rs#L220)):*
> ```XML
>         }
> 
>         Ok(u64::from_be_bytes(u64_bytes.try_into().expect("u64_bytes should be of size u64.")))
> ```

Just a suggestion (cause your code is totally fine):

I think we can simplify, given that we know the size of `u64` (unlike the case for the `usize` conversion).
Also, I think it's OK to `unwrap` here since it is trivially infallible.



_Suggestion:_
```XML
        let felt_in_bytes: [u8; 32] = felt.0;

        // Check if all bytes above 8th are zeros
        if felt_in_bytes.iter().take(24).any(|&byte| byte != 0) {
            return Err(StarknetApiError::OutOfRange { string: felt.to_string() });
        }

        // Convert the last 8 bytes into u64
        let bytes: [u8; 8] = felt.bytes()[24..].try_into().unwrap();
        Ok(u64::from_be_bytes(bytes))
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/87)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dafnamatsry and @elintul)

___
*[`src/hash.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/87#-NYm27f25n_t86o4-Io8:-NYmHIOY-ylrUUKEwxxK:b-czqw5j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/690c0296ee42aee019816cd81425cdfc3c802604/src/hash.rs#L209)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we want these for the rest of the `uX` (is there motivation to do so I mean)? 

If so, there is a macro Dori wrote called `impl_from_through_intermediate` that will generate the remaining `impl`s.
</blockquote></details>

I do want these - but mostly platonically.
We do not want to implement conversion from Felt to integer types generally. We want Felt to have implemented arithmetic and direct correct conversions. We allow this conversion as a hack.

Documented accordingly. 
___
*[`src/hash.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/87#-NYm9ShqBH0aMww2WHOg:-NYmHxrzB5BwhRlTmpyf:b468qyz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/690c0296ee42aee019816cd81425cdfc3c802604/src/hash.rs#L220)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Just a suggestion (cause your code is totally fine):

I think we can simplify, given that we know the size of `u64` (unlike the case for the `usize` conversion).
Also, I think it's OK to `unwrap` here since it is trivially infallible.
</blockquote></details>

1. I don’t want the magic number `24` to appear without its clear role.

2. Which is better?
`if felt_in_bytes.iter().take(COMPLIMENT_OF_U64).any(|&byte| byte != 0) {` VS `if rest != [0u8; COMPLIMENT_OF_U64]`?

3. The compiler does not like `unwrap` instead of `expect`.
```
error: used `unwrap()` on a `Result` value
   --> src/hash.rs:219:40
    |
219 |         let bytes: [u8; SIZE_OF_U64] = u64_bytes.try_into().unwrap();
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: if you don't want to handle the `Err` case gracefully, consider using `expect()` to provide a better panic message
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used
    = note: requested on the command line with `-D clippy::unwrap-used`
```

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @elintul)

___
*[`src/hash.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/87#-NYm27f25n_t86o4-Io8:-NYn4tUgCYLhc8NcObJq:bc52tdo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/690c0296ee42aee019816cd81425cdfc3c802604/src/hash.rs#L209)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I do want these - but mostly platonically.
We do not want to implement conversion from Felt to integer types generally. We want Felt to have implemented arithmetic and direct correct conversions. We allow this conversion as a hack.

Documented accordingly. 
</blockquote></details>

:laughing: 
___
*[`src/hash.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/87#-NYm9ShqBH0aMww2WHOg:-NYn5708DYEl6K-xQxBV:bhw1ffb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/690c0296ee42aee019816cd81425cdfc3c802604/src/hash.rs#L220)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

1. I don’t want the magic number `24` to appear without its clear role.

2. Which is better?
`if felt_in_bytes.iter().take(COMPLIMENT_OF_U64).any(|&byte| byte != 0) {` VS `if rest != [0u8; COMPLIMENT_OF_U64]`?

3. The compiler does not like `unwrap` instead of `expect`.
```
error: used `unwrap()` on a `Result` value
   --> src/hash.rs:219:40
    |
219 |         let bytes: [u8; SIZE_OF_U64] = u64_bytes.try_into().unwrap();
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: if you don't want to handle the `Err` case gracefully, consider using `expect()` to provide a better panic message
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used
    = note: requested on the command line with `-D clippy::unwrap-used`
```

</blockquote></details>

1) Fair enough
2) First one i think, easier to parse, but second one is also fine.
3) Oh yes it is a residue from when we started out and were super strict about our unwraps :sweat_smile: can you please remove `"-Dclippy::unwrap_used"` from `.carg/config.toml` and remove `-allow-unwrap-in-tests = true` from `.clippy.toml` (leaving the file empty)?

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/87)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`src/hash.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/87#-NYm9ShqBH0aMww2WHOg:-NYn7oEX0zYBt75B9w22:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/690c0296ee42aee019816cd81425cdfc3c802604/src/hash.rs#L220)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

1) Fair enough
2) First one i think, easier to parse, but second one is also fine.
3) Oh yes it is a residue from when we started out and were super strict about our unwraps :sweat_smile: can you please remove `"-Dclippy::unwrap_used"` from `.carg/config.toml` and remove `-allow-unwrap-in-tests = true` from `.clippy.toml` (leaving the file empty)?
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry and @elintul)

**Pull request merged**
