### PR TITLE
Change serialization of EntryPointOffset to hex.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/102)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/102)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/102#-N_hIs98B7iZ0_9Cbl20:-N_hIs99-qp6tjlXCGus:b9znng7) (no related file):*
To match the expected serialization in the spec.

___

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/102)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

**Review by nagmo-starkware — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/102)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/102#-N_hIs98B7iZ0_9Cbl20:-N_hYPTt1PKvA3dbG0Tr:b-vodwrm) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

To match the expected serialization in the spec.
</blockquote></details>

note that this is not backwards compatible. it requires a change in our code base as well

___

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #102** <a href="https://app.graphite.dev/github/pr/starkware-libs/starknet-api/102" target="_blank">Graphite</a>  👈
    * **PR #100** <a href="https://app.graphite.dev/github/pr/starkware-libs/starknet-api/100" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/starknet-api/102?utm_source=stack-comment).

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/102)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/102#-N_hIs98B7iZ0_9Cbl20:-N_hdWk60JCA5AFp0bc1:bc04cqq) (no related file):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

note that this is not backwards compatible. it requires a change in our code base as well
</blockquote></details>

I think it should be implemented on the Client/Gateway struct instead of SN_API.
We don't want to store it like this in the storage.
Also, not only that it might break our code (I'm not sure), but it requires bumping the storage version (and a new snapshot, etc.)

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think it should be implemented on the Client/Gateway struct instead of SN_API.
We don't want to store it like this in the storage.
Also, not only that it might break our code (I'm not sure), but it requires bumping the storage version (and a new snapshot, etc.)
</blockquote></details>

nvm, forgot what I wrote, it is not how we store the data...

**Review by nagmo-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/102)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @DvirYo-starkware)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/102#-:-N_mUYlk8csez3HQlWbl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @DvirYo-starkware, and @nagmo-starkware)

**Pull request merged**
