### PR TITLE
Restore default definitions.

### PR DESCRIPTION
**Pull request by Adi-Yakovian**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/16)

### CODE REVIEW

**Review by anatgstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/16#-:-NKn5zStBC9rmbAJbXf7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @elintul)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/16#-:-NKvyEkc81-dWaDhMi7v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Adi-Yakovian)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Adi-Yakovian)

**Review by elintul — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/16)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Adi-Yakovian)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Adi-Yakovian)

**Pull request merged**
