### PR TITLE
From<Fee> for StarkFelt

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/63#-NVZU68y2aENx1Y1I87D:-NVZU68y2aENx1Y1I87E:b2ih2qm) (no related file):*
Several things happening here:
1. Bump `cairo-lang-starknet` version (otherwise PR is broken).
2. Implement `From<u128> for StarkFelt`.
3. Changed `x` -> `x_64` where needed in `StarkFelt::from(x)` (so the compiler knows which `From` to use, `u64` or `u128`.
4. Implement + test `From<Fee> for StarkFelt`.

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/63#-NVZWQ8j9VM6m8oVFGLI:-NVZWQ8j9VM6m8oVFGLJ:b-lu0uxe) (no related file):*
@giladchase do you think I should just delete the `From<u64> for StarkFelt`? That way, I could delete all the `_64`s I sprinkled everywhere, only one int->obj converter so it's not ambiguous...
I'll push another commit and see if it works

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/63#-NVZWQ8j9VM6m8oVFGLI:-NVZckfS7vnA4C7xvGbr:b-c5vf93) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase do you think I should just delete the `From<u64> for StarkFelt`? That way, I could delete all the `_64`s I sprinkled everywhere, only one int->obj converter so it's not ambiguous...
I'll push another commit and see if it works
</blockquote></details>

Might be missing something here, where are you using `x_64` here? (number 3 above)

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/63#-NVZWQ8j9VM6m8oVFGLI:-NVZdTJd-jAEdJWo5bEk:b2jp4w9) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Since i deleted `From<u64> for StarkFelt`, it is no longer needed
</blockquote></details>

Oh i saw the revision now :)
I think it's fine, but keep in mind that most API I see that have a from<128> also have for all smaller ones.
It might be just a coincidence, or maybe we're missing something, we'll know later I guess :)

___

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/63#-:-NVZojJ2487nQ7a4VOlp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
