### PR TITLE
Invoke transaction v0 fix

### PR DESCRIPTION
**Pull request by nagmo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/90)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/90)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @dan-starkware, and @nagmo-starkware)

___
*[`src/transaction.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/90#-NZ_pXFM2k6cVJ0v3sHb:-NZ_pXFM2k6cVJ0v3sHc:b-4xm2kr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fa4437206bfcf6dd9f43edba159bced442a8c268/src/transaction.rs#L213)):*
> ```XML
>     pub fn nonce(&self) -> Nonce {
>         match self {
>             InvokeTransaction::V0(_) => unreachable!("V0 invoke txs don't have a nonce"),
> ```

Why implement getters on structs that don't have the members?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/90)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dan-starkware, and @yair-starkware)

___
*[`src/transaction.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/90#-NZ_pXFM2k6cVJ0v3sHb:-NZaAKt29JyXTH24zooK:b2gtlvo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fa4437206bfcf6dd9f43edba159bced442a8c268/src/transaction.rs#L213)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why implement getters on structs that don't have the members?
</blockquote></details>

removed after discussing with @alonh5 . please read the commit message for info

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/90#-:-NZaBJTkAGGUTmBM55Mm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> Dismissed @yair-starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
