### PR TITLE
Fix: replace web3 with primitive-types

### PR DESCRIPTION
**Pull request by MegaRedHand**
The _web3_ version currently in use has known vulnerabilities that trigger _dependabot_ alerts. This PR replaces it, as it was only used for its `H160` type - a reexport of _primitive-types_ with the _"serde"_ feature.

Alternatively, we could update the _web3_ dependency to the latest version and disable default features. This would leave us the option of later enabling those features as needed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/47)

### CODE REVIEW

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/47#-:-NUIaEdb63n09Xs4rV1W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MegaRedHand)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MegaRedHand)

**Review by MegaRedHand — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MegaRedHand)

**Comment by MegaRedHand** [comment]
Sorry, I'm new to _Reviewable_. Do I need to do something there?
(I'm asking because of the "waiting on @MegaRedHand" part)

**Comment by dan-starkware** [comment]
I don't think so, Just click "Merge when ready" on GitHub.

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MegaRedHand)

**Comment by MegaRedHand** [comment]
I can't merge PRs because I don't have **write access** to this repository. Sorry but could you do it for me? Thanks in advance!

**Review by dan-starkware — APPROVED** [review]

**Pull request closed without merging**
