### PR TITLE
Yoav/block hash/receipt hash

### PR DESCRIPTION
**Pull request by yoavGrs**
Calculations for the receipt hash.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/242)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/242)* status: all files reviewed, 6 unresolved discussions (waiting on @yair-starkware and @yoavGrs)

___
*[`src/block_hash/receipt_commitment.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHv-rB0WYnlk7wlSX7:-NxHv-rB0WYnlk7wlSX8:b-t8p67f) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L53)):*
> ```XML
> }
> 
> fn as_stark_felt(arr: &[u8; 20]) -> StarkFelt {
> ```

Please make sure the input has the same endian as StarkFelt::new_unchecked.
In general, why not use `message_sent.to_address.0.into()`?
___
*[`src/block_hash/receipt_commitment.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHu_Zq9YI7TQCSzpV4:-NxHu_Zq9YI7TQCSzpV5:b-u0stfy) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L64)):*
> ```XML
>         TransactionExecutionStatus::Succeeded => StarkFelt::ZERO,
>         TransactionExecutionStatus::Reverted(reason) => {
>             ascii_as_felt(&reason.revert_reason).expect("ascii_as_felt failed for revert reason")
> ```

This should be a keccak of this ascii_as_felt. If you don't have a keccak implementation right now, I'm ok with a TODO to fix this.
___
*[`src/block_hash/receipt_commitment.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHrCpOELv-vFdhT0Tr:-NxHrCpOELv-vFdhT0Ts:bhorynm) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L78)):*
> ```XML
>     execution_resources: &ExecutionResources,
> ) -> HashChain {
>     let l1_gas_consumed = execution_resources.da_l1_data_gas_consumed
> ```

This should be da_l1_gas_consumed, and in the bottom you should use da_l1_data_gas_consumed instead of da_l1_gas_consumed
___
*[`src/block_hash/receipt_commitment.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHrRSR8hbw8oHFIgwJ:-NxHrRSR8hbw8oHFIgwK:bspga9r) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L79)):*
> ```XML
> ) -> HashChain {
>     let l1_gas_consumed = execution_resources.da_l1_data_gas_consumed
>         + execution_resources.steps
> ```

This should be multiplied by gas per step which we get from versioned constants. For now add a constant called L1_GAS_PER_STEP (with value 1) and add a TODO to get the value from versioned constants
___
*[`src/block_hash/receipt_commitment.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHreQP1U_f-P1P0Kp8:-NxHreQP1U_f-P1P0Kp9:brtywsk) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L80)):*
> ```XML
>     let l1_gas_consumed = execution_resources.da_l1_data_gas_consumed
>         + execution_resources.steps
>         + execution_resources.builtin_instance_counter.values().sum::<u64>();
> ```

This should be multiplied by gas per step which we get from versioned constants. For now add a constant called L1_GAS_PER_BUILTIN_INSTANCE (with value 1) and add a TODO to get the value from versioned constants
___
*[`src/block_hash/receipt_commitment.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHrLQxCDt9omFxItaC:-NxHrLQxCDt9omFxItaD:b-gxorm) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L82)):*
> ```XML
>         + execution_resources.builtin_instance_counter.values().sum::<u64>();
>     hash_chain
>         .chain(&StarkFelt::ZERO)
> ```

Add a comment that this zero is L2 gas consumed

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/242)* status: all files reviewed, 6 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`src/block_hash/receipt_commitment.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHv-rB0WYnlk7wlSX7:-NxI59Pn8d5B-ZBp6hNU:b-cn35u) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Please make sure the input has the same endian as StarkFelt::new_unchecked.
In general, why not use `message_sent.to_address.0.into()`?
</blockquote></details>

Added to the test.

There is no conversion of 20 bytes into StarkFelt.
Is it better to define a `new` (safe) function for StarkFelt, which receives a byte array shorter than 32?
___
*[`src/block_hash/receipt_commitment.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHu_Zq9YI7TQCSzpV4:-NxI81-v0A9mlaHiz-hp:b-dyikak) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L64)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be a keccak of this ascii_as_felt. If you don't have a keccak implementation right now, I'm ok with a TODO to fix this.
</blockquote></details>

TODO for now.
___
*[`src/block_hash/receipt_commitment.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHrCpOELv-vFdhT0Tr:-NxI9Ii3-bGTXCK9Ylwo:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L78)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be da_l1_gas_consumed, and in the bottom you should use da_l1_data_gas_consumed instead of da_l1_gas_consumed
</blockquote></details>

Done.
___
*[`src/block_hash/receipt_commitment.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHrRSR8hbw8oHFIgwJ:-NxIAnBuAhbtQCKPGngH:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L79)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be multiplied by gas per step which we get from versioned constants. For now add a constant called L1_GAS_PER_STEP (with value 1) and add a TODO to get the value from versioned constants
</blockquote></details>

Done.
___
*[`src/block_hash/receipt_commitment.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHreQP1U_f-P1P0Kp8:-NxIAn-G1N5puF2yvCdH:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L80)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This should be multiplied by gas per step which we get from versioned constants. For now add a constant called L1_GAS_PER_BUILTIN_INSTANCE (with value 1) and add a TODO to get the value from versioned constants
</blockquote></details>

Done.
___
*[`src/block_hash/receipt_commitment.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHrLQxCDt9omFxItaC:-NxI8v9b4xyR5flTlNds:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L82)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add a comment that this zero is L2 gas consumed
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/242)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware and @yoavGrs)

___
*[`src/block_hash/receipt_commitment.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHv-rB0WYnlk7wlSX7:-NxIE0HQ72y4DUytKJBa:bgk91k7) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L53)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Added to the test.

There is no conversion of 20 bytes into StarkFelt.
Is it better to define a `new` (safe) function for StarkFelt, which receives a byte array shorter than 32?
</blockquote></details>

You're converting the address to bytes and the bytes to felt. Isn't there a converter directly from address to felt

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/242)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

___
*[`src/block_hash/receipt_commitment.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-NxHv-rB0WYnlk7wlSX7:-NxIF7Uo3ZIM78f9LmDU:bboa55k) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1c07e2908fe35b517137188c4913bd49b1dcbd4b/src/block_hash/receipt_commitment.rs#L53)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

You're converting the address to bytes and the bytes to felt. Isn't there a converter directly from address to felt
</blockquote></details>

You're right, there is.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/242#-:-NxIFQ1Z82mlea8Lp_VA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
