### PR TITLE
feat: add l1_gas_consumed for block hash

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/268)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/268)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yoavGrs)

___
*[`src/transaction.rs` line 969 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzSyWK9DJ_J0-EJJGQc:-NzSyWK9DJ_J0-EJJGQd:b-snab8u) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e5f4bc7b3aabdc1a04ca96999592dd8546a0537e/src/transaction.rs#L969)):*
> ```XML
>     pub da_l1_gas_consumed: u64,
>     pub da_l1_data_gas_consumed: u64,
>     pub l1_gas_consumed: u64,
> ```

what about data gas?



_Code quote:_
```XML
pub l1_gas_consumed: u64,
```
___
*[`src/block_hash/receipt_commitment.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzSyxdLDqZv42iKRXXq:-NzSyxdMAOBauCkCOgss:b-71m63u) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e5f4bc7b3aabdc1a04ca96999592dd8546a0537e/src/block_hash/receipt_commitment.rs#L95)):*
> ```XML
>         .chain(&Felt::ZERO) // L2 gas consumed
>         .chain(&execution_resources.l1_gas_consumed.into())
>         .chain(&execution_resources.da_l1_data_gas_consumed.into())
> ```

not data-availability related gas; just total L1 blob gas



_Suggestion:_
```XML
l1_data_gas_consumed
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/268)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yoavGrs)

___
*[`src/transaction.rs` line 965 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzTIqqI2SLbov7xJSRI:-NzTIqqI2SLbov7xJSRJ:b-mrley0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/976b5ff30f3fc6a99f8f3bd81ca4edc9a03a68d2/src/transaction.rs#L965)):*
> ```XML
>     pub l1_gas: u64,
>     pub l1_data_gas: u64,
> }
> ```

why u64s? in the blockifier they're u128



_Code quote:_
```XML
pub struct GasVector {
    pub l1_gas: u64,
    pub l1_data_gas: u64,
}
```
___
*[`src/block_hash/test_utils.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzTJ7yPAYV9RDerPeEM:-NzTJ7yPAYV9RDerPeEN:b-p7ec8m) ([raw file](https://github.com/starkware-libs/starknet-api/blob/976b5ff30f3fc6a99f8f3bd81ca4edc9a03a68d2/src/block_hash/test_utils.rs#L24)):*
> ```XML
>         memory_holes: 76,
>         da_gas_consumed: GasVector { l1_gas: 54, l1_data_gas: 10 },
>         gas_consumed: GasVector { l1_gas: 16580, l1_data_gas: 32 },
> ```

where did the `10` come from?



_Code quote:_
```XML
        da_gas_consumed: GasVector { l1_gas: 54, l1_data_gas: 10 },
        gas_consumed: GasVector { l1_gas: 16580, l1_data_gas: 32 },
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/268)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`src/transaction.rs` line 965 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzTIqqI2SLbov7xJSRI:-NzTOFnX6gTI2Bgmd0nj:b-v9u32l) ([raw file](https://github.com/starkware-libs/starknet-api/blob/976b5ff30f3fc6a99f8f3bd81ca4edc9a03a68d2/src/transaction.rs#L965)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why u64s? in the blockifier they're u128
</blockquote></details>

There was a u64 here before my change.
Would you like me to change it?
___
*[`src/block_hash/test_utils.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzTJ7yPAYV9RDerPeEM:-NzTNjvC-Z88fr8fsxab:bzd7x37) ([raw file](https://github.com/starkware-libs/starknet-api/blob/976b5ff30f3fc6a99f8f3bd81ca4edc9a03a68d2/src/block_hash/test_utils.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where did the `10` come from?
</blockquote></details>

It's a new number.
The 32 was taken to preserve the hash, and I want a different number here.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/268)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @ShahakShama)

___
*[`src/transaction.rs` line 965 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzTIqqI2SLbov7xJSRI:-NzTUhiu2WvLeQjTGA27:bdctg8b) ([raw file](https://github.com/starkware-libs/starknet-api/blob/976b5ff30f3fc6a99f8f3bd81ca4edc9a03a68d2/src/transaction.rs#L965)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in the `ExecutionResources` struct?
I would run this by @Yoni-Starkware
</blockquote></details>

u64 is enough, but `gas_price` must be u128 and @dorimedini-starkware set `gas` to u128 because we need to multiple them. 

I see that other fields are not consistent with the blockifier as well. 
Whatever you choose

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`src/transaction.rs` line 965 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/268#-NzTIqqI2SLbov7xJSRI:-NzWy6kN6ALPnE0QH5U6:b-8hs70z) ([raw file](https://github.com/starkware-libs/starknet-api/blob/976b5ff30f3fc6a99f8f3bd81ca4edc9a03a68d2/src/transaction.rs#L965)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

u64 is enough, but `gas_price` must be u128 and @dorimedini-starkware set `gas` to u128 because we need to multiple them. 

I see that other fields are not consistent with the blockifier as well. 
Whatever you choose
</blockquote></details>

`GasPrice` is u128

**Pull request merged**
