### PR TITLE
update cairo-lang-starknet dep to 2.5.0-dev.0

### PR DESCRIPTION
**Pull request by zuphitf**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/167)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/167#-:-Nmejga91wOpdb3V9olQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/167)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/167#-NmekKW06l8qBke91509:-NmekKW06l8qBke9150A:bq3unvp) (no related file):*
did you run `cargo build`?

___

**Comment by zuphitf** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

did you run `cargo build`?
</blockquote></details>

Yes, of course.
Cargo.lock is in `.gitignore` in this repo.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/167)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

**Pull request merged**
