### PR TITLE
Mohammad/transaction/transaction converters/add tx hash

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/225)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/225)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`src/external_transaction.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/225#-Nv0ir2u0dhPIs15kOW8:-Nv0ir2u0dhPIs15kOW9:bxg0oyz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/811257fa0080d15168321cd5be1738a0c7c367dc/src/external_transaction.rs#L255)):*
> ```XML
>             });
> 
>         let tx_hash = tx.calculate_transaction_hash(chain_id, &TransactionVersion::THREE).unwrap();
> ```

I think we might have missed this during the review, `tx.calculate_transaction_hash ` where `tx` is `InvokeTransactionV3`, shouldn't have to pass transactionVersion as an arg, as the info is encoded inside `InvokeTransactionV3` and can be hardcoded in the `impl` of this method.
Not critical for here though 



_Code quote:_
```XML
        let tx_hash = tx.calculate_transaction_hash(chain_id, &TransactionVersion::THREE).unwrap();
```

**Review by giladchase — COMMENTED** [review]
where is the ChainId being passed from?
Can you give a usage example plz?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/225#-:-Nv0jhOs8TdspvQLeBP8:bzdza2i)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @elintul)

**Review by MohammadNassar1 — COMMENTED** [review]
It should be part of the `gateway_config`. 
Then, once the gateway receives external tx, it calls `into_internal`, and sends the relevant chain id.
See [this](https://reviewable.io/reviews/starkware-libs/mempool/13) PR.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/225#-:-Nv0mJ9I5N0DWCf3vPk5:b-eli2kg)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`src/external_transaction.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/225#-Nv0ir2u0dhPIs15kOW8:-Nv0mk0dA66ba-a8wbWA:b8k8uu6) ([raw file](https://github.com/starkware-libs/starknet-api/blob/811257fa0080d15168321cd5be1738a0c7c367dc/src/external_transaction.rs#L255)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think we might have missed this during the review, `tx.calculate_transaction_hash ` where `tx` is `InvokeTransactionV3`, shouldn't have to pass transactionVersion as an arg, as the info is encoded inside `InvokeTransactionV3` and can be hardcoded in the `impl` of this method.
Not critical for here though
</blockquote></details>

Hmm, but in `DeclareTransactionV0V1` struct, we need to pass the TX version.
So, it should be part of the api.

**Review by giladchase — APPROVED** [review]
:pray: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/225#-:-Nv1xTbgDMD65r66ZRzF:bi9estx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

___
*[`src/external_transaction.rs` line 255 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/225#-Nv0ir2u0dhPIs15kOW8:-Nv1xkyr8-dr7bQRDgYB:b-bxrwcq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/811257fa0080d15168321cd5be1738a0c7c367dc/src/external_transaction.rs#L255)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Hmm, but in `DeclareTransactionV0V1` struct, we need to pass the TX version.
So, it should be part of the api.
</blockquote></details>

Sababa, but in the future i think we'll want to split v0v1 into v0 and v1, if this is causing us issues like this.
It also had a divergant behavior in the tx hash calculation, so that v0v1 is becoming less and less worth it.

**Pull request merged**
