### PR TITLE
fix: consider replace classes as deployed contracts

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/262)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/262)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`src/block_hash/state_diff_hash.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/262#-NyySQ0eEkk0yNTgwSiW:-NyySQ0eEkk0yNTgwSiX:b-hpk4y4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/95b88de49491862cfbeee320c90ec6f9400e071e/src/block_hash/state_diff_hash.rs#L25)):*
> ```XML
>     let mut hash_chain = HashChain::new();
>     hash_chain = hash_chain.chain(&STARKNET_STATE_DIFF0);
>     hash_chain = chain_updated_contracts(
> ```

You can keep calling it deployed. The end goal is to unite these two fields into a single field by 0.13.3
___
*[`src/block_hash/state_diff_hash_test.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/262#-NyySb7N2VnBlZvgnAsB:-NyySb7N2VnBlZvgnAsC:b-keywfy) ([raw file](https://github.com/starkware-libs/starknet-api/blob/95b88de49491862cfbeee320c90ec6f9400e071e/src/block_hash/state_diff_hash_test.rs#L31)):*
> ```XML
>     };
>     let replaced_classes_0 = indexmap! {
>         2u64.into() => ClassHash(2u64.into()),
> ```

Change the replaced contract address to be in the middle of the two deployed contracts to test the sorting

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/262)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/262#-NyyidVp207CYr8N1cwm:-NyyidVp207CYr8N1cwn:b-6voo94) (no related file):*
why did the regression tests result change? I see no change in `get_state_diff()` so no replaced classes means the hash should be the same, right?

___

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/262)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/262#-NyyidVp207CYr8N1cwm:-NyynEhq525clqKpTgJO:b-sxlp94) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did the regression tests result change? I see no change in `get_state_diff()` so no replaced classes means the hash should be the same, right?
</blockquote></details>

There were `replaced_classes` before, but we didn't consider them.

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/262#-:-Nyypqw--OB99nHGYQVZ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/262#-:-Nz1jDug2N8rDJPYY3tt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
