### PR TITLE
refactor: use small letters for rpc transaction enum

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/285)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Only rename? no logic changes?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/285#-:-O0NjFzP-22ODEZjR3C5:bpkic4v)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ArniStarkware and @elintul)

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/285#-:-O0OJpnL0N1EE4O5liJV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/285)* status: 0 of 33 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/285#-O0d9kkM9MuDrKWocyHz:-O0d9kkM9MuDrKWocyI-:b-ulzrdn) (no related file):*
Bad rebase? 

___

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/285)* status: 0 of 33 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/285#-O0d9kkM9MuDrKWocyHz:-O0d9oi04XAm-xoRgd1M:b-yhmioe) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Bad rebase?
</blockquote></details>

Note your target branch is `main-mempool`.:

___

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/285)* status: 0 of 33 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/285#-O0d9kkM9MuDrKWocyHz:-O0dCNrMCKKNrnmeZEea:beu6ypp) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Note your target branch is `main-mempool`.:
</blockquote></details>

Yeah, it was a bad rebase.
Fixed it.

___

**Review by elintul — APPROVED** [review]
> Reviewed 33 of 33 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/285)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

**Pull request merged**
