### PR TITLE
Generic uint->X converter

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`src/hash.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NV_LfhR4cpAntwzcPI5:-NV_LfhR4cpAntwzcPI6:bi4ew38) ([raw file](https://github.com/starkware-libs/starknet-api/blob/80a9762438f43e6f0c920cf4ccf334bde131b8b0/src/hash.rs#L42)):*
> ```XML
>         .iter()
>         .fold(StarkFelt::from(0_u8), |current_hash, felt| pedersen_hash(&current_hash, felt));
>     let data_len = StarkFelt::from(u128::try_from(felts.len()).expect("Got 2^128 felts or more."));
> ```

rust does not guarantee `usize <= u128`

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @alonh5 and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVdb4kb6MD3BnOKfDhB:-NVdb4kc2QDuCKZy52FE:b-5d387e) (no related file):*
Any idea how this will look in the blockifier/papyrus repos?

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @alonh5 and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVdb4kb6MD3BnOKfDhB:-NVdd6-w16YPcr0U6G2k:bf2jb4h) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Any idea how this will look in the blockifier/papyrus repos?
</blockquote></details>

Every `StarkFelt::from(7)` will no longer work, because it now becomes ambiguous.
If there exists some `x` of a type with *implicit conversions to u64 or u128*, then we may also hit errors on `StarkFelt::from(x)`.
Other than that, everything should be the same

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @alonh5 and @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVdb4kb6MD3BnOKfDhB:-NVddYYP1XsvfixYauBH:b-wnmeeb) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Every `StarkFelt::from(7)` will no longer work, because it now becomes ambiguous.
If there exists some `x` of a type with *implicit conversions to u64 or u128*, then we may also hit errors on `StarkFelt::from(x)`.
Other than that, everything should be the same
</blockquote></details>

I'll open a PR in papyrus so you can see

___

**Review by dan-starkware — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @dorimedini-starkware)

___
*[`src/hash.rs` line 158 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVhaj8C7ZVUPZV8EMc2:-NVhaj8C7ZVUPZV8EMc3:b7ofe0c) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a9326cb76de01d6b44184612ad3a1307c79cedab/src/hash.rs#L158)):*
> ```XML
> }
> 
> impl_from_small_uints!(StarkFelt);
> ```

Not sure about this one, but here's my rationale:

* Using this macro for `StarkFelt` makes sense, because writing each impl by hand will be subtly different, and the implementation is not totally trivial.
In other cases, when writing the `impl` is trivial for every type, it might be better just to write them out explicitly, in which case using the macro will only make something simple appear complicated (and also perform an unnecessary function call but the compiler probably inlines this kind of call anyway).

Therefore,  I think this should have `StarkFelt` hardcoded in the macro and moved into the `hash` module, at least until we find  another use case such as this.

* RE writing the types explicitly, I think this way might help readers believe in the macro without having to look up the implementation.

WDYT?



_Suggestion:_
```XML
impl_from_small_uints!(u8,u16,u32,u64);
```
___
*[`src/type_utils.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVh_Dk7DOTICLGHHq5j:-NVh_Dk7DOTICLGHHq5k:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a9326cb76de01d6b44184612ad3a1307c79cedab/src/type_utils.rs#L2)):*
> ```XML
> #[macro_export]
> macro_rules! impl_from_small_uints {
> ```





_Suggestion:_
```XML
 impl_from_for_small_uints 
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`src/hash.rs` line 158 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVhaj8C7ZVUPZV8EMc2:-NVhq0sB7Yl8y_bXfd-1:b-gdtnpa) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a9326cb76de01d6b44184612ad3a1307c79cedab/src/hash.rs#L158)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure about this one, but here's my rationale:

* Using this macro for `StarkFelt` makes sense, because writing each impl by hand will be subtly different, and the implementation is not totally trivial.
In other cases, when writing the `impl` is trivial for every type, it might be better just to write them out explicitly, in which case using the macro will only make something simple appear complicated (and also perform an unnecessary function call but the compiler probably inlines this kind of call anyway).

Therefore,  I think this should have `StarkFelt` hardcoded in the macro and moved into the `hash` module, at least until we find  another use case such as this.

* RE writing the types explicitly, I think this way might help readers believe in the macro without having to look up the implementation.

WDYT?
</blockquote></details>

My rationale was: we may want more intermediate converters in the future.
We have many number types (StarkFelt, STarkHash, StorageKey, PatriciaKey, Address, Nonce, BlockNumber...) and we may want to reuse this From<> generator.
So, I put it in it's own module, so we can expand in the future if we want without moving things around.
Maybe I should define the generic version:
```
#[macro_export]
macro_rules! impl_from_intermediate {
    ($struct_type:ty, $intermediate_type:ty, $($base_type:ty),+) => {
        $(
            impl From<$base_type> for $struct_type {
                fn from(x: $base_type) -> Self {
                    Self::from($intermediate_type::from(x))
                }
            }
        )+
    };
}
```
and use
```
impl_from_intermediate!(StarkFelt, u128, u8, u16, u32, u64);
```
?
___
*[`src/type_utils.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVh_Dk7DOTICLGHHq5j:-NVhr1Fo5--cuN8Lgw_q:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a9326cb76de01d6b44184612ad3a1307c79cedab/src/type_utils.rs#L2)):*
> ```XML
> #[macro_export]
> macro_rules! impl_from_small_uints {
> ```

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-:-NViN8l_8LV4jSLqksON:bnfp4nl)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dan-starkware, and @dorimedini-starkware)

___
*[`src/hash.rs` line 158 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-NVhaj8C7ZVUPZV8EMc2:-NViMxq63UwBRqZoMfPA:b-kksjnz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a9326cb76de01d6b44184612ad3a1307c79cedab/src/hash.rs#L158)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

My rationale was: we may want more intermediate converters in the future.
We have many number types (StarkFelt, STarkHash, StorageKey, PatriciaKey, Address, Nonce, BlockNumber...) and we may want to reuse this From<> generator.
So, I put it in it's own module, so we can expand in the future if we want without moving things around.
Maybe I should define the generic version:
```
#[macro_export]
macro_rules! impl_from_intermediate {
    ($struct_type:ty, $intermediate_type:ty, $($base_type:ty),+) => {
        $(
            impl From<$base_type> for $struct_type {
                fn from(x: $base_type) -> Self {
                    Self::from($intermediate_type::from(x))
                }
            }
        )+
    };
}
```
and use
```
impl_from_intermediate!(StarkFelt, u128, u8, u16, u32, u64);
```
?
</blockquote></details>

:lgtm: 
Just make sure to document it.

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/66#-:-NViTdPwEeUVJ12fgD-q:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @alonh5 and @dan-starkware)

**Pull request merged**
