### PR TITLE
Refactor(transaction): define a trait for transactions that includes …

### PR DESCRIPTION
**Pull request by MohammadNassar1**
…a method for calculating the transaction hash

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @MohammadNassar1)

___
*[`src/transaction_hash.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuJyC5m5KepgaxG0F3J:-NuJyC5m5KepgaxG0F3K:bsxypqu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L25)):*
> ```XML
> const L2_GAS: &ResourceName = b"\0L2_GAS";
> 
> static DECLARE: Lazy<StarkFelt> =
> ```

Consider keeping these as regular consts for simplicity.

**Review by giladchase — CHANGES_REQUESTED** [review]
Looking at this now, there appears to be a pattern I missed before:
All chain implementations have a common prefix
```rust
        HashChain::new()
        .chain(&<TX_NAME>)
        .chain(&transaction_version.0)
```
Then in each tx type there is one more common thing chained (depending on tx type), and after which the implementations diverge depending on the internal tx type version.

This suggests maybe having a common trait is too simplistic...
Perhaps it should be only Transaction that has the existing `calculate_transaction_hash` signature (without a trait), generate the common prefix above, and pass to internal calls the p hash chain prefix, where each levels expands it based on it's additional information.

Basically the idea is to remove all duplication from the hashchain as possible.

WDYT? not sure if this is better or not.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-:-NuNcXrj8rU55BHsb1YM:bwcsaj0)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/transaction_hash.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuNjXe_3-0DHbhsN1lz:-NuNjXe_3-0DHbhsN1m-:ba3dfna) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L1)):*
> ```XML
> use std::convert::TryFrom;
> ```

Remove?



_Code quote:_
```XML
use std::convert::TryFrom;
```
___
*[`src/transaction_hash.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuNiZNKE5SiS2nTQh_W:-NuNiZNKE5SiS2nTQh_X:b-15mn6u) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L35)):*
> ```XML
>     Lazy::new(|| ascii_as_felt("invoke").expect("ascii_as_felt failed for 'invoke'"));
> static L1_HANDLER: Lazy<StarkFelt> =
>     Lazy::new(|| ascii_as_felt("l1_handler").expect("ascii_as_felt failed for 'l1_handler'"));
> ```

These should be associated with the transaction objects somehow, to reduce coupling.

If we go with the suggestion I made in the previous comment about breaking up the chain, we can add a variant_name method on `Transaction` that matches and returns the literals.
If we don't break up the chain, we can create a simple trait in this module and implement it here for all inner-types.



_Code quote:_
```XML
static DECLARE: Lazy<StarkFelt> =
    Lazy::new(|| ascii_as_felt("declare").expect("ascii_as_felt failed for 'declare'"));
static DEPLOY: Lazy<StarkFelt> =
    Lazy::new(|| ascii_as_felt("deploy").expect("ascii_as_felt failed for 'deploy'"));
static DEPLOY_ACCOUNT: Lazy<StarkFelt> = Lazy::new(|| {
    ascii_as_felt("deploy_account").expect("ascii_as_felt failed for 'deploy_account'")
});
static INVOKE: Lazy<StarkFelt> =
    Lazy::new(|| ascii_as_felt("invoke").expect("ascii_as_felt failed for 'invoke'"));
static L1_HANDLER: Lazy<StarkFelt> =
    Lazy::new(|| ascii_as_felt("l1_handler").expect("ascii_as_felt failed for 'l1_handler'"));
```
___
*[`src/transaction_hash.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuNjg8BDuPYe3Btm6FD:-NuNjg8BDuPYe3Btm6FE:b7h6d0g) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L41)):*
> ```XML
> });
> 
> pub(crate) static ZERO: Lazy<StarkFelt> = Lazy::new(|| StarkFelt::ZERO);
> ```

Can we use StarkFelt::ZERO directly? 
It is a const, so performance-wise it'll actually be faster than using a Lazy static.



_Code quote:_
```XML
pub(crate) static ZERO: Lazy<StarkFelt> = Lazy::new(|| StarkFelt::ZERO);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[`src/transaction_hash.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuNjXe_3-0DHbhsN1lz:-NuTok-bDdYN63WBhIJj:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`src/transaction_hash.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuJyC5m5KepgaxG0F3J:-NuTyO7-6tXfsz9k7diQ:b-1dykry) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L25)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider keeping these as regular consts for simplicity.
</blockquote></details>

Note that `ascii_as_felt` cannot be called within a const expression.
___
*[`src/transaction_hash.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuNjg8BDuPYe3Btm6FD:-NuTpAn58kXpzqaT7Z-F:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L41)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can we use StarkFelt::ZERO directly? 
It is a const, so performance-wise it'll actually be faster than using a Lazy static.
</blockquote></details>

Done.

**Review by MohammadNassar1 — COMMENTED** [review]
Hmm, your suggestion would eliminate one argument and save the calculation of two chains. 
I'm not sure if avoiding duplication justifies modifying the trait, especially considering that the common calculation isn't overly complex or time-consuming.
WDYT?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-:-NuU3SBC6HenfXC8dOx_:blmhkok)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @giladchase and @yair-starkware)

**Comment by yair-starkware** [comment]
*[`src/transaction_hash.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuJyC5m5KepgaxG0F3J:-NuUA4CnEa9Ye06dHZ0J:bckz3hh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L25)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Note that `ascii_as_felt` cannot be called within a const expression.
</blockquote></details>

You can calc it one time and keep the result

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[`src/transaction_hash.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuJyC5m5KepgaxG0F3J:-NuYUk7RBTGQPyDBNPym:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L25)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can calc it one time and keep the result
</blockquote></details>

Done

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[`src/transaction_hash.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuJyC5m5KepgaxG0F3J:-Nuci0e37oJ-fwTtf5yg:b6k3cix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L25)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Reverted.
Cannot call non-const fn `try_from` in constants calls.

**Review by giladchase — APPROVED** [review]
Discussed offline: retracting my suggestion as sometimes we'll want to calculate hash on the internal struct.

:lgtm: 

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-:-NurNaX73P0puBOYVcsd:b3zj3qq)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 175 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuricxB7y4PAJ0nqiG-:-NuricxB7y4PAJ0nqiG0:b-danxt7) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fd1239a315c4ef7bd3c8b2d6c0eea580df99f6b9/src/transaction.rs#L175)):*
> ```XML
>         transaction_version: &TransactionVersion,
>     ) -> Result<TransactionHash, StarknetApiError> {
>         get_declare_transaction_v2_hash(self, chain_id, transaction_version)
> ```

Are these inner functions no longer necessary?
If so, were you planning on deleting them (and putting their contents here) afterwards?



_Code quote:_
```XML
get_declare_transaction_v2_hash
```
___
*[`src/transaction_hash.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuNiZNKE5SiS2nTQh_W:-NuriJjFD_NM16iI60zZ:broc0or) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

These should be associated with the transaction objects somehow, to reduce coupling.

If we go with the suggestion I made in the previous comment about breaking up the chain, we can add a variant_name method on `Transaction` that matches and returns the literals.
If we don't break up the chain, we can create a simple trait in this module and implement it here for all inner-types.
</blockquote></details>

Well the suggestion above flopped, but i still think this needs to be addressed, but I'll unblock and address it later.
Can you plz unblock and create a Monday task for this? Plz assign me to it.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/214)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`src/transaction.rs` line 175 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuricxB7y4PAJ0nqiG-:-Nurot7W2EDSQ-IhnIL4:b-mgrpi2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fd1239a315c4ef7bd3c8b2d6c0eea580df99f6b9/src/transaction.rs#L175)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Are these inner functions no longer necessary?
If so, were you planning on deleting them (and putting their contents here) afterwards?
</blockquote></details>

Note that I kept the `get_transaction_hash`function.
This function calls the inner function.
___
*[`src/transaction_hash.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/214#-NuNiZNKE5SiS2nTQh_W:-NuroqKB-If04YtV1Sge:b8j59da) ([raw file](https://github.com/starkware-libs/starknet-api/blob/70dc75189dc924835a218ec3bee51d34c9d83218/src/transaction_hash.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Well the suggestion above flopped, but i still think this needs to be addressed, but I'll unblock and address it later.
Can you plz unblock and create a Monday task for this? Plz assign me to it.
</blockquote></details>

Done
https://starkware.monday.com/boards/3670745608/pulses/6405685897

**Pull request merged**
