### PR TITLE
Add const constructor to `StarkFelt`

### PR DESCRIPTION
**Pull request by giladchase**
- Implement `from<128>` using const logic, so that it can be used as a const constructor.
- Also remove `StarkFelt::one()` which in favor of `StarkFelt::from_128(1_u128)`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-Nd_rHYaCxF2tytxt2hi:-Nd_rHYaCxF2tytxt2hj:b-n6jv1p) (no related file):*
why remove the `::one`?
can it be implemented in `const` way?
I don't like the hard-coded `1_u128`

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-Nd_rHYaCxF2tytxt2hi:-Ndc_Yq7-AI7YbppuzuS:bqra5oj) (no related file):*
Some context: Basically this whole thing is about creating `const` `StarkFelt` instances for small values, which wasn't possible because `StarkFelt::from` isn't a `const` function.
`::one` was added because we didn't have const constructor add someone wanted something equivalent to:
```rust
pub const BLOCK_HASH_TABLE_ADDRESS = StarkFelt(1); // note that it is hard coded here as well, but it's a constant.
```

Back to your questions now :) 
>why remove the `::one`?

We can leave it, it just became a special case of `from_128` now so I thought it might be unnecessary.

>can it be implemented in `const` way?

I don't quite follow, both `::one` and `from_128` are `const`s

>I don't like the hard-coded `1_u128`

Isn't it okay if it's a constant though?

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-Nd_rHYaCxF2tytxt2hi:-NddL3v2-tv6b-Kcar4A:b-828hg7) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Some context: Basically this whole thing is about creating `const` `StarkFelt` instances for small values, which wasn't possible because `StarkFelt::from` isn't a `const` function.
`::one` was added because we didn't have const constructor add someone wanted something equivalent to:
```rust
pub const BLOCK_HASH_TABLE_ADDRESS = StarkFelt(1); // note that it is hard coded here as well, but it's a constant.
```

Back to your questions now :) 
>why remove the `::one`?

We can leave it, it just became a special case of `from_128` now so I thought it might be unnecessary.

>can it be implemented in `const` way?

I don't quite follow, both `::one` and `from_128` are `const`s

>I don't like the hard-coded `1_u128`

Isn't it okay if it's a constant though?
</blockquote></details>

The reason I don't like the `1` is because, when you use numeric constants, it's not always clear if the value is arbitrary or not; `::one` is more explicit

___
___
*[`src/hash.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-NddL-Ox2qwLzjYJE_Uo:-NddL-Ox2qwLzjYJE_Up:b-ry0t8e) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2093bc18d35742306f0ed64d178cd57265b33f09/src/hash.rs#L67)):*
> ```XML
>             0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1,
>         ])
>     }
> ```

how bout this?



_Suggestion:_
```XML
    pub const fn one() -> Self {
        Self::from_u128(1_u128)
    }
```

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-Nd_rHYaCxF2tytxt2hi:-NddMrna0OMFvyAIWbzR:b-y8oxow) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

The reason I don't like the `1` is because, when you use numeric constants, it's not always clear if the value is arbitrary or not; `::one` is more explicit
</blockquote></details>

Fair enough, removed the deprecate TODO as well as putting back the `one`.

___
___
*[`src/hash.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-NddL-Ox2qwLzjYJE_Uo:-NddMU5C7vwb01xSNx5c:b-qz7bhu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2093bc18d35742306f0ed64d178cd57265b33f09/src/hash.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how bout this?
</blockquote></details>


Right again :)

**Review by yair-starkware — COMMENTED** [review]
What about the other types (TransactionHash, ContractAddress, TransactionVersion, etc.)? 
Can we do the same for them?
In our code we use a lot of lazy_static for this

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-:-NddUUBK2KveeeqMJade:b-f4jpps)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`src/hash.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-NddSjj5AeJ1GTiKwVy6:-NddSjj66eDa-oCw-Dtm:b-68lrti) ([raw file](https://github.com/starkware-libs/starknet-api/blob/78880924c27656aaea063f549fa38413d45152a9/src/hash.rs#L75)):*
> ```XML
>         }
>         Self(bytes)
>     }
> ```

Why is this code changed?
IIUC before it was 
```
        let mut bytes = [0u8; 32];
        bytes[16..32].copy_from_slice(&val.to_be_bytes());
        Self(bytes)
```

Also, why not
```
for index in 16..32
```



_Code quote:_
```XML
    pub const fn from_u128(val: u128) -> Self {
        let mut bytes = [0u8; 32];
        let val_bytes = val.to_be_bytes();
        let mut index = 16;
        while index < 32 {
            bytes[index] = val_bytes[index - 16];
            index += 1;
        }
        Self(bytes)
    }
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

**Review by giladchase — COMMENTED** [review]
For TransactionHash` and `TransactionVersion` it isn't strictly necessary, because now you can do:
```rust
pub const ZERO: TransactionVersion = TransactionVersion(StarkFelt::from_u128(0_u128));
```
So adding a const constructor for them would just be sugar.

For `ContractAddress` we might want to add one though (in a separate PR), because it'll require adding a const constructor for `PatriciaKey`.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-:-NdyJDnk5Zct26SnFcXW:bauki0w)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @yair-starkware)

___
*[`src/hash.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/128#-NddSjj5AeJ1GTiKwVy6:-NdycdjeEt-T7ADmL0oM:b-x8s35w) ([raw file](https://github.com/starkware-libs/starknet-api/blob/78880924c27656aaea063f549fa38413d45152a9/src/hash.rs#L75)):*
>Why is this code changed?

It's doing the same thing the const constructor does, only with non-const methods (like `copy_from_slice`), so this removed the duplication.
Also using the const implementation will be faster because it is computed at compile-time.

> Also, why not

`for` [isn't allowed](https://github.com/rust-lang/rust/issues/87575) in `const` functions. 
You can use control-flow in `const`, but only a very limited subset of them.

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by yair-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
