### PR TITLE
Add test utils with get_test_instance for BlockHeader

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/6)

### CODE REVIEW

**Comment by dan-starkware** [comment]
Please add a reviewer from the sequencer team.

**Comment by dan-starkware** [comment]
*[`src/test_utils.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJ50Kqf1xQEQUvGj5Im:-NJ50Kqf1xQEQUvGj5In:b-53ysoh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/dff401ef05bf56879e78b0ca51df60bc634616ac/src/test_utils.rs#L11)):*
> ```XML
> 
> auto_impl_get_test_instance! {
>     pub struct BlockHash(pub StarkHash);
> ```

Can we use non-testing derive on the original structs instead?

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/6)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJ50bCz9I9-oW4Hxqc0:-NJ54x2wECpBwx6hDonp:bb6un1j) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add a reviewer from the sequencer team. 
</blockquote></details>

Done

___
___
*[`src/test_utils.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJ50Kqf1xQEQUvGj5Im:-NJ64VeO7ghyJS0g96Wr:b-dtkds3) ([raw file](https://github.com/starkware-libs/starknet-api/blob/dff401ef05bf56879e78b0ca51df60bc634616ac/src/test_utils.rs#L11)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Can we use non-testing derive on the original structs instead? 
</blockquote></details>

Done, thanks!

**Comment by dan-starkware** [comment]
*[`src/core.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJAN0SUE5xvYKFg4vAZ:-NJAN0SUE5xvYKFg4vA_:b-agadoh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/007c3cb88512610f3953dfb8fa5460f10aea152f/src/core.rs#L27)):*
> ```XML
> }
> 
> /// The address of a [DeployedContract](`crate::state::DeployedContract`).
> ```

Not related to this PR, please add a CI job for cargo doc (and fix this one).



_Code quote:_
```XML
/// The address of a [DeployedContract](`crate::state::DeployedContract`).
```

**Comment by anatgstarkware** [comment]
*[`src/core.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJAN0SUE5xvYKFg4vAZ:-NJFJEqT8Yu1tW8gMtHW:b-occz08) ([raw file](https://github.com/starkware-libs/starknet-api/blob/007c3cb88512610f3953dfb8fa5460f10aea152f/src/core.rs#L27)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not related to this PR, please add a CI job for cargo doc (and fix this one).
</blockquote></details>

ptal https://reviewable.io/reviews/starkware-libs/starknet-api/8

**Review by giladchase — COMMENTED** [review]
I think if we're adding a second crate to the repo we should add it into a `./crates/` structure and move the rest of the files into it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-:-NJGHAgw4n0SylnlyheM:b-4qdhn8)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @elintul)

___
*[`get_test_instance_macro_derive/src/lib.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJGIhHH0Saqr2yji7oi:-NJGIhHH0Saqr2yji7oj:bvrijaq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b673838f3f3e8e4a00f995d6b2334f8508cfd2e4/get_test_instance_macro_derive/src/lib.rs#L6)):*
> ```XML
> 
> #[proc_macro_derive(GetTestInstance)]
> pub fn get_test_instance_macro_derive(input: TokenStream) -> TokenStream {
> ```

can you please document what this does and how it should be used?



_Code quote:_
```XML
#[proc_macro_derive(GetTestInstance)]
pub fn get_test_instance_macro_derive(input: TokenStream) -> TokenStream {
```

**Review by anatgstarkware — COMMENTED** [review]
What would you call the starknet_api crate? (this will impact all your imports)
or you can think of it as a "sub-crate" since this is just for macro purposes 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-:-NJGQ3iW3GBctKRIdQbC:blivw8l)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @elintul)

**Comment by anatgstarkware** [comment]
https://doc.rust-lang.org/book/ch19-06-macros.html
It suggests that the hello_macro_derive crate is inside the hello_macro crate (where the trait is defined)
Out trait (GetTestInstance) is defined in starknet_api::test_utils.

**Comment by anatgstarkware** [comment]
We can take the test_utils out to a separate crate, call it get_test_instance, and inside it put the macro crate, WDYT?
How about `objects` for the starknet_api crate? or `core`? or `defs`?

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/6)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @elintul)

___
*[`crates/objects/src/block.rs` line 27 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJZ9ONl7rW7ryCRGXO8:-NJZ9ONl7rW7ryCRGXO9:b-qkjpmt) ([raw file](https://github.com/starkware-libs/starknet-api/blob/62c0a5d25e8673fd2b6d3c4ee9a79d76971e1e03/crates/objects/src/block.rs#L27)):*
> ```XML
> #[derive(Debug, Default, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> #[cfg_attr(feature = "testing", derive(GetTestInstance))]
> pub struct BlockHeader {
> ```

Is it OK for a testing feature to leak into non-test code in this way?

I'm not sure.
On the one hand, it's conditionality compiled, so it's not really leaking out of the test context.
Therefore, it would be negligible if this only appeared once or twice in a central location (say in lib.rs).
However, IUUC, this attribute will appear quite often (roughly over every struct)?



_Code quote:_
```XML
#[cfg_attr(feature = "testing", derive(GetTestInstance))]
pub struct BlockHeader {
```
___
*[`crates/objects/src/block_test.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJZ4GKDCN-XXFM0YgFI:-NJZ4GKDCN-XXFM0YgFJ:brd76hf) ([raw file](https://github.com/starkware-libs/starknet-api/blob/62c0a5d25e8673fd2b6d3c4ee9a79d76971e1e03/crates/objects/src/block_test.rs#L12)):*
> ```XML
> use crate::hash::StarkHash;
> #[cfg(feature = "testing")]
> use crate::{patky, shash};
> ```

Would these #cfg boilerplate not be necessary once `auto_impl_get_test_instance!` is implemented?



_Code quote:_
```XML
#[cfg(feature = "testing")]
use get_test_instance::GetTestInstance;

use crate::block::BlockNumber;
#[cfg(feature = "testing")]
use crate::block::{BlockHash, BlockHeader, BlockTimestamp, GasPrice};
#[cfg(feature = "testing")]
use crate::core::{ContractAddress, GlobalRoot, PatriciaKey};
#[cfg(feature = "testing")]
use crate::hash::StarkHash;
#[cfg(feature = "testing")]
use crate::{patky, shash};
```

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/6)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @elintul, and @giladchase)

___
*[`crates/objects/src/block.rs` line 27 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJZ9ONl7rW7ryCRGXO8:-NJZ_ucv3RPqphfH9avL:b65g60k) ([raw file](https://github.com/starkware-libs/starknet-api/blob/62c0a5d25e8673fd2b6d3c4ee9a79d76971e1e03/crates/objects/src/block.rs#L27)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is it OK for a testing feature to leak into non-test code in this way?

I'm not sure.
On the one hand, it's conditionality compiled, so it's not really leaking out of the test context.
Therefore, it would be negligible if this only appeared once or twice in a central location (say in lib.rs).
However, IUUC, this attribute will appear quite often (roughly over every struct)?
</blockquote></details>

It should be derived for every struct
___
*[`crates/objects/src/block_test.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/6#-NJZ4GKDCN-XXFM0YgFI:-NJZ_VXjBQPFkg1dqgJL:bkq8m6x) ([raw file](https://github.com/starkware-libs/starknet-api/blob/62c0a5d25e8673fd2b6d3c4ee9a79d76971e1e03/crates/objects/src/block_test.rs#L12)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Would these #cfg boilerplate not be necessary once `auto_impl_get_test_instance!` is implemented?
</blockquote></details>

No, you would still need them here, because this is a test file that has one regular test and one test of a testing feature

**Comment by anatgstarkware** [comment]
No need for testing features in starknet_api for now

**Pull request closed without merging**
