### PR TITLE
feat(transaction): implement rpc transaction

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)

### CODE REVIEW

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`src/rpc_transaction.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoKdVf8fi4NTtNJB-x:-NwoKdVf8fi4NTtNJB-y:b9qg7ov) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L37)):*
> ```XML
> /// [`Starknet specs`]: https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json
> #[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
> #[serde(deny_unknown_fields)]
> ```

Is this necessary? it's not in ExternalTransaction
___
*[`src/rpc_transaction.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoKx3g-snhL5D3gJDJ:-NwoKx3g-snhL5D3gJDK:b-al217o) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L50)):*
> ```XML
> ///
> /// [`Starknet specs`]: https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json
> #[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
> ```

Where do you use `Hash`, `Ord` and `PartialOrd`? (also for the other tx type)
___
*[`src/rpc_transaction.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoLF-jERves0xHsqX5:-NwoLF-jERves0xHsqX6:b-vkp1ks) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L72)):*
> ```XML
> /// A declare transaction of a Cairo-v1 contract class that can be added to Starknet through the
> /// RPC.
> #[derive(Debug, Deserialize, Serialize, Clone, Eq, PartialEq)]
> ```

alphabetize 
___
*[`src/rpc_transaction.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoLili8mSpUS38FSqu:-NwoLili8mSpUS38FSqv:buyeeju) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L92)):*
> ```XML
> /// A deploy account transaction that can be added to Starknet through the RPC.
> #[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
> pub struct RPCDeployAccountTransactionV3 {
> ```

in ExternalTransaction there's `#[serde(deny_unknown_fields)]`. why not here?
same for `RPCInvokeTransactionV3`
___
*[`src/rpc_transaction.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoODnNCglL04n2QHXo:-NwoODnNCglL04n2QHXp:b7pt71z) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L123)):*
> ```XML
> #[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
> pub struct ContractClass {
>     pub sierra_program: Vec<StarkFelt>,
> ```

The code below is from ExternalTransaction. Why did you change it? Because of the spec? I see that this field used to be a String, and now it's a vector of StarkFelts.



_Code snippet:_
```XML
#[serde(rename = "sierra_program")]
 pub compressed_sierra_program: String,
```
___
*[`src/rpc_transaction.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoPjCtBa7tLoieKODj:-NwoPjCtBa7tLoieKODk:b6y0g1q) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L130)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> pub struct EntryPointByType {
> ```

Why did you decide to change `entry_points_by_type`, that was  `HashMap<EntryPointType, Vec<EntryPoint>>` (`EntryPointType` as an enum) to a struct?

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-:-Nx7s7np7QJrTwUkNIV3:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)

___
*[`src/rpc_transaction.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-Nx7qMCM8rJPP_OzcnvD:-Nx7qMCNESGmtLed6-5n:be5ck22) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L35)):*
> ```XML
> /// either a contract class or a class hash).
> ///
> /// [`Starknet specs`]: https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json
> ```

:star_struck: 



_Code quote:_
```XML
/// [`Starknet specs`]: https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json
```
___
*[`src/rpc_transaction.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoPjCtBa7tLoieKODj:-Nx7rF5u3zETQd7BAegi:bfdhnet) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L130)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Why did you decide to change `entry_points_by_type`, that was  `HashMap<EntryPointType, Vec<EntryPoint>>` (`EntryPointType` as an enum) to a struct?
</blockquote></details>

In general, if you have a hash with fixed fields it should be a struct, it is better:

a) you get a compile-time check that all keys you want exist for free
b) easier to access the values, rather than having to do a `get(thing).unwrap()` or something like that
c) faster access, more optimized

probably other that I forgot.
But basically hashmaps are largly for dynamic content, not fixed.
___
*[`src/rpc_transaction_test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-Nx7s200ETa1qeWi4BN_:-Nx7s200ETa1qeWi4BNa:b-wypa73) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction_test.rs#L1)):*
> ```XML
> use std::sync::Arc;
> ```

no logic changes  right? just move/rename?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`src/rpc_transaction.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-Nx7qMCM8rJPP_OzcnvD:-Nyp3Zwp2ARm-ImuniPi:b32vhw) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L35)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

:star_struck:
</blockquote></details>

:)
___
*[`src/rpc_transaction.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoKdVf8fi4NTtNJB-x:-Nyp9o0ACCCJACzqZAEn:b-9acxom) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L37)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is this necessary? it's not in ExternalTransaction
</blockquote></details>

Moved to `ExternalTransaction`
___
*[`src/rpc_transaction.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoKx3g-snhL5D3gJDJ:-Nyp9tgE1hMyT2FKC0E1:bqaig31) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L50)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Where do you use `Hash`, `Ord` and `PartialOrd`? (also for the other tx type)
</blockquote></details>

Note that this struct should be shared among other crates.
So, I prefer to keep additional traits that can be useful for others.
___
*[`src/rpc_transaction.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoLF-jERves0xHsqX5:-NypAcBe3ucZMKBo7iQL:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L72)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

alphabetize
</blockquote></details>

Done.
___
*[`src/rpc_transaction.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoLili8mSpUS38FSqu:-Nyp8I0L8Ps_pvPjAeEH:bb4bnnl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L92)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

in ExternalTransaction there's `#[serde(deny_unknown_fields)]`. why not here?
same for `RPCInvokeTransactionV3`
</blockquote></details>

Good point.
I think it should be added for `ExternalTransaction` struct.
As the deserialization is done over ExernalTransaction struct.
___
*[`src/rpc_transaction.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NwoODnNCglL04n2QHXo:-Nyp8rxa9xg4lmBVhpIg:b-mvzaal) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction.rs#L123)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

The code below is from ExternalTransaction. Why did you change it? Because of the spec? I see that this field used to be a String, and now it's a vector of StarkFelts.
</blockquote></details>

Correct, changed to be aligned with the spec.
___
*[`src/rpc_transaction_test.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-Nx7s200ETa1qeWi4BN_:-Nyp3F2s35ua4A5wbmU7:b-jp377f) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a327a51d9769a484838067498c081369e9d3814e/src/rpc_transaction_test.rs#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

no logic changes  right? just move/rename?
</blockquote></details>

correct

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NypAeMS7I8bQH6SsRAj:-NypAeMS7I8bQH6SsRAk:brmfov1) (no related file):*
In this PR, I changed the struct fields to be aligned with the spec.
Next PR, rename to `RPCTransaction`.

___

**Review by giladchase — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`src/external_transaction.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytpuS39L7u_EPgcTG_:-NytpuS39L7u_EPgcTGa:b9anqvr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/463e1c03cdc0a3f845172b06f636c449c7813d2f/src/external_transaction.rs#L28)):*
> ```XML
>     DeployAccount(ExternalDeployAccountTransaction),
>     /// An invoke transaction.
>     #[serde(rename = "INVOKE_FUNCTION")]
> ```

why did you remove it?



_Code quote:_
```XML
_FUNCTION
```
___
*[`src/external_transaction_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytrCtM-WSFBgMKlTHX:-NytrCtM-WSFBgMKlTHY:bkuqonq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/463e1c03cdc0a3f845172b06f636c449c7813d2f/src/external_transaction_test.rs#L21)):*
> ```XML
> fn create_resource_bounds() -> ResourceBoundsMapping {
>     let mut map = BTreeMap::new();
>     map.insert(Resource::L1Gas, ResourceBounds { max_amount: 100, max_price_per_unit: 12 });
> ```

What are these values? I see you use default values now.
___
*[`src/executable_transaction.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytrYx_C6Q9QDJXOfP1:-NytrYx_C6Q9QDJXOfP2:bb7r2f0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a22c54457bdf8a02276bb0b00c3218e363e5afe0/src/executable_transaction.rs#L4)):*
> ```XML
> use crate::state::ContractClass;
> use crate::transaction::TransactionHash;
> ```

why?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`src/external_transaction.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytpuS39L7u_EPgcTG_:-NyxnJzy0PQGuFfD0qE5:bexp7ua) ([raw file](https://github.com/starkware-libs/starknet-api/blob/463e1c03cdc0a3f845172b06f636c449c7813d2f/src/external_transaction.rs#L28)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why did you remove it?
</blockquote></details>

See [here](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L2699C36-L2699C45)
___
*[`src/external_transaction_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytrCtM-WSFBgMKlTHX:-Nyy2Pg0CmsWEHK1zRKy:bnklmlp) ([raw file](https://github.com/starkware-libs/starknet-api/blob/463e1c03cdc0a3f845172b06f636c449c7813d2f/src/external_transaction_test.rs#L21)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

What are these values? I see you use default values now.
</blockquote></details>

I've added a new function that generates non-default values.
___
*[`src/executable_transaction.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytrYx_C6Q9QDJXOfP1:-Nyy2BN30GAtk48CX3zr:bfpf9vr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a22c54457bdf8a02276bb0b00c3218e363e5afe0/src/executable_transaction.rs#L4)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

why?
</blockquote></details>

This file wasn't changed.
It's not related to the external tx.

**Review by ayeletstarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`src/external_transaction_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytrCtM-WSFBgMKlTHX:-Nyy7LQS30B7ezURPYG1:b-oeka74) ([raw file](https://github.com/starkware-libs/starknet-api/blob/463e1c03cdc0a3f845172b06f636c449c7813d2f/src/external_transaction_test.rs#L21)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I've added a new function that generates non-default values.
</blockquote></details>

Add a comment explaining that these are non-default values because they're random and seem to mean something.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @ayeletstarkware)

___
*[`src/external_transaction_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NytrCtM-WSFBgMKlTHX:-NyyhumX6A9NhoSOyQOO:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/463e1c03cdc0a3f845172b06f636c449c7813d2f/src/external_transaction_test.rs#L21)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Add a comment explaining that these are non-default values because they're random and seem to mean something.
</blockquote></details>

Done.

**Review by ayeletstarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ayeletstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-:-NyyiW_u2T1Me5QJY-pM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

___
*[`src/external_transaction.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NyypK4kBKd3qJwuwWD_:-NyyuHqSEqwQD06uoxxR:b-aipdr5) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8317046e17157af7958fb213bb8e5f3d1618f0d9/src/external_transaction.rs#L122)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Can we be aligned with the class `ContractClass` used in the compilers repo?
</blockquote></details>

Discussed F2F. This is complicated.

**Comment by ArniStarkware** [comment]
*[`src/external_transaction.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NyypK4kBKd3qJwuwWD_:-Nz33qXSC9kPYxg5wzrO:b-nzxyup) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8317046e17157af7958fb213bb8e5f3d1618f0d9/src/external_transaction.rs#L122)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Discussed F2F. This is complicated.
</blockquote></details>

Wait - we talked F2f about how this member needs to be consistent with the RPC.
(look for the line: `The list of Sierra instructions of which the program consists` in [here](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json)
 But we just changed this value (to fit this better, I admit). Who is in charge of the RPC? Are we sure they are using the same values for external transactions? Can the external transaction use a different ContractClass struct than the one Papyrus is using?

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @ayeletstarkware, and @giladchase)

___
*[`src/external_transaction.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NyypK4kBKd3qJwuwWD_:-Nz39XAv-ONZdPZXZ78Z:b6sg7q8) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8317046e17157af7958fb213bb8e5f3d1618f0d9/src/external_transaction.rs#L122)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Wait - we talked F2f about how this member needs to be consistent with the RPC.
(look for the line: `The list of Sierra instructions of which the program consists` in [here](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json)
 But we just changed this value (to fit this better, I admit). Who is in charge of the RPC? Are we sure they are using the same values for external transactions? Can the external transaction use a different ContractClass struct than the one Papyrus is using?
</blockquote></details>

Why do you think we use a different value?
What do you mean by external transaction?  the one that is different than RPC.

I think Ariel is in charged of this spec.

**Review by ArniStarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-:-Nz3OdGuEeUoZcDAHuiZ:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

___
*[`src/external_transaction.rs` line 122 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/236#-NyypK4kBKd3qJwuwWD_:-Nz3OZ4CBLMNrjrBJjX-:bb70hji) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8317046e17157af7958fb213bb8e5f3d1618f0d9/src/external_transaction.rs#L122)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why do you think we use a different value?
What do you mean by external transaction?  the one that is different than RPC.

I think Ariel is in charged of this spec.
</blockquote></details>

NVM.

**Review by ArniStarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/236)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
