### PR TITLE
refactor: move transaction hash calculation to sn api

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204)

### CODE REVIEW

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`src/transaction_hash.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-Ntyv1I47BeYORO8NEXw:-Ntyv1I47BeYORO8NEXx:b-dz5etb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1d65e668ad318daeea2ef25c1dcf9970891faa9a/src/transaction_hash.rs#L44)):*
> ```XML
>     static ref ONE: StarkFelt = StarkFelt::from(1_u8);
>     static ref TWO: StarkFelt = StarkFelt::from(2_u8);
>     static ref THREE: StarkFelt = StarkFelt::from(3_u8);
> ```

You can use StarkFelt::ZERO etc.



_Code quote:_
```XML
    pub(crate) static ref ZERO: StarkFelt = StarkFelt::from(0_u8);
    static ref ONE: StarkFelt = StarkFelt::from(1_u8);
    static ref TWO: StarkFelt = StarkFelt::from(2_u8);
    static ref THREE: StarkFelt = StarkFelt::from(3_u8);
```
___
*[`src/transaction_hash.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-NtyvCyO3jgE6d8PK-HX:-NtyvCyO3jgE6d8PK-HY:b-hgjj7i) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1d65e668ad318daeea2ef25c1dcf9970891faa9a/src/transaction_hash.rs#L48)):*
> ```XML
> 
> /// Calculates hash of a Starknet transaction.
> pub fn get_transaction_hash(
> ```

Consider implementing as methods (can be in a separate PR)
___
*[`src/transaction_hash.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-NtywD6P657YF8h06uPD:-NtywD6P657YF8h06uPE:b-65d6mx) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1d65e668ad318daeea2ef25c1dcf9970891faa9a/src/transaction_hash.rs#L216)):*
> ```XML
>         poseidon_hash_many(&self.elements).into()
>     }
> }
> ```

Consider moving to the crypto module



_Code quote:_
```XML
// Collect elements for applying hash chain.
pub(crate) struct HashChain {
    elements: Vec<FieldElement>,
}

impl HashChain {
    pub fn new() -> HashChain {
        HashChain { elements: Vec::new() }
    }

    // Chains a felt to the hash chain.
    pub fn chain(mut self, felt: &StarkFelt) -> Self {
        self.elements.push(FieldElement::from(*felt));
        self
    }

    // Chains the result of a function to the hash chain.
    pub fn chain_if_fn<F: Fn() -> Option<StarkFelt>>(self, f: F) -> Self {
        match f() {
            Some(felt) => self.chain(&felt),
            None => self,
        }
    }

    // Chains many felts to the hash chain.
    pub fn chain_iter<'a>(self, felts: impl Iterator<Item = &'a StarkFelt>) -> Self {
        felts.fold(self, |current, felt| current.chain(felt))
    }

    // Returns the pedersen hash of the chained felts, hashed with the length of the chain.
    pub fn get_pedersen_hash(&self) -> StarkHash {
        let current_hash = self
            .elements
            .iter()
            .fold(FieldElement::ZERO, |current_hash, felt| pedersen_hash(&current_hash, felt));
        let n_elements = FieldElement::from(self.elements.len());
        pedersen_hash(&current_hash, &n_elements).into()
    }

    // Returns the poseidon hash of the chained felts.
    pub fn get_poseidon_hash(&self) -> StarkHash {
        poseidon_hash_many(&self.elements).into()
    }
}
```

**Review by giladchase — COMMENTED** [review]
@MohammadNassar1,

To clarify, this PR is only extracting code from papyrus into SNAPI, without any logic changes, with a refactor to follow, correct? 

Should we wait to review until after the refactor, or would you like initial, non-blocking feedback now, with the understanding that fixes are for subsequent PRs?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-:-Nu2MMMn3aGLC4PCDOGh:bl18zk2)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
Yes, this PR is without any changes.
The next PR is for refactoring. I haven't opened it yet.
Please review it, so we can merge it and use transaction hash calculation in mempool.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-:-Nu3QmH7E_Qri0MfoFa8:b-pj6bfh)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @giladchase and @yair-starkware)

___
*[`src/transaction_hash.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-Ntyv1I47BeYORO8NEXw:-Nu44RGm7jRmm-DAJHC0:b-803vfl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1d65e668ad318daeea2ef25c1dcf9970891faa9a/src/transaction_hash.rs#L44)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can use StarkFelt::ZERO etc.
</blockquote></details>

Will be done in the next PR.
___
*[`src/transaction_hash.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-NtyvCyO3jgE6d8PK-HX:-Nu44Tx95na45fZ1XbNa:b-803vfl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1d65e668ad318daeea2ef25c1dcf9970891faa9a/src/transaction_hash.rs#L48)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider implementing as methods (can be in a separate PR)
</blockquote></details>

Will be done in the next PR.

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-:-NuJvZWCE1hgtofFKjtb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204#-:-Nu3gn7d5T3Eyx0W_ECG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
