### PR TITLE
Use xJonathanLEI/starknet-rs to compute stark hash

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/5)

### CODE REVIEW

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/5)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @anatgstarkware, @elintul, and @giladchase)

___
*[`Cargo.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJ4NA7g4sNNUwhE2Lev:-NJ4NA7g4sNNUwhE2Lew:b-b96w0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/33cbe9c67895a71af7c37332b2008a466262bc54/Cargo.toml#L14)):*
> ```TOML
> serde = { version = "1.0.130", features = ["derive"] }
> serde_json = { version = "1.0.81" }
> starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
> ```

Consider using a specific commit/release 
___
*[`src/hash.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJ4NoCC1T45oDim_gtp:-NJ4NoCC1T45oDim_gtq:b-o444j9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/33cbe9c67895a71af7c37332b2008a466262bc54/src/hash.rs#L24)):*
> ```XML
> const CHOOSER_HALF: u8 = 14;
> 
> /// Computes Pedersen hash using STARK curve on two elements, as defined
> ```

Consider moving below StarkHash definition
___
*[`src/hash.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJ4NO2L1BHSgEPZLq_N:-NJ4NO2L1BHSgEPZLq_O:b-refjk0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/33cbe9c67895a71af7c37332b2008a466262bc54/src/hash.rs#L26)):*
> ```XML
> /// Computes Pedersen hash using STARK curve on two elements, as defined
> /// in https://docs.starknet.io/documentation/architecture_and_concepts/Hashing/hash-functions/#pedersen_hash.
> pub fn compute_hash(felt0: &StarkFelt, felt1: &StarkFelt) -> Result<StarkHash, StarknetApiError> {
> ```

Consider renaming to `pedersen_hash` (import with a different name)



_Code quote:_
```XML
compute_hash
```
___
*[`src/hash_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJ4O1nUCuqyhslDAZrk:-NJ4O1nUCuqyhslDAZrl:b61yq4r) ([raw file](https://github.com/starkware-libs/starknet-api/blob/33cbe9c67895a71af7c37332b2008a466262bc54/src/hash_test.rs#L5)):*
> ```XML
> 
> #[test]
> fn compute_hash_correctness() {
> ```

Please add a test to array hashing as well.

**Comment by dan-starkware** [comment]
*[`src/hash_test.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJ9iT843kFGB1y_xu7i:-NJ9iT843kFGB1y_xu7j:b2v2lpf) ([raw file](https://github.com/starkware-libs/starknet-api/blob/87d940f14d78cb435f3bee7178c9f7d1a629c5a5/src/hash_test.rs#L15)):*
> ```XML
> #[test]
> fn pedersen_array_hash_correctness() {
>     // Test vectors from https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/crypto.rs
> ```

Please verify with [cairo-lang](https://github.com/starkware-libs/cairo-lang) implementation. 



_Code quote (from src/hash.rs):_
```XML
https://docs.starknet.io/documentation/architecture_and_concepts/Hashing/hash-functions/#array_hashing
```

**Comment by dan-starkware** [comment]
*[`src/hash_test.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJ9iT843kFGB1y_xu7i:-NJ9jEAODobZzpDcRjq3:bllgnm) ([raw file](https://github.com/starkware-libs/starknet-api/blob/87d940f14d78cb435f3bee7178c9f7d1a629c5a5/src/hash_test.rs#L15)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please verify with [cairo-lang](https://github.com/starkware-libs/cairo-lang) implementation. 
</blockquote></details>

https://github.com/starkware-libs/cairo-lang/blob/167b28bcd940fd25ea3816204fa882a0b0a49603/src/starkware/cairo/common/hash_state.py

**Comment by anatgstarkware** [comment]
*[`src/hash_test.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJ9iT843kFGB1y_xu7i:-NJB8Xsi57hh_EdF13PS:b-kvu2kl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/87d940f14d78cb435f3bee7178c9f7d1a629c5a5/src/hash_test.rs#L15)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

https://github.com/starkware-libs/cairo-lang/blob/167b28bcd940fd25ea3816204fa882a0b0a49603/src/starkware/cairo/common/hash_state.py
</blockquote></details>

Changed the test to be the same as the test in https://github.dev/starkware-industries/starkware/src/starkware/cairo/common/hash_state_test.py

**Comment by anatgstarkware** [comment]
*[`src/hash.rs` line 161 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJFLvNoDRvlexJ6ODSd:-NJFP3CuE491lyrfQNv0:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ee7813d0cb84d398f2034130d4697809a1dce360/src/hash.rs#L161)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why not through new?
</blockquote></details>

Done

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/5)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @elintul)

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-:-NJfsQLo1sLCL6-_0ikh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/5)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @dan-starkware, @elintul, and @giladchase)

___
*[`src/hash.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJo5WBKCMRIKAf77qWR:-NJo5WBKCMRIKAf77qWS:b9e4it4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/387cfebea15fe1e58b08a9a0c7dd7ee11bc65133/src/hash.rs#L40)):*
> ```XML
> pub fn pedersen_hash_array(felts: &[StarkFelt]) -> StarkHash {
>     let mut current_hash = StarkFelt::from(0);
>     for felt in felts.iter() {
> ```

Consider using the `fold()` method.

**Comment by anatgstarkware** [comment]
*[`src/hash.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/5#-NJo5WBKCMRIKAf77qWR:-NJo6wsO57G4hn3aXDkW:b-iry7x8) ([raw file](https://github.com/starkware-libs/starknet-api/blob/387cfebea15fe1e58b08a9a0c7dd7ee11bc65133/src/hash.rs#L40)):*
<details><summary><i>Previously, noaov1 wrote…</i></summary><blockquote>

Consider using the `fold()` method.
</blockquote></details>

Done, thanks

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/5)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @dan-starkware, @elintul, and @giladchase)

**Pull request merged**
