### PR TITLE
Add DeclareTransactionV3.

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvMybO-UwW17sVG4EH:-NcvMybO-UwW17sVG4EI:b-t4bab5) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L100)):*
> ```XML
>     pub resource_bounds: ResourceBounds,
>     pub sender_address: ContractAddress,
>     pub tip: Tip,
> ```

For consistency with the previous versions.



_Suggestion:_
```XML
    pub resource_bounds: ResourceBounds,
    pub tip: Tip,
    pub signature: TransactionSignature,
    pub nonce: Nonce,
    pub class_hash: ClassHash,
    pub compiled_class_hash: CompiledClassHash,
    pub sender_address: ContractAddress,
    pub nonce_data_availability_mode: DataAvailabilityMode,
    pub fee_data_availability_mode: DataAvailabilityMode,
```
___
*[`src/transaction.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNZE6-dUxVJi9w21B:-NcvNZE6-dUxVJi9w21C:bf3nhnw) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L139)):*
> ```XML
>             Self::V3(tx) => Some(tx.compiled_class_hash),
>         }
>     }
> ```

Not sure this is needed.



_Code quote:_
```XML
    pub fn compiled_class_hash(&self) -> Option<CompiledClassHash> {
        match self {
            Self::V0(_) => None,
            Self::V1(_) => None,
            Self::V2(tx) => Some(tx.compiled_class_hash),
            Self::V3(tx) => Some(tx.compiled_class_hash),
        }
    }
```
___
*[`src/transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNPJbBcVzxg_mQMwb:-NcvNPJbBcVzxg_mQMwc:b-qtt68p) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L148)):*
> ```XML
>             Self::V3(_) => None,
>         }
>     }
> ```

I think we should implement this in Blockifier.



_Code quote:_
```XML
    pub fn max_fee(&self) -> Option<Fee> {
        match self {
            Self::V0(tx) => Some(tx.max_fee),
            Self::V1(tx) => Some(tx.max_fee),
            Self::V2(tx) => Some(tx.max_fee),
            Self::V3(_) => None,
        }
    }
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`src/transaction.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvMybO-UwW17sVG4EH:-Ncvh8VjBvoT8Duca4-J:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L100)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

For consistency with the previous versions.
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNZE6-dUxVJi9w21B:-NcwOTr4BE0zaDUnBpHk:bwugsb2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L139)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure this is needed.
</blockquote></details>

IIUC, we can't do something like:
```
let tx = DeclareTransactionV2 {...};
let t = DeclareTransaction::V2(tx);
let h = t.compiled_class_hash
```
Since `t` is of type `DeclareTransaction`, which is an enum and not a struct, thus doesn’t have any fields.
We must use the `match` block to get the fields, and then we can use the getter `pub fn compiled_class_hash`:
```
let h = t.compiled_class_hash()
```
___
*[`src/transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNPJbBcVzxg_mQMwb:-NcwQC9z4FasNydqGOP9:b2kywuh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we should implement this in Blockifier.
</blockquote></details>

I see that the convention is to complement the "getters" in this file.
If you want me to move this specific or all of them LMK (: your call.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNZE6-dUxVJi9w21B:-NcwSEeMA5oKKaYKN87j:bar9nye) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L139)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

IIUC, we can't do something like:
```
let tx = DeclareTransactionV2 {...};
let t = DeclareTransaction::V2(tx);
let h = t.compiled_class_hash
```
Since `t` is of type `DeclareTransaction`, which is an enum and not a struct, thus doesn’t have any fields.
We must use the `match` block to get the fields, and then we can use the getter `pub fn compiled_class_hash`:
```
let h = t.compiled_class_hash()
```
</blockquote></details>

I'm not sure it's used though, PTAL at the Blockifier.
___
*[`src/transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNPJbBcVzxg_mQMwb:-NcwS4Z-DS41WEoavZ5H:bhzfn7a) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L148)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I see that the convention is to complement the "getters" in this file.
If you want me to move this specific or all of them LMK (: your call.
</blockquote></details>

But it's different for V3... and it makes it `Option<Fee>`. Please see where we use this getter to decide.

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`src/transaction.rs` line 139 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNZE6-dUxVJi9w21B:-Nd-Fxow7163SrQg0fnV:b-eazmz3) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L139)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm not sure it's used though, PTAL at the Blockifier.
</blockquote></details>

Done.
Removed.
___
*[`src/transaction.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NcvNPJbBcVzxg_mQMwb:-Nd-FzFC6kvSoWSKxDy9:b-eazmz3) ([raw file](https://github.com/starkware-libs/starknet-api/blob/289c58ec342e074d5dce6938e9823e77fa0c58ba/src/transaction.rs#L148)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

But it's different for V3... and it makes it `Option<Fee>`. Please see where we use this getter to decide.
</blockquote></details>

Done.
Removed.

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-:-Nd-KyR60i7CuIVrNNEc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-Nd-KzxoCx9tP_3Ua81F:-Nd-KzxoCx9tP_3Ua81G:bno2j0r) (no related file):*
Blocking until we're ready to begin the upgrade process. 

___

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

___
*[`src/transaction.rs` line 92 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NdxQQf52zePlgCiCEPt:-NdxQQf52zePlgCiCEPu:b5o3598) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cfdad352ceaf8cfa291299fe0d41bc1b87c0c7b0/src/transaction.rs#L92)):*
> ```XML
> #[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
> pub struct DeclareTransactionV3 {
>     pub resource: Resource,
> ```

What's `resource`? We only need the bounds map.

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @elintul, and @MohammadNassar1)

___
*[`src/transaction.rs` line 92 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NdxQQf52zePlgCiCEPt:-NdyhRiHCl617O6UmqDc:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cfdad352ceaf8cfa291299fe0d41bc1b87c0c7b0/src/transaction.rs#L92)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What's `resource`? We only need the bounds map.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

___
*[`src/transaction.rs` line 102 at r8](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NdyvM8D-hgtpa2Ay3dz:-NdyvM8E7p-aaMdDHCt6:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1f8666747ce74fda25d62677a088dcb0f9aeb9ee/src/transaction.rs#L102)):*
> ```XML
>     pub fee_data_availability_mode: DataAvailabilityMode,
>     pub paymaster_address: PaymasterAddress,
>     pub account_deployment_code: AccountDeploymentData,
> ```





_Suggestion:_
```XML
data
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @elintul, and @MohammadNassar1)

___
*[`src/transaction.rs` line 102 at r8](https://reviewable.io/reviews/starkware-libs/starknet-api/125#-NdyvM8D-hgtpa2Ay3dz:-Ndz6U-40Wwp1ODDLRP5:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1f8666747ce74fda25d62677a088dcb0f9aeb9ee/src/transaction.rs#L102)):*
> ```XML
>     pub fee_data_availability_mode: DataAvailabilityMode,
>     pub paymaster_address: PaymasterAddress,
>     pub account_deployment_code: AccountDeploymentData,
> ```

Done.

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

**Review by elintul — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/125)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

**Comment by barak-b-starkware** [comment]
Merged in [this](https://github.com/starkware-libs/starknet-api/pull/135) PR.

**Pull request closed without merging**
