### PR TITLE
feat!: use poseidon hash in patricia hash tree

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, and @Yoni-Starkware)

___
*[`src/crypto/patricia_hash.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxBle779xvMlK7urm23:-NxBle78403q2lHcLKLE:b-ceqliq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8a486e832a90cb0265285dd73470b82036c49903/src/crypto/patricia_hash.rs#L93)):*
> ```XML
>     let child_hash =
>         get_hash(SubTree { leaves: sub_tree.leaves, height: sub_tree.height + n_zeros });
>     let child_and_path_hash = poseidon_hash(&child_hash, &StarkFelt::ZERO);
> ```

This is a breaking change, is no one using this functionality?



_Code quote:_
```XML
poseidon_has
```
___
*[`src/crypto/patricia_hash.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxBln_T6yDONfM4aasL:-NxBln_T6yDONfM4aasM:bb7od0r) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8a486e832a90cb0265285dd73470b82036c49903/src/crypto/patricia_hash.rs#L108)):*
> ```XML
>         height: sub_tree.height + 1,
>     });
>     poseidon_hash(&zero_hash, &one_hash).0
> ```

same



_Code quote:_
```XML
poseidon_has
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama, @yair-starkware, and @Yoni-Starkware)

___
*[`src/crypto/patricia_hash.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxBle779xvMlK7urm23:-NxBtj0B7O3tU9bvv6QV:b-9uoh7o) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8a486e832a90cb0265285dd73470b82036c49903/src/crypto/patricia_hash.rs#L93)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This is a breaking change, is no one using this functionality?
</blockquote></details>

Context: In the previous PR (207), we copied the Patricia hash from Papyrus. Here, we change the hash function.
No one uses the functionality in this repo.
___
*[`src/crypto/patricia_hash.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxBln_T6yDONfM4aasL:-NxBti9206fmURx4_5_8:bb73xfv) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8a486e832a90cb0265285dd73470b82036c49903/src/crypto/patricia_hash.rs#L108)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

Same

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama, @yair-starkware, and @Yoni-Starkware)

___
*[`src/crypto/patricia_hash.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxBle779xvMlK7urm23:-NxC7zbj7lG3cbzwwBXF:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8a486e832a90cb0265285dd73470b82036c49903/src/crypto/patricia_hash.rs#L93)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Context: In the previous PR (207), we copied the Patricia hash from Papyrus. Here, we change the hash function.
No one uses the functionality in this repo.
</blockquote></details>

Done.
___
*[`src/crypto/patricia_hash.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxBln_T6yDONfM4aasL:-NxC7zv-5uo_juGclLHE:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8a486e832a90cb0265285dd73470b82036c49903/src/crypto/patricia_hash.rs#L108)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 2 unresolved discussions (waiting on @ShahakShama, @yoavGrs, and @Yoni-Starkware)

___
*[`src/crypto/patricia_hash.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxBle779xvMlK7urm23:-NxCCvfs4QDxs7qYwvaU:b-ncj2jt) ([raw file](https://github.com/starkware-libs/starknet-api/blob/8a486e832a90cb0265285dd73470b82036c49903/src/crypto/patricia_hash.rs#L93)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't it be generic on the hash function?

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @ShahakShama, @yoavGrs, and @Yoni-Starkware)

___
*[`src/hash.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCg4vtEAuYrZawKUPe:-NxCg4vtEAuYrZawKUPf:b-5o89po) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/hash.rs#L80)):*
> ```XML
> 
> impl HashFunction for PoseidonHashCalculator {
>     fn hash_pair(&self, felt0: &StarkFelt, felt1: &StarkFelt) -> StarkHash {
> ```

Why do we need a separate function for pair?
___
*[`src/crypto/patricia_hash.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCfyfn0R-3l1QuUZCy:-NxCfyfn0R-3l1QuUZCz:bph3ezq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/crypto/patricia_hash.rs#L77)):*
> ```XML
> // a continuous range, and hence the case of '1's in the longest common prefix is impossible.
> // - Binary: Some keys start with '0' bit and some start with '1' bit.
> fn get_hash(sub_tree: SubTree<'_>, hash_function: &impl HashFunction) -> StarkFelt {
> ```

I think using Fn trait is cleaner, see: https://doc.rust-lang.org/std/ops/trait.Fn.html#:~:text=This%20trait%20(%20Fn%20)%20is%20not,their%20documentation%20for%20more%20details). 



_Code quote:_
```XML
hash_function: &impl HashFunction
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama, @yair-starkware, @yoavGrs, and @Yoni-Starkware)

___
*[`src/hash.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCg4vtEAuYrZawKUPe:-NxCgwny3t4OjEeNP13p:b-3o7j2p) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/hash.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need a separate function for pair?
</blockquote></details>

hash_array hashes the length as well IIRC
___
*[`src/hash.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCh-TQ74tb-tzWOhe-:-NxCh-TQ74tb-tzWOhe0:b-k18nyy) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/hash.rs#L87)):*
> ```XML
>         poseidon_hash_array(stark_felts).0
>     }
> }
> ```

if going with the generic type method (see below)



_Suggestion:_
```XML
/// An interface for hash function calculations.
pub trait HashFunction {
    /// Computes hash of two Felts.
    fn hash_pair(felt0: &StarkFelt, felt1: &StarkFelt) -> StarkHash;
    /// Computes hash of array of Felts.
    fn hash_array(stark_felts: &[StarkFelt]) -> StarkHash;
}

pub struct PoseidonHashCalculator;

impl HashFunction for PoseidonHashCalculator {
    fn hash_pair(felt0: &StarkFelt, felt1: &StarkFelt) -> StarkHash {
        poseidon_hash(felt0, felt1).0
    }

    fn hash_array(&self, stark_felts: &[StarkFelt]) -> StarkHash {
        poseidon_hash_array(stark_felts).0
    }
}
```
___
*[`src/crypto/patricia_hash.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCfyfn0R-3l1QuUZCy:-NxCh6rFAV9aCRXkfauD:bsimxom) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/crypto/patricia_hash.rs#L77)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think using Fn trait is cleaner, see: https://doc.rust-lang.org/std/ops/trait.Fn.html#:~:text=This%20trait%20(%20Fn%20)%20is%20not,their%20documentation%20for%20more%20details).
</blockquote></details>

I was thinking of using generic types, like this:
```
fn get_hash<H: HashFunction>(sub_tree: SubTree<'_>) -> StarkFelt {
```
and then using `H::hash_pair` when needed.
I prefer `do_thing_involving_hash::<H>(args)` over `do_thing_involving_hash(args, stateless_variable_representing_hash_function)`, WDYT?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama, @yair-starkware, @yoavGrs, and @Yoni-Starkware)

___
*[`src/crypto/patricia_hash.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCfyfn0R-3l1QuUZCy:-NxCiGFAEbDMI9rKt6qX:bmwf6bi) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/crypto/patricia_hash.rs#L77)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I was thinking of using generic types, like this:
```
fn get_hash<H: HashFunction>(sub_tree: SubTree<'_>) -> StarkFelt {
```
and then using `H::hash_pair` when needed.
I prefer `do_thing_involving_hash::<H>(args)` over `do_thing_involving_hash(args, stateless_variable_representing_hash_function)`, WDYT?
</blockquote></details>

note that if these weren't just a bunch of flat functions,
but all part of a trait / struct impl,
you could define `<H: HashFunction>` on the struct/trait declaration and just use the available `H` in all methods of the trait/struct, without passing `H` around explicitly.
`get_edge_hash`, `get_hash`, `get_binary_hash` can all be in a `PatriciaHasher<H: HashFunction>` trait

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama, @yair-starkware, @yoavGrs, and @Yoni-Starkware)

___
*[`src/crypto/patricia_hash.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCfyfn0R-3l1QuUZCy:-NxCitiXDZ7HjVct7smP:brsd6bu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/crypto/patricia_hash.rs#L77)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

note that if these weren't just a bunch of flat functions,
but all part of a trait / struct impl,
you could define `<H: HashFunction>` on the struct/trait declaration and just use the available `H` in all methods of the trait/struct, without passing `H` around explicitly.
`get_edge_hash`, `get_hash`, `get_binary_hash` can all be in a `PatriciaHasher<H: HashFunction>` trait
</blockquote></details>

see [here](https://github.com/starkware-libs/committer/blob/main/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L27-L58) for an example in the committer

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 4 unresolved discussions (waiting on @ShahakShama, @yair-starkware, and @Yoni-Starkware)

___
*[`src/hash.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCg4vtEAuYrZawKUPe:-NxCkRJq3K5ZSc5_fx7M:ble2e17) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/hash.rs#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hash_array hashes the length as well IIRC
</blockquote></details>

Right, these are different functions.
(But I'm not sure that poseidon_hash_array hashes the length)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @ShahakShama, @yoavGrs, and @Yoni-Starkware)

___
*[`src/hash.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCg4vtEAuYrZawKUPe:-NxCx20G1w2SWUw_doo0:b-xi09bo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/hash.rs#L80)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Right, these are different functions.
(But I'm not sure that poseidon_hash_array hashes the length)
</blockquote></details>

If they are not doing the same thing, please rename/doc the difference. Otherwise please delete one of them

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ShahakShama, @yair-starkware, and @Yoni-Starkware)

___
*[`src/hash.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-NxCg4vtEAuYrZawKUPe:-NxCyyOICxr_bcBvA6iD:b-f8sf1p) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f4876867331c1011307f45956ca1529fd9641546/src/hash.rs#L80)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

If they are not doing the same thing, please rename/doc the difference. Otherwise please delete one of them
</blockquote></details>

Added a comment.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/216#-:-NxHfvbw6nHbWKXjT4m2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama and @Yoni-Starkware)

**Pull request merged**
