### PR TITLE
Better field type for deprecated class instead of serde_json::Value

### PR DESCRIPTION
**Pull request by dan-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/56)

### CODE REVIEW

**Comment by dan-starkware** [comment]
@noaov1 FYI

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/56)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @spapinistarkware)

___
*[`src/deprecated_contract_class.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/56#-NUGxh6e-z53I-h2xIj_:-NUGxh6e-z53I-h2xIja:b-n0ho3q) ([raw file](https://github.com/starkware-libs/starknet-api/blob/65fc8503cbd71acbb663e2e45debbb0764ba2906/src/deprecated_contract_class.rs#L96)):*
> ```XML
>     #[serde(skip_serializing_if = "Option::is_none")]
>     pub compiler_version: Option<String>,
>     pub data: Vec<StarkFelt>,
> ```

I see [LC are representing this](https://reviewable.io/reviews/starkware-libs/blockifier/432) as `Vec<MaybeRelocatable>`; could those felts be `Relocatable`? @spapinistarkware 



_Code quote:_
```XML
pub data: Vec<StarkFelt>,
```
___
*[`src/deprecated_contract_class.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/56#-NUGyDZRDfu_H8RRSrHT:-NUGyAWE28bNjAUSs7B1:b-c3pcuj) ([raw file](https://github.com/starkware-libs/starknet-api/blob/65fc8503cbd71acbb663e2e45debbb0764ba2906/src/deprecated_contract_class.rs#L99)):*
> ```XML
>     pub debug_info: serde_json::Value,
>     pub hints: HashMap<String, Vec<HintParams>>,
>     pub identifiers: serde_json::Value,
> ```

What about `identifiers` and `reference_manager`?



_Suggestion:_
```XML
HashMap<String, Identifier>
```

**Comment by dan-starkware** [comment]
*[`src/deprecated_contract_class.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/56#-NUGyDZRDfu_H8RRSrHT:-NUHE7X8CeBVxfAIcUgg:blw4shq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/65fc8503cbd71acbb663e2e45debbb0764ba2906/src/deprecated_contract_class.rs#L99)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about `identifiers` and `reference_manager`?
</blockquote></details>

Currently I made only trivial changes. Both identifiers and ref_mngr can hold `Felt252`.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/56)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @spapinistarkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/56)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/56#-NUKdB1tBdF0MkBXrbI2:-NUKdB1x-8y_9HSkRTT9:b-lh1lss) ([raw file](https://github.com/starkware-libs/starknet-api/blob/65fc8503cbd71acbb663e2e45debbb0764ba2906/Cargo.toml#L10)):*
> ```TOML
> 
> [dependencies]
> cairo-vm = { git = "https://github.com/lambdaclass/cairo-rs.git", rev = "d545372f" }
> ```

Can we use a semantic version instead here?
___
*[`src/deprecated_contract_class.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/56#-NUGxh6e-z53I-h2xIj_:-NUKdJAvDdfCaJTzBOOE:b1qos2v) ([raw file](https://github.com/starkware-libs/starknet-api/blob/65fc8503cbd71acbb663e2e45debbb0764ba2906/src/deprecated_contract_class.rs#L96)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I see [LC are representing this](https://reviewable.io/reviews/starkware-libs/blockifier/432) as `Vec<MaybeRelocatable>`; could those felts be `Relocatable`? @spapinistarkware 
</blockquote></details>

Why not, make it similar to the cairo_vm so we hopefully have near-zero translation cost

**Pull request closed without merging**
