### PR TITLE
feat: add ref getters for external transaction

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/234)

### CODE REVIEW

**Review by MohammadNassar1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/234)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`src/external_transaction.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/234#-NwnjshJ3FhwOLZCDJqM:-NwnjshJ3FhwOLZCDJqN:b-6ebs45) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bb856856bcec34e99f904cb5466db322a35ec61c/src/external_transaction.rs#L33)):*
> ```XML
> 
> macro_rules! implement_ref_getters {
>     ($(($member_name:ident, $member_type:ty));* $(;)?) => {
> ```

Could you tell me why you need this?

you can use `, *` instead, right?



_Code quote:_
```XML
;* $(;)?
```

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/234)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/external_transaction.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/234#-NwnjshJ3FhwOLZCDJqM:-NwntHb48bCHJf2hEYqu:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bb856856bcec34e99f904cb5466db322a35ec61c/src/external_transaction.rs#L33)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Could you tell me why you need this?

you can use `, *` instead, right?
</blockquote></details>

Done.

**Review by MohammadNassar1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/234#-:-NwoLVeg-NSEFO1uHnJ6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`src/external_transaction.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/234#-NwnjshJ3FhwOLZCDJqM:-NwoLLiTAnVV0jiR2Q-h:btsr271) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bb856856bcec34e99f904cb5466db322a35ec61c/src/external_transaction.rs#L33)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

out of curiosity: what's the differenece?

**Comment by ArniStarkware** [comment]
*[`src/external_transaction.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/234#-NwnjshJ3FhwOLZCDJqM:-Nwohloi-jHD8pEdnW4Y:b-c72wvp) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bb856856bcec34e99f904cb5466db322a35ec61c/src/external_transaction.rs#L33)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

out of curiosity: what's the differenece?
</blockquote></details>

one `,` in the current version VS two `;` in the old version. You can see it in the diff `r1` to `r2`.

**Pull request merged**
