### PR TITLE
Add test utils with get_test_instance for testing

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/4)

### CODE REVIEW

**Comment by dan-starkware** [comment]
Please break into smaller PRs

**Comment by anatgstarkware** [comment]
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please break into smaller PRs
</blockquote></details>

ptal https://reviewable.io/reviews/starkware-libs/starknet-api/6

**Review by giladchase — COMMENTED** [review]
Can you please explain what the motivation for this utility is?

For example, when put up against specialized utility functions inside the test modules, how much does this save?
And conversely, how much "glue"-code will need to be added for this to work (both in test-code and non-test-code)?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/4#-:-NJZ5n1Q6zBZ5X2LJxal:bcufgnj)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dan-starkware and @elintul)

**Comment by anatgstarkware** [comment]
ptal https://reviewable.io/reviews/starkware-libs/starknet-api/6

**Comment by anatgstarkware** [comment]
To be implemented as macro rules in papyrus, or as a derive macro in starknet_api (https://reviewable.io/reviews/starkware-libs/starknet-api/6)

**Pull request closed without merging**
