### PR TITLE
fix: calculate l1 gas consumed

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/257)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/257)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/257#-NyFdIFiDAeJXeQl22D8:-NyFdIFiDAeJXeQl22D9:b-cddpn9) (no related file):*
Where is the connection to the block hash? It should have changed from this PR. Is it not connected yet?

___
___
*[`src/block_hash/receipt_commitment.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/257#-NyFZ2NO9UCTKjHh4Iko:-NyFZ2NO9UCTKjHh4Ikp:bqtdv7y) ([raw file](https://github.com/starkware-libs/starknet-api/blob/08e54ff4a2166ca27cefe80644cdb7d4f5f9b5d6/src/block_hash/receipt_commitment.rs#L17)):*
> ```XML
> pub fn calculate_receipt_commitment<H: HashFunction>(
>     transactions_receipt: &[TransactionReceipt],
>     l1_data_gas_wei_price: GasPrice,
> ```

Why wei? IIRC It depends on the transaction. If it's a v3 transaction you should put fri here
___
*[`src/block_hash/receipt_commitment.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/257#-NyFZPAe-8a_LNxym6zo:-NyFZPAe-8a_LNxym6zp:b8qs6xb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/08e54ff4a2166ca27cefe80644cdb7d4f5f9b5d6/src/block_hash/receipt_commitment.rs#L82)):*
> ```XML
> // L1 gas consumed (In the current RPC:
> //      L1 gas consumed for calldata + L1 gas consumed for steps and builtins.
> //      Calculated as: total L1 gas consumed - L1 data gas consumed for blob),
> ```

total L1 gas consumed is L1 gas consumed. Data gas is not gas
You can write here `(actual_fee - actual_l1_data_gas_fee) / l1_gas_price`

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/257)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`src/block_hash/receipt_commitment.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/257#-NyK1Hxr098klSMucHVa:-NyK1Hxr098klSMucHVb:bgimw6i) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d4f5e940585443acad3286a5347eda0255a340ed/src/block_hash/receipt_commitment.rs#L112)):*
> ```XML
> }
> 
> fn get_price_by_version(
> ```

This is a useful function. Add a TODO to move it to transaction.rs and make it public
___
*[`src/block_hash/receipt_commitment_test.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/257#-NyK1Vq2-0oeSHMyyrBo:-NyK1Vq2-0oeSHMyyrBp:b-592al7) ([raw file](https://github.com/starkware-libs/starknet-api/blob/d4f5e940585443acad3286a5347eda0255a340ed/src/block_hash/receipt_commitment_test.rs#L45)):*
> ```XML
>     };
>     let l1_data_gas_price =
>         GasPricePerToken { price_in_fri: GasPrice(456), price_in_wei: GasPrice(456) };
> ```

Make the prices different to check that you're calling the correct price.
You can have two prices, one with fri = x, wei = y for the v2 transaction, and one with fri = y, wei = z for the v3 transaction

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/257)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/257#-NyFdIFiDAeJXeQl22D8:-NyFdovPAf4mpsJZ7Q3u:b556ik) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Where is the connection to the block hash? It should have changed from this PR. Is it not connected yet?
</blockquote></details>

Right, I will update the block hash (251, 248) after this PR.

___

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/257#-:-NyK4YP56XscGubXDf4j:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
