### PR TITLE
add transaction execution status enum

### PR DESCRIPTION
**Pull request by nagmo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* main
  * **PR #96** <a href="https://app.graphite.dev/github/pr/starkware-libs/starknet-api/96" target="_blank">Graphite</a> 
    * **PR #100** <a href="https://app.graphite.dev/github/pr/starkware-libs/starknet-api/100" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/starknet-api/100?utm_source=stack-comment).

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`src/block.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_mZyWX6YgM9x15Ua6S:-N_mZyWYBEm_-vT7lnSa:b-rg53ld) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e95b6c4f067ba291ba6dfa107f9e4f8d14012e2d/src/block.rs#L41)):*
> ```XML
>     pub transactions: Vec<Transaction>,
>     pub transaction_outputs: Vec<TransactionOutput>,
>     pub transaction_execution_status: Vec<TransactionExecutionStatus>,
> ```

transaction_execution_statuses (in plural)
Could you check with @AlonStark that it's correct English?
___
*[`src/transaction.rs` line 275 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_m_DeY4jiev-4-Absv:-N_m_DeY4jiev-4-Absw:b-yfjau4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e95b6c4f067ba291ba6dfa107f9e4f8d14012e2d/src/transaction.rs#L275)):*
> ```XML
> /// Transaction execution status.
> #[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord, Default)]
> pub enum TransactionExecutionStatus {
> ```

Consider removing default

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @AlonStark, @dan-starkware, and @ShahakShama)

___
*[`src/block.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_mZyWX6YgM9x15Ua6S:-N_mdCNyCIFal-Ep54xf:bsb9la0) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e95b6c4f067ba291ba6dfa107f9e4f8d14012e2d/src/block.rs#L41)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

transaction_execution_statuses (in plural)
Could you check with @AlonStark that it's correct English?
</blockquote></details>

it's correct english just looks ugly.. I'm fine with changing to plural. 
___
*[`src/transaction.rs` line 275 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_m_DeY4jiev-4-Absv:-N_mdL-96abgnG2zqPK7:b-kc0fpb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e95b6c4f067ba291ba6dfa107f9e4f8d14012e2d/src/transaction.rs#L275)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider removing default
</blockquote></details>

it's needed since past blocks don't have this and have only successful TXs

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonStark and @ShahakShama)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @AlonStark and @nagmo-starkware)

___
*[`src/block.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_mZyWX6YgM9x15Ua6S:-N_mpXlgBrgf5-8YnYjv:b-k11pfk) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e95b6c4f067ba291ba6dfa107f9e4f8d14012e2d/src/block.rs#L41)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's correct english just looks ugly.. I'm fine with changing to plural. 
</blockquote></details>

My problem with transaction_execution_status is that it doesn't show that there are multiple statuses here. I could've thought that there's only one execution status per block
___
*[`src/transaction.rs` line 275 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_m_DeY4jiev-4-Absv:-N_mpeK41XTL5d0M4tQf:b-dnobqg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e95b6c4f067ba291ba6dfa107f9e4f8d14012e2d/src/transaction.rs#L275)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's needed since past blocks don't have this and have only successful TXs
</blockquote></details>

Then maybe add a comment saying that
e.g // Succeeded is the default variant because old versions of Starknet don't have an execution status and every transaction is considered succeeded

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @nagmo-starkware)

___
*[`src/transaction.rs` line 274 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_n7xM34-A6Z47sNGXg:-N_n7xM34-A6Z47sNGXh:b-lnefl8) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4b14daf859f000c43c3c1bf9bc352b089b0926fa/src/transaction.rs#L274)):*
> ```XML
> 
> /// Transaction execution status.
> /// Succeeded is the default variant because old versions of Starknet don't have an execution status
> ```

Make this a comment and not a document, and move it to the #[default] line

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`src/transaction.rs` line 274 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-N_n7xM34-A6Z47sNGXg:-N_nA3q_4wXBBnv54srr:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4b14daf859f000c43c3c1bf9bc352b089b0926fa/src/transaction.rs#L274)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this a comment and not a document, and move it to the #[default] line
</blockquote></details>

Done.

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100#-:-N_nAGyL-VzdnYWMAUf1:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nagmo-starkware)

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)

**Pull request merged**
