### PR TITLE
feat: impl From<EthAddress> for StarkFelt

### PR DESCRIPTION
**Pull request by tdelabro**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/164)

### CODE REVIEW

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/164)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @tdelabro)

___
*[`src/core.rs` line 271 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/164#-NnE1ExN0kbz4SGOBriD:-NnE1ExN0kbz4SGOBriE:b-odpii1) ([raw file](https://github.com/starkware-libs/starknet-api/blob/687433aefd52769b1b2c3e9bbdc580167a7267a3/src/core.rs#L271)):*
> ```XML
>         // Padding H160 with zeros to 32 bytes (big endian)
>         bytes[12..32].copy_from_slice(value.0.as_bytes());
>         StarkFelt::new_unchecked(bytes)
> ```

I think the risk of adding this unsafe constructor is warranted for this usage.
WDYT?



_Suggestion:_
```XML
        StarkFelt::new(bytes).expect("EthAddress should be within StarkFelt bounds")
```
___
*[`src/hash.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/164#-NnE1zxJAI3oX5SREZTs:-NnE1zxJAI3oX5SREZTt:bop6b1q) ([raw file](https://github.com/starkware-libs/starknet-api/blob/687433aefd52769b1b2c3e9bbdc580167a7267a3/src/hash.rs#L60)):*
> ```XML
>     }
> 
>     pub const fn new_unchecked(bytes: [u8; 32]) -> StarkFelt {
> ```

See comment above please.

**Comment by tdelabro** [comment]
The unchecked constructor is used there it won't be the only place. We added it to our fork as it is useful in multiple places.
The main thing is that it is `const` while `new` cannot be `const` because the check returns an error that allocates memory:
```rust
        Err(StarknetApiError::OutOfRange { string: hex_str_from_bytes::<32, true>(bytes) })
```
So there is now a way to create `StarkFelt` in a `const` environment, which is useful/required.

**Review by giladchase — COMMENTED** [review]
Fair enough, so please add a docstring to this method that sufficiently scares off users against abusing it.
In other words, when a `StarkFelt` is created this way for an out of bounds number, here be dragons...

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/164#-:-NnYNVeNAoKOprw1FiUx:b-dpcovj)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by tdelabro** [comment]
> Fair enough, so please add a docstring to this method that sufficiently scares off users against abusing it.
In other words, when a StarkFelt is created this way for an out of bounds number, here be dragons...

@giladchase Done

**Review by giladchase — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/164#-:-NniyAKC3fd1zQ5JXjdE:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @tdelabro)

___
*[`src/hash.rs` line 68 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/164#-NnipHm72EbSFWA6tDGy:-NnipHm72EbSFWA6tDGz:b-2uvoo2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/eab582ea1017b3b8b9251b0c00d957852d6b8e70/src/hash.rs#L68)):*
> ```XML
>     /// The `StarkFelt::new` method make sure that you can't initialize a `StarkFelt` greater than
>     /// it's specification maximum. This method does not not. It's your responsability make sure
>     /// it's okay to call this method.
> ```

For brevity, also to avoid duplicated instructions.



_Suggestion:_
```XML
/// To avoid undefined behavior, refer to [`StarkFelt`] struct's docstring for the required constraints on the `bytes` argument, or use [`StarkFelt::new`] instead of this method.
```
___
*[`src/hash.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/164#-NnixuLvE68GHHrKIy82:-NnixuLw4s47HmgYX6cT:b45h) ([raw file](https://github.com/starkware-libs/starknet-api/blob/eab582ea1017b3b8b9251b0c00d957852d6b8e70/src/hash.rs#L75)):*
> ```XML
>     /// - creating instances of `StarkFelt` at compile time
>     /// - implementing `From<T> for StarkFelt` on types that have a smaller binary representation
>     ///   than `StarkFelt`
> ```





_Suggestion:_
```XML
    /// Most of the time you should use `new` instead, but it comes in handy for a few cases:
    /// - creating instances of `StarkFelt` at compile time
    /// - implementing `From<T> for StarkFelt` for types that have a smaller binary representation
    ///   than `StarkFelt`
```

**Review by giladchase — COMMENTED** [review]
Plz rebase and i'll merge it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/164#-:-NnmHM7o5hoZr7iqB810:b5v3q8n)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Comment by tdelabro** [comment]
> Plz rebase and i'll merge it.


Just did :)

**Review by giladchase — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/164)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Pull request merged**
