### PR TITLE
Import initial code

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/1)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/1)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/1#-NH4Qo4N0yD30iTNsyRK:-NH4Qo4N0yD30iTNsyRL:b-b6pkfq) (no related file):*
Do we want module, submodules?

___

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/1)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/1#-NH4Qo4N0yD30iTNsyRK:-NH4aTzd4TnZofWaZWmI:b3et4jm) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want module, submodules?
</blockquote></details>

I don't think we do.
Currently, each of the files contains one module, and every module contains mostly relevant stuff, with very little logic (mostly definitions of structs).

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/1#-:-NH5LOJx2naz21EQqPiG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/1)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @alonh5, @elintul, and @giladchase)

___
*[`src/state.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/1#-NHKHAb8B3IjR4XY8Osq:-NHKHAb8B3IjR4XY8Osr:b-4x3wxc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2b5e1d9dc633ae1ccebe8b526755971bee0d04ab/src/state.rs#L210)):*
> ```XML
> /// A program corresponding to a contract class in StarkNet.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> pub struct Program {
> ```

Note that @anatgstarkware added a new field named `compiler_version` to the `Program` struct (in the following PR: https://reviewable.io/reviews/starkware-libs/papyrus/324)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/1)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @alonh5, @anatgstarkware, and @elintul)

___
*[`src/state.rs` line 210 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/1#-NHKHAb8B3IjR4XY8Osq:-NHKQHfl2Nn1fXji43l2:bx4gth6) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2b5e1d9dc633ae1ccebe8b526755971bee0d04ab/src/state.rs#L210)):*
<details><summary><i>Previously, noaov1 wrote…</i></summary><blockquote>

Note that @anatgstarkware added a new field named `compiler_version` to the `Program` struct (in the following PR: https://reviewable.io/reviews/starkware-libs/papyrus/324)
</blockquote></details>

Thanks, but i think it'd be better to handle these conflicts when we merge papyrus into here.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/1#-:-NHKQqazDBZDLtZnRY3F:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware)

**Pull request merged**
