### PR TITLE
Add ExecutionResources to transaction output

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/151)

### CODE REVIEW

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/151)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`src/transaction.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/151#-NiohuCb3fU5V6gQANRo:-NiohuCb3fU5V6gQANRp:bzgsgx8) ([raw file](https://github.com/starkware-libs/starknet-api/blob/40b06d0a5b7ac4018cb36a7595dedae58b9481da/src/transaction.rs#L70)):*
> ```XML
>     }
> 
>     pub fn execution_resources(&self) -> &ExecutionResources {
> ```

We should at some point create a CommonTransactionOutput struct and avoid these methods, but now is not the time
___
*[`src/transaction.rs` line 655 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/151#-NiogvKe19Pu821P8yDb:-NiogvKf0fOKrGD-bH8n:biurd9i) ([raw file](https://github.com/starkware-libs/starknet-api/blob/40b06d0a5b7ac4018cb36a7595dedae58b9481da/src/transaction.rs#L655)):*
> ```XML
> #[derive(Debug, Deserialize, Serialize, Clone, Eq, PartialEq)]
> #[serde(untagged)]
> pub enum BuiltinInstanceCounter {
> ```

Consider having an Option instead
```
pub type BuiltinInstanceCounter = Option<HashMap<...
```
I think that the type above has serde implementation with behaviour identical to what you seek, or maybe you can tweak it to what you seek with skip_if

If that doesn't work, can you check if having a unit variant does work (Change the `Empty(EmptyBuiltinInstanceCounter),` to `Empty,`)

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/151)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`src/transaction.rs` line 655 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/151#-NiogvKe19Pu821P8yDb:-Nj3BW9aBRVqYO1JpiKo:b-6lx3bs) ([raw file](https://github.com/starkware-libs/starknet-api/blob/40b06d0a5b7ac4018cb36a7595dedae58b9481da/src/transaction.rs#L655)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider having an Option instead
```
pub type BuiltinInstanceCounter = Option<HashMap<...
```
I think that the type above has serde implementation with behaviour identical to what you seek, or maybe you can tweak it to what you seek with skip_if

If that doesn't work, can you check if having a unit variant does work (Change the `Empty(EmptyBuiltinInstanceCounter),` to `Empty,`)
</blockquote></details>

Changed to a simpler struct

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/151#-:-Nj3EYnb9nVOCsUG9694:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`src/transaction.rs` line 669 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/151#-Nj3CDAl4St5ctdmzuXO:-Nj3CDAl4St5ctdmzuXP:bapbmze) ([raw file](https://github.com/starkware-libs/starknet-api/blob/56c0cca56fdee341fbf9e996afd41954447f0e7b/src/transaction.rs#L669)):*
> ```XML
>     Keccak,
>     #[serde(rename = "segment_arena_builtin_applications")]
>     SegmentArena,
> ```

I remember there was a discussion in slack if this is needed or not. What was the final verdict?

**Comment by yair-starkware** [comment]
*[`src/transaction.rs` line 669 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/151#-Nj3CDAl4St5ctdmzuXO:-Nj3F0iv0fItwGJQYsbB:b-d2dof5) ([raw file](https://github.com/starkware-libs/starknet-api/blob/56c0cca56fdee341fbf9e996afd41954447f0e7b/src/transaction.rs#L669)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I remember there was a discussion in slack if this is needed or not. What was the final verdict?
</blockquote></details>

The SegmentArena? it is needed

**Pull request merged**
