### PR TITLE
feat(crypto): add crypto module with signature verification functionality

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/166)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/166)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/166#-NmVb_wLAfZX4PlwobB2:-NmVb_wLAfZX4PlwobB3:b-57fdz8) (no related file):*
What's the goal of this PR? why wrap starknet_crypto instead of just using it?

___
___
*[`src/crypto.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/166#-NmVb7Zp8gpwd8lGaYhp:-NmVb7Zp8gpwd8lGaYhq:bj3mk4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/849af445def3b1be746cd64f720faf9cefbcd3c2/src/crypto.rs#L52)):*
> ```XML
>         &signature.s.into(),
>     )
>     .map_err(|err| match err {
> ```

Extract to `impl From`
Also, why not just use starknet_crypto::VerifyError?

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/166)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/166#-NmVb_wLAfZX4PlwobB2:-NmVwXHDEv38XISmIcGI:b-gf6jfq) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What's the goal of this PR? why wrap starknet_crypto instead of just using it?
</blockquote></details>

discussed

___
___
*[`src/crypto.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/166#-NmVb7Zp8gpwd8lGaYhp:-NmVwPleDKHqcZC00x3i:bhqdhe5) ([raw file](https://github.com/starkware-libs/starknet-api/blob/849af445def3b1be746cd64f720faf9cefbcd3c2/src/crypto.rs#L52)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Extract to `impl From`
Also, why not just use starknet_crypto::VerifyError?
</blockquote></details>

I need to pass additional data for the error

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/166#-:-NmZxm2KB8mqjbvDUJs_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/166#-:-NmZyxedBue48PgiPQUa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
