### PR TITLE
Fixate parity_scale_codec on 3.6.5 to fix error in udeps

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/158)

### CODE REVIEW

**Review by dan-starkware — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/158)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/158#-NlIhaxz-vwRsbCUOgRZ:-NlIhay-7ZAOcInlr6rS:byvv3w2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/48df14d3a4cdc418404e04cf401c3ac4569ade8a/Cargo.toml#L19)):*
> ```TOML
> indexmap = { version = "1.9.2", features = ["serde"] }
> once_cell = "1.17.1"
> # TODO: Remove the explicit version once the following issue is resolved: https://github.com/paritytech/parity-scale-codec/issues/520
> ```

I don't think it relates to the same issue



_Code quote:_
```TOML
https://github.com/paritytech/parity-scale-codec/issues/520
```

**Comment by yair-starkware** [comment]
*[`Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/158#-NlIhaxz-vwRsbCUOgRZ:-NlIviEd6MSgerU-E15A:b-n9tkhd) ([raw file](https://github.com/starkware-libs/starknet-api/blob/48df14d3a4cdc418404e04cf401c3ac4569ade8a/Cargo.toml#L19)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I don't think it relates to the same issue
</blockquote></details>

changed

**Review by dan-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/158)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/158#-:-NlJ9MXn8E1HsgfB1jPy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by dan-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/158)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
