### PR TITLE
feat(block): block signatures

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/134)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/134)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @yair-starkware)

___
*[`src/block_test.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/134#-NmVcCLR1ThTt6HIik5S:-NmVcCLR1ThTt6HIik5T:b-pqolmg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/94f6bb5b9d6d5638a4a9c57ef13d9123293f4807/src/block_test.rs#L32)):*
> ```XML
> fn block_signature_verification() {
>     let block_hash =
>         BlockHash(stark_felt!("0x7d5db04c5ca2aea828180dc441afb1580e3cee7547a3567ced3aa5bb8b273c0"));
> ```

Add in a comment where these come from (I guess they come from some public starknet chain)
___
*[`src/lib.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/134#-NmVcXZT6nTHSFyIlLau:-NmVcXZT6nTHSFyIlLav:bfsig90) ([raw file](https://github.com/starkware-libs/starknet-api/blob/94f6bb5b9d6d5638a4a9c57ef13d9123293f4807/src/lib.rs#L38)):*
> ```XML
>     InvalidResourceMappingInitializer(String),
>     #[error("Failed to verify the signature of block {block_hash}. Error: {error}")]
>     BlockSignatureVerificationFailed { block_hash: BlockHash, error: CryptoError },
> ```

Won't it require us to handle this error in all of our starknet api errors? Why not create a separate error for this

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/134)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @ShahakShama)

___
*[`src/block_test.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/134#-NmVcCLR1ThTt6HIik5S:-NmW-rI76Ld2BDSd-0cv:bb7f2mf) ([raw file](https://github.com/starkware-libs/starknet-api/blob/94f6bb5b9d6d5638a4a9c57ef13d9123293f4807/src/block_test.rs#L32)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add in a comment where these come from (I guess they come from some public starknet chain)
</blockquote></details>

done
___
*[`src/lib.rs` line 38 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/134#-NmVcXZT6nTHSFyIlLau:-NmW-tymBHQWEBODEV4y:b-896fiz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/94f6bb5b9d6d5638a4a9c57ef13d9123293f4807/src/lib.rs#L38)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Won't it require us to handle this error in all of our starknet api errors? Why not create a separate error for this
</blockquote></details>

Done,

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/134#-:-NmZy2cb9fEk8wrpVHbA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/134#-:-Nm_0Ieq4vzHffLFYvwU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Pull request merged**
