### PR TITLE
build: impl display for fee and contractaddress structs

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/279)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/279)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-VtfNz0kHJBg7nJXE7:-O-VtfNz0kHJBg7nJXE8:b4n8tll) (no related file):*
please add a unit test that makes sure the output is nice-looking... i.e.
```
fn test_nice() {
    assert_eq!(format("{}", patricia_key!(7_u8)), "0x7");
}
```

___
___
*[`src/transaction.rs` line 649 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-Vtxkg9RH0Fp7hExdm:-O-Vtxkg9RH0Fp7hExdn:b6upxvt) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e87e047930d8f1ba9cb378c16e70e2081e258338/src/transaction.rs#L649)):*
> ```XML
>     Clone,
>     Default,
>     Display,
> ```

why is this needed? it wraps a u128, this should be displayed fine



_Code quote:_
```XML
Display,
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/279)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-VtfNz0kHJBg7nJXE7:-O-_MgiVCmW9tmc7jIhP:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a unit test that makes sure the output is nice-looking... i.e.
```
fn test_nice() {
    assert_eq!(format("{}", patricia_key!(7_u8)), "0x7");
}
```
</blockquote></details>

Done.

___
___
*[`src/transaction.rs` line 649 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-Vtxkg9RH0Fp7hExdm:-O-_MiQoEbo0_96Lf2zS:bb38swi) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e87e047930d8f1ba9cb378c16e70e2081e258338/src/transaction.rs#L649)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed? it wraps a u128, this should be displayed fine
</blockquote></details>

We talked about it later

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/279)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`src/core.rs` line 309 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-_et2yDfZOhFy6O2vS:-O-_et2yDfZOhFy6O2vT:bu0irqq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4c23cae3ae614087cc6856e20db9d5e1f96b7104/src/core.rs#L309)):*
> ```XML
>     Ord,
>     derive_more:: Deref,
>     Display,
> ```

why did this move down?



_Code quote:_
```XML
 Display,
```
___
*[`src/core.rs` line 311 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-_f4p83zvM6-4gXQnv:-O-_f4p83zvM6-4gXQnw:b-ih4wkx) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4c23cae3ae614087cc6856e20db9d5e1f96b7104/src/core.rs#L311)):*
> ```XML
>     Display,
> )]
> #[display(fmt = "{}", "_0.to_fixed_hex_string()")]
> ```

this works? cool



_Code quote:_
```XML
#[display(fmt = "{}", "_0.to_fixed_hex_string()")]
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/279)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`src/core.rs` line 309 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-_et2yDfZOhFy6O2vS:-O-_farD9b7iHBE8Q1I9:b-ixsi9j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4c23cae3ae614087cc6856e20db9d5e1f96b7104/src/core.rs#L309)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did this move down?
</blockquote></details>

No special reason.
___
*[`src/core.rs` line 311 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-_f4p83zvM6-4gXQnv:-O-_feqsDas_i_JHf86H:b-5pbm18) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4c23cae3ae614087cc6856e20db9d5e1f96b7104/src/core.rs#L311)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this works? cool
</blockquote></details>

yes, its possible if u use the derive_moe:Display macro

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/279)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`src/core.rs` line 309 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-O-_et2yDfZOhFy6O2vS:-O-_iqIDC-YCgOK7Em8D:b6njycc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4c23cae3ae614087cc6856e20db9d5e1f96b7104/src/core.rs#L309)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please move back
</blockquote></details>

I hope that I put it back to the same place

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/279#-:-O-aAUQc6SmQrb7YkwQb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
