### PR TITLE
Stabilize 0.6.0 - remove rc from version

### PR DESCRIPTION
**Pull request by giladchase**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/162)

### CODE REVIEW

**Review by giladchase — COMMENTED** [review]
Major:  blocking to remind myself to full-merge instead of merge-queue/squash/rebase

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/162#-:-NlOUgubE-OOeLrDJgOW:b-8wiu4c)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/162)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/162#-NlOVK9B4cpw6J7mzgg5):*
Blocking to remind myself to merge.

**Review by liorgold2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/162#-:-NlOWPt02sD_PKteulcL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

**Review by liorgold2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/162)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

**Pull request merged**
