### PR TITLE
feat(transaction): implement internal transaction converters

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`Cargo.toml` line 28 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/222#-NuXlx8a42KeVMzjpJml:-Nud44SWDua0W5yf9NFx:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2b5913c7259452875ecb85311f9d69c009268d40/Cargo.toml#L28)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

please remove
</blockquote></details>

Done.

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`src/internal_transaction.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/222#-Nusx_3C2mhxfCVX50Ns:-Nusx_3C2mhxfCVX50Nt:b8jh3ta) ([raw file](https://github.com/starkware-libs/starknet-api/blob/c04035d34163f0b145df8900a39608bcf4277a41/src/internal_transaction.rs#L55)):*
> ```XML
> 
> impl From<ExternalTransaction> for InternalTransaction {
>     fn from(value: ExternalTransaction) -> Self {
> ```

Switch all From into a regular function, `into_internal`, for all types.
Rationale: this isn't a cast, it's a state transition.

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`src/internal_transaction.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/222#-Nusx_3C2mhxfCVX50Ns:-NuwlIZSCVL-5hp1LyZm:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/c04035d34163f0b145df8900a39608bcf4277a41/src/internal_transaction.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Switch all From into a regular function, `into_internal`, for all types.
Rationale: this isn't a cast, it's a state transition.
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`src/external_transaction.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/222#-Nv0hLkt31t-g88X0BTA:-Nv0hLkt31t-g88X0BTB:boz0imp) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e3a22263a66aed06dcb5819c8af44dd24f06570a/src/external_transaction.rs#L197)):*
> ```XML
>                 contract_class: InternalContractClass::default(),
>                 sierra_program_length: 0,
>             },
> ```

FYI this could have just been default, but this is temp code so doesn't matter really



_Code quote:_
```XML
            class_info: ClassInfo {
                abi_length: 0,
                contract_class: InternalContractClass::default(),
                sierra_program_length: 0,
            },
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware, @elintul, and @giladchase)

___
*[`src/external_transaction.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/222#-Nv0hLkt31t-g88X0BTA:-Nv0imq60MbJ9YgLmjA7:by3rsfd) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e3a22263a66aed06dcb5819c8af44dd24f06570a/src/external_transaction.rs#L197)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

FYI this could have just been default, but this is temp code so doesn't matter really
</blockquote></details>

`ClassInfo` doesn't implement  `Default`.

**Review by giladchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

___
*[`src/external_transaction.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/222#-Nv0hLkt31t-g88X0BTA:-Nv0j0R5E6frm_5e3Gqr:b-l114it) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e3a22263a66aed06dcb5819c8af44dd24f06570a/src/external_transaction.rs#L197)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

`ClassInfo` doesn't implement  `Default`.
</blockquote></details>

Hmm I wonder why, anyway, not critical for now, ignore.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/222#-:-Nv5roTe6xV5caDevjA3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @elintul)

**Comment by giladchase** [comment]
Continued in https://reviewable.io/reviews/starkware-libs/starknet-api/230

**Pull request closed without merging**
