### PR TITLE
Mohammad/external tx/resource bounds/implement from trait

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/264)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/264)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/external_transaction.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/264#-NzMs-1KChBMnWe735qP:-NzMs-1KChBMnWe735qQ:breex9o) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bff11bc9dfd7d850417903e5801c23b3be540db3/src/external_transaction.rs#L172)):*
> ```XML
> }
> 
> impl From<ResourceBoundsMapping> for crate::transaction::ResourceBoundsMapping {
> ```

I'm confused; why do we need both types?



_Code quote:_
```XML
crate::transaction::ResourceBoundsMapping
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/264)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`src/external_transaction.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/264#-NzMs-1KChBMnWe735qP:-NzNQFo05a_Pe9f4OvOd:blpi776) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bff11bc9dfd7d850417903e5801c23b3be540db3/src/external_transaction.rs#L172)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm confused; why do we need both types?
</blockquote></details>

The RPC field expects small letters `l1_gas` & `l2_gas`.
While the transaction is Capital letters, which doesn't follow the [spec](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L3719C1-L3737C15).

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/264)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/external_transaction.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/264#-NzTS01r8mxXh33Fjti0:-NzTS01r8mxXh33Fjti1:bievws3) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bff11bc9dfd7d850417903e5801c23b3be540db3/src/external_transaction.rs#L176)):*
> ```XML
>         let mut map = BTreeMap::new();
>         map.insert(Resource::L1Gas, mapping.l1_gas);
>         map.insert(Resource::L2Gas, mapping.l2_gas);
> ```

Please use a `BTreeMap` c-tor from tuples.



_Code quote:_
```XML
        let mut map = BTreeMap::new();
        map.insert(Resource::L1Gas, mapping.l1_gas);
        map.insert(Resource::L2Gas, mapping.l2_gas);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/264)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`src/external_transaction.rs` line 176 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/264#-NzTS01r8mxXh33Fjti0:-NzTSsTq5QUnnBZpdN82:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/bff11bc9dfd7d850417903e5801c23b3be540db3/src/external_transaction.rs#L176)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please use a `BTreeMap` c-tor from tuples.
</blockquote></details>

Done

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/264#-:-NzTVC363bMMmrSGKuOs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Pull request merged**
