### PR TITLE
feat: calculate state diff hash

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/243)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/243)* status: all files reviewed, 4 unresolved discussions (waiting on @yoavGrs)

___
*[`src/block_hash/state_diff_hash.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR5kGl1Bdkrf78iNR0:-NxR5kGl1Bdkrf78iNR1:b-pyua95) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L23)):*
> ```XML
> /// ).
> pub fn calculate_state_diff_hash(state_diff: &ThinStateDiff) -> StateDiffCommitment {
>     let mut hash_chain = HashChain::new().chain(&STARKNET_STATE_DIFF0);
> ```

Split this into two lines. It's really easy to miss the fact that you enter STARKNET_STATE_DIFF0 to the chain currently
___
*[`src/block_hash/state_diff_hash.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR5xHM6o2IE26AcswE:-NxR5xHM6o2IE26AcswF:b6g36v2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L28)):*
> ```XML
>     hash_chain =
>         chain_deprecated_declared_classes(&state_diff.deprecated_declared_classes, hash_chain);
>     hash_chain = chain_data_availability_modes(&state_diff.storage_diffs, hash_chain);
> ```

IMO data_availability_modes is a term that shouldn't appear here until we have it implemented, for now you can just chain the zeroes that come from it with a comment and then call functions called chain_storage_diffs and chain_nonces
___
*[`src/block_hash/state_diff_hash.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR6sgH7iCg40KtQLqG:-NxR6sgH7iCg40KtQLqH:b-ogoh4t) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L35)):*
> ```XML
> fn chain_deployed_contracts(
>     deployed_contracts: &IndexMap<ContractAddress, ClassHash>,
>     mut hash_chain: HashChain,
> ```

Why not receive a mut& to HashChain instead of returning it each time?
I'm really asking. I'm not sure what is the correct one and wanted to know why you chose this
___
*[`src/block_hash/state_diff_hash.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR7B4Q6Os8kGgDZ3Ay:-NxR7B4Q6Os8kGgDZ3Az:b-6u934f) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L76)):*
> ```XML
>     hash_chain = hash_chain.chain(&StarkFelt::ONE) // number of DA modes.
>         .chain(&StarkFelt::ZERO); // the DA mode.
>     chain_storage_diffs(storage_diffs, hash_chain)
> ```

What about nonces???

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/243)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ShahakShama)

___
*[`src/block_hash/state_diff_hash.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR5kGl1Bdkrf78iNR0:-NxRBBB23iyDmHbE-QFh:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Split this into two lines. It's really easy to miss the fact that you enter STARKNET_STATE_DIFF0 to the chain currently
</blockquote></details>

Done.
___
*[`src/block_hash/state_diff_hash.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR5xHM6o2IE26AcswE:-NxRDMvL15BM4YUnZAXJ:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L28)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO data_availability_modes is a term that shouldn't appear here until we have it implemented, for now you can just chain the zeroes that come from it with a comment and then call functions called chain_storage_diffs and chain_nonces
</blockquote></details>

Done.
___
*[`src/block_hash/state_diff_hash.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR6sgH7iCg40KtQLqG:-NxRDNhJ9SDSX0O-dMDT:b-wjmq41) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L35)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not receive a mut& to HashChain instead of returning it each time?
I'm really asking. I'm not sure what is the correct one and wanted to know why you chose this
</blockquote></details>

The `chain` operation of hash_chain takes and returns hash_chain.
___
*[`src/block_hash/state_diff_hash.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxR7B4Q6Os8kGgDZ3Ay:-NxRF_nV6o14W_X4YCoD:b-834n6i) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3d1d9bbdcdc8b4166922f1995fd4ea00ece4bcfb/src/block_hash/state_diff_hash.rs#L76)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

What about nonces???
</blockquote></details>

Oops.

**Review by ShahakShama — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-:-NxRJWYp1wFVA5YPEqLV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`src/block_hash/state_diff_hash.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-NxRJ1tc3tD_L0hk16eD:-NxRJ1tc3tD_L0hk16eE:bmozvmh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/400db56d7de69d84b0188e91097448e57e95a61f/src/block_hash/state_diff_hash.rs#L20)):*
> ```XML
> /// Poseidon(
> ///     "STARKNET_STATE_DIFF0", deployed_contracts, declared_classes, deprecated_declared_classes,
> ///     1, 0, storage_diffs
> ```

Add nonces to here as well

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/243#-:-NxRREQk3tkUm-N5fuK3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
