### PR TITLE
feat: add len to ThinStateDiff

### PR DESCRIPTION
**Pull request by ShahakShama**
- feat!: add missing fields to BlockHeader
- feat: add len to ThinStateDiff

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/191)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/191)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware and @ShahakShama)

___
*[`src/core.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/191#-NsrrwG0Cuk6yeSHaBcV:-NsrrwG13Od69-oOqgdf:b-imtnwp) ([raw file](https://github.com/starkware-libs/starknet-api/blob/be3eb91a550748694d982980c25e4fe11e2c9ad6/src/core.rs#L245)):*
> ```XML
>     Display,
> )]
> pub struct ReceiptCommitment(pub StarkHash);
> ```

It is not mentioned in the document about the hashes - is it not a Poseidon hash?



_Code quote:_
```XML
StarkHash
```

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/191)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware and @yair-starkware)

___
*[`src/core.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/191#-NsrrwG0Cuk6yeSHaBcV:-NsrsS8-8jN0c1Iq2IDT:b-liemdk) ([raw file](https://github.com/starkware-libs/starknet-api/blob/be3eb91a550748694d982980c25e4fe11e2c9ad6/src/core.rs#L245)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It is not mentioned in the document about the hashes - is it not a Poseidon hash?
</blockquote></details>

It should be the same type as EventCommitment, TransactionCommitment. etc.
I think they're all poseidon

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/191)* status: all files reviewed, 1 unresolved discussion (waiting on @nagmo-starkware and @ShahakShama)

___
*[`src/core.rs` line 245 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/191#-NsrrwG0Cuk6yeSHaBcV:-NsrtBoT40ge1oEpF4ez:bqpa4dz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/be3eb91a550748694d982980c25e4fe11e2c9ad6/src/core.rs#L245)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think currently they are not. The block signature is on Poseidon(block hash, state diff commitment)
</blockquote></details>

I guess that means the type is ok - resolving

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/191)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ShahakShama and @yair-starkware)

___
*[`src/state.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/191#-NsrvKLWEaQNLRli0BSa:-NsrvKLWEaQNLRli0BSb:b-d6325c) ([raw file](https://github.com/starkware-libs/starknet-api/blob/be3eb91a550748694d982980c25e4fe11e2c9ad6/src/state.rs#L88)):*
> ```XML
>     }
> 
>     #[allow(clippy::len_without_is_empty)]
> ```

why not just implement is_empty?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/191)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`src/state.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/191#-NsrvKLWEaQNLRli0BSa:-NsrvjSjDEJ76ghJWAr5:b-djps70) ([raw file](https://github.com/starkware-libs/starknet-api/blob/be3eb91a550748694d982980c25e4fe11e2c9ad6/src/state.rs#L88)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why not just implement is_empty?
</blockquote></details>


I don't need it, and it's not clear when the state diff is empty and when it is not

**Pull request merged**
