### PR TITLE
chore: derive enum-iter for builtin enum

### PR DESCRIPTION
**Pull request by ArniStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/290)

### CODE REVIEW

**Comment by ArniStarkware** [comment]
Used here: https://reviewable.io/reviews/starkware-libs/mempool/319#-O0dQfSM82y-CzMbpSck

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/290)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`src/transaction.rs` line 946 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/290#-O0meCBL7A0TfOHb1BTr:-O0meCBL7A0TfOHb1BTs:b7tcf7w) ([raw file](https://github.com/starkware-libs/starknet-api/blob/12faa3086526ade572013966e7f43ff870841349/src/transaction.rs#L946)):*
> ```XML
>     #[serde(rename = "keccak_builtin_applications")]
>     Keccak,
> }
> ```

Changed the order to match: the starknet OS: See: https://github.com/starkware-industries/starkware/blob/2ab0987978309566f8b562768494daede23a9b26/src/starkware/starknet/core/os/builtins.cairo#L16C1-L27C2



_Code quote:_
```XML
pub enum Builtin {
    #[serde(rename = "pedersen_builtin_applications")]
    Pedersen,
    #[serde(rename = "range_check_builtin_applications")]
    RangeCheck,
    #[serde(rename = "ecdsa_builtin_applications")]
    Ecdsa,
    #[serde(rename = "bitwise_builtin_applications")]
    Bitwise,
    #[serde(rename = "ec_op_builtin_applications")]
    EcOp,
    #[serde(rename = "poseidon_builtin_applications")]
    Poseidon,
    #[serde(rename = "segment_arena_builtin")]
    SegmentArena,
    #[serde(rename = "keccak_builtin_applications")]
    Keccak,
}
```

**Review by Yael-Starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/290)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by yair-starkware — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/290#-:-O0ijd_h9yW97hwklmPp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`src/transaction.rs` line 934 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/290#-O0nevo64thxbI4rXpPk:-O0nevo73Hu594R2PIBN:b-8d5bjq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cefe30c802b52e55eaa0b0b5f9f6ae78b1ed00d3/src/transaction.rs#L934)):*
> ```XML
> /// The order of the builtins in this enum is important for EnumIter.
> /// This is the order of builtins the Starknet OS expects.
> #[derive(Clone, Debug, Deserialize, EnumIter, Eq, Hash, PartialEq, Serialize)]
> ```

Changing the order requires  a storage migration in Papyrus
@dan-starkware

**Comment by yair-starkware** [comment]
*[`src/transaction.rs` line 934 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/290#-O0nevo64thxbI4rXpPk:-O0ng-LHDKsegStWN0EQ:b7tiqlx) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cefe30c802b52e55eaa0b0b5f9f6ae78b1ed00d3/src/transaction.rs#L934)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Changing the order requires  a storage migration in Papyrus
@dan-starkware
</blockquote></details>

Another option is to add a function that will return the order of the builtin

**Comment by dan-starkware** [comment]
We are during a major storage version change as it is. So if this can be merged into papyrus before the 13.2 corresponding version we should be fine

**Review by ArniStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/290)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @Yael-Starkware, and @yair-starkware)

___
*[`src/transaction.rs` line 934 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/290#-O0nevo64thxbI4rXpPk:-O0npAfu1eAq8eTFz1qS:b-an7joz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cefe30c802b52e55eaa0b0b5f9f6ae78b1ed00d3/src/transaction.rs#L934)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Another option is to add a function that will return the order of the builtin
</blockquote></details>

Done.
Even though @dan-starkware does not seem to mind.

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/290#-:-O0rhnOu3ok_62UjQqUy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @Yael-Starkware)

**Review by yair-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/290)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @Yael-Starkware)

**Pull request merged**
