### PR TITLE
Adding new structs for transaction V3.

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 392 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ncw6Fa34CnmEXCu3L3Q:-Ncw6Fa34CnmEXCu3L3R:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L392)):*
> ```XML
> pub struct EventIndexInTransactionOutput(pub usize);
> 
> /// A Tip.
> ```





_Suggestion:_
```XML
/// Transaction fee tip.
```
___
*[`src/transaction.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcvdhRs3h670V7VMano:-NcvdhRt-ygXzmAdNCXY:b-di46sl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L396)):*
> ```XML
>     Clone, Copy, Debug, Default, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize,
> )]
> #[serde(from = "PrefixedBytesAsHex<8_usize>", into = "PrefixedBytesAsHex<8_usize>")]
> ```

What does this line mean? Both of them are the same class.



_Code quote:_
```XML
#[serde(from = "PrefixedBytesAsHex<8_usize>", into = "PrefixedBytesAsHex<8_usize>")]
```
___
*[`src/transaction.rs` line 400 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ncw6JcfAWaEvA3YFgx1:-Ncw6JcfAWaEvA3YFgx2:bp9mwzr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L400)):*
> ```XML
> 
> impl From<PrefixedBytesAsHex<8_usize>> for Tip {
>     fn from(val: PrefixedBytesAsHex<8_usize>) -> Self {
> ```

Also in other locations.



_Suggestion:_
```XML
value
```
___
*[`src/transaction.rs` line 417 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ncw6N-a1wYTtaKC0Yac:-Ncw6N-a1wYTtaKC0Yad:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L417)):*
> ```XML
> }
> 
> /// A Resources.
> ```





_Suggestion:_
```XML
Execution resource.
```
___
*[`src/transaction.rs` line 424 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ncw6QMG0MAWxvh-ZcNi:-Ncw6QMG0MAWxvh-ZcNj:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L424)):*
> ```XML
> }
> 
> /// A ResourceBounds.
> ```





_Suggestion:_
```XML
/// Fee bounds for an execution resource.
```
___
*[`src/transaction.rs` line 433 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ncw6boX0MBFOv2rff5W:-Ncw6boX0MBFOv2rff5X:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L433)):*
> ```XML
> }
> 
> /// A ResourcesBounds.
> ```





_Suggestion:_
```XML
A mapping from execution resources to their corresponding fee bounds.
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`src/transaction.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcvdhRs3h670V7VMano:-NcwF-co0sn-TemlVTli:b-j6q2q9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L396)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does this line mean? Both of them are the same class.
</blockquote></details>

It means that serialization is from the `8_usize` prefixed as hex to `Tip`, and the deserialization is from `Tip` to `8_usize` prefixed as hex, where "from type" is the same as "into type".
It’s used in the same way as the "old” `Fee` struct (with 16_usize instead of 8_usize):



_Code quote:_
```XML
#[serde(from = "PrefixedBytesAsHex<16_usize>", into = "PrefixedBytesAsHex<16_usize>")]
pub struct Fee(pub u128);
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`src/transaction.rs` line 417 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcwKPgl60lH1wyPOGbZ:-Ncy4sQ5CqH2A7_v11_y:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b4453786eed890a1c3e6bd1edddc8cceae27ec35/src/transaction.rs#L417)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Fix? You have an offset with the documentations.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcvdhRs3h670V7VMano:-Nd-N0ZG-Se-2ZFR_Orj:b8hmvkg) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L396)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It means that serialization is from the `8_usize` prefixed as hex to `Tip`, and the deserialization is from `Tip` to `8_usize` prefixed as hex, where "from type" is the same as "into type".
It’s used in the same way as the "old” `Fee` struct (with 16_usize instead of 8_usize):
</blockquote></details>

How come it's the same type on both directions?

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcvdhRs3h670V7VMano:-Nd-nkNvBhuhZGta529w:b76vg7r) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L396)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come it's the same type on both directions?
</blockquote></details>

IIUC, this is the natural choice. If it was different, then I would ask, "How come it's a different type in the serialization direction and in the deserialization direction?"
I.e., this is the default behavior.
Maybe @dan-starkware can correct me if I'm wrong.

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcvdhRs3h670V7VMano:-Nd-vJiw-nw8N1YUdHVs:b-sp8d4g) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L396)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

IIUC, this is the natural choice. If it was different, then I would ask, "How come it's a different type in the serialization direction and in the deserialization direction?"
I.e., this is the default behavior.
Maybe @dan-starkware can correct me if I'm wrong.
</blockquote></details>

Talked with @dan-starkware and confirmed what I said.
Our "benchmark" is the feeder gateway's output types. We want to behave like the feeder for other nodes, that is, if some node asks for the `Tip` then we want to serialize it and send it exactly as we got it from the feeder. We know that the feeder sends a serialized prefixed hex format of 8 bytes so this is the `from` for deserialization.

If the types are different then there should be a very good reason for that.

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-:-Nd0T1D23pDVOrRWS0in:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcvdhRs3h670V7VMano:-Nd0SvCr3mr2wN8kOB3n:bmvjaao) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L396)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Talked with @dan-starkware and confirmed what I said.
Our "benchmark" is the feeder gateway's output types. We want to behave like the feeder for other nodes, that is, if some node asks for the `Tip` then we want to serialize it and send it exactly as we got it from the feeder. We know that the feeder sends a serialized prefixed hex format of 8 bytes so this is the `from` for deserialization.

If the types are different then there should be a very good reason for that.
</blockquote></details>

Are you sure thr Feeder serializes with `0x`?

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 396 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NcvdhRs3h670V7VMano:-NdLxNbZ64aLQPZWg2Ud:b-vpz43i) ([raw file](https://github.com/starkware-libs/starknet-api/blob/efbc7d54d5842632e09e0304456e789ada985968/src/transaction.rs#L396)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you sure thr Feeder serializes with `0x`?
</blockquote></details>

```
TipField = RangeValidatedField(
lower_bound=constants.TIP_LOWER_BOUND,
upper_bound=constants.TIP_UPPER_BOUND,
name="Tip",
error_code=StarknetErrorCode.OUT_OF_RANGE_TIP,
formatter=hex,
)
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 437 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndsw_co2e0F_x7KkGiZ:-Ndsw_co2e0F_x7KkGi_:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1bf3dd050bd9b92acfb0087e7cf0ee06451cd401/src/transaction.rs#L437)):*
> ```XML
> pub struct ResourcesBounds(pub BTreeMap<Resource, ResourceBounds>);
> 
> /// A Paymaster, entities other than the transaction sender to pay the transaction fees.
> ```





_Suggestion:_
```XML
A paymaster, an entity
```
___
*[`src/transaction.rs` line 441 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NdswccDDmYXN8EnKUTD:-NdswccDDmYXN8EnKUTE:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1bf3dd050bd9b92acfb0087e7cf0ee06451cd401/src/transaction.rs#L441)):*
> ```XML
>     Clone, Copy, Debug, Default, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize,
> )]
> pub struct PaymasterAddress(pub StarkFelt);
> ```





_Suggestion:_
```XML
ContractAddress
```
___
*[`src/transaction.rs` line 444 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndswf8m4PzBFSf-8b7Z:-Ndswf8n58CfVb7sL4pU:b-ngywnd) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1bf3dd050bd9b92acfb0087e7cf0ee06451cd401/src/transaction.rs#L444)):*
> ```XML
> 
> /// An account initialization code. Enabling deploying an account without a DeployAccount
> /// transaction.
> ```

Please take [the documentation from the Python repo.](https://github.com/starkware-industries/starkware/blob/d0ad156cd07804b0a8e463ff1746065c16ee9abb/src/starkware/starknet/services/api/gateway/account_transaction.py#L129-L130).



_Code quote:_
```XML
/// An account initialization code. Enabling deploying an account without a DeployAccount
/// transaction.
```
___
*[`src/transaction.rs` line 446 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NdswVU80hyyJcNlUAD1:-NdswVU9-8_ErjYJ1fTW:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/1bf3dd050bd9b92acfb0087e7cf0ee06451cd401/src/transaction.rs#L446)):*
> ```XML
> /// transaction.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub struct AccountInitCode(pub Vec<StarkFelt>);
> ```





_Suggestion:_
```XML
AccountDeploymentData
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`src/transaction.rs` line 441 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NdswccDDmYXN8EnKUTD:-NdsyNAdBXQ-2Z50Ixrz:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b943f5622fb4e9a319a676720cfc30dbe7ac8489/src/transaction.rs#L441)):*
> ```XML
>     Clone, Copy, Debug, Default, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize,
> )]
> pub struct PaymasterAddress(pub StarkFelt);
> ```

Done.
___
*[`src/transaction.rs` line 444 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndswf8m4PzBFSf-8b7Z:-NdsyXm72I0wM2TIp5OA:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b943f5622fb4e9a319a676720cfc30dbe7ac8489/src/transaction.rs#L444)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please take [the documentation from the Python repo.](https://github.com/starkware-industries/starkware/blob/d0ad156cd07804b0a8e463ff1746065c16ee9abb/src/starkware/starknet/services/api/gateway/account_transaction.py#L129-L130).
</blockquote></details>

Done.
___
*[`src/transaction.rs` line 446 at r4](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-NdswVU80hyyJcNlUAD1:-NdsyZen5rc97kQfycHa:b-6h1dvc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b943f5622fb4e9a319a676720cfc30dbe7ac8489/src/transaction.rs#L446)):*
> ```XML
> /// transaction.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> pub struct AccountInitCode(pub Vec<StarkFelt>);
> ```

Done.
Notice that they named the tx's field `account_init_code` in the snip.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @MohammadNassar1)

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

___
*[`src/transaction.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndxu_hZAggg_Zu2eYXW:-Ndxu_hZAggg_Zu2eYXX:b-jh1dns) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4f82451f10aecf8ee04e31b6ac7629d8b2555243/src/transaction.rs#L423)):*
> ```XML
>     L2Gas,
> }
> ```

Please rename `ResourcesBounds` (note the plural) to `ResourceBoundsMapping`, so it's less confusing. Please make `Resource` and `ResourceBounds` (note the singular) non-`pub`lic, if possible. The mapping type is the one that should be used in the transaction structs, and the single `Resource` change should be reverted.

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dan-starkware, @elintul, and @MohammadNassar1)

___
*[`src/transaction.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndxu_hZAggg_Zu2eYXW:-NdygP350vytXXf27ai0:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4f82451f10aecf8ee04e31b6ac7629d8b2555243/src/transaction.rs#L423)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please rename `ResourcesBounds` (note the plural) to `ResourceBoundsMapping`, so it's less confusing. Please make `Resource` and `ResourceBounds` (note the singular) non-`pub`lic, if possible. The mapping type is the one that should be used in the transaction structs, and the single `Resource` change should be reverted.
</blockquote></details>

Done.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, and @MohammadNassar1)

___
*[`src/transaction.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndxu_hZAggg_Zu2eYXW:-NdyvxWnEq-fd5F8bE-e:b-beauvm) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4f82451f10aecf8ee04e31b6ac7629d8b2555243/src/transaction.rs#L423)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can the first two ones become non-`pub`lic?

**Comment by barak-b-starkware** [comment]
*[`src/transaction.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndxu_hZAggg_Zu2eYXW:-Ndz5yXL7FZkfHUg8iYA:bzagijh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4f82451f10aecf8ee04e31b6ac7629d8b2555243/src/transaction.rs#L423)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can the first two ones become non-`pub`lic?
</blockquote></details>

I don't think so because we need to add them to papyrus storage so it could serialize them or something like that, but I'll check it when I reach there.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndxu_hZAggg_Zu2eYXW:-Ndz7v9k5kfowxZocsgb:b-ucfknh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4f82451f10aecf8ee04e31b6ac7629d8b2555243/src/transaction.rs#L423)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I don't think so because we need to add them to papyrus storage so it could serialize them or something like that, but I'll check it when I reach there.
</blockquote></details>

Thanks!

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndxu_hZAggg_Zu2eYXW:-Ne-t-l60sANLIYI2RT9:b-of02gc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4f82451f10aecf8ee04e31b6ac7629d8b2555243/src/transaction.rs#L423)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

If we remove the `pub` definitions from `Resource` and `ResourceBounds`, we can't do the quoted code (line 435) because of the `pub` inside the parentheses.
In some places, we use `resource_bounds_mapping.0`, so we need the `BTreeMap` to be public.



_Code quote:_
```XML
pub struct ResourceBoundsMapping(pub BTreeMap<Resource, ResourceBounds>);
```

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @MohammadNassar1)

___
*[`src/transaction.rs` line 423 at r6](https://reviewable.io/reviews/starkware-libs/starknet-api/124#-Ndxu_hZAggg_Zu2eYXW:-Ne14j-t06pWEy3qj10i:b-xy13tb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4f82451f10aecf8ee04e31b6ac7629d8b2555243/src/transaction.rs#L423)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

If we remove the `pub` definitions from `Resource` and `ResourceBounds`, we can't do the quoted code (line 435) because of the `pub` inside the parentheses.
In some places, we use `resource_bounds_mapping.0`, so we need the `BTreeMap` to be public.
</blockquote></details>

Thanks. :)

**Comment by barak-b-starkware** [comment]
Merged in [this](https://github.com/starkware-libs/starknet-api/pull/135) PR.

**Pull request closed without merging**
