### PR TITLE
test(transaction): test external transaction

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/224)

### CODE REVIEW

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/224)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-NucfRD_3RObf78OoVGT:-NucfRD_3RObf78OoVGU:b-2mnihe) (no related file):*
I will change it to use non-trivial values.

___

**Review by giladchase — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/224)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`src/external_transaction_test.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-Nus5tPB-DsmK0501q8X:-Nus5tPB-DsmK0501q8Y:b-u2ol48) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51ca988d14f393d4a098a35deb85593f427147be/src/external_transaction_test.rs#L24)):*
> ```XML
>     ResourceBoundsMapping(map)
> }
> ```

This is hitting a previous discussion we had (I'm not sure if you were present) about reusing testing fixtures between SNAPI/blockifier/papyrus.

I'm assuming this test util duplicates an existing testing util in blockifier?
___
*[`src/external_transaction_test.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-Nus7PuODYBN2kcUblmt:-Nus7PuODYBN2kcUblmu:bn1qaaz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51ca988d14f393d4a098a35deb85593f427147be/src/external_transaction_test.rs#L86)):*
> ```XML
>         ),
>         ("InvokeTransactionV3", ExternalTransaction::Invoke(create_invoke_v3())),
>     ];
> ```

Use `rstest` test cases, and remove the `name` part, it can be encoded in the rstest case



_Code quote:_
```XML
    let test_cases: Vec<(&str, ExternalTransaction)> = vec![
        ("DeclareTransactionV3", ExternalTransaction::Declare(create_declare_v3())),
        (
            "DeployAccountTransactionV3",
            ExternalTransaction::DeployAccount(create_deploy_account_v3()),
        ),
        ("InvokeTransactionV3", ExternalTransaction::Invoke(create_invoke_v3())),
    ];
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/224)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`src/external_transaction_test.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-Nus5tPB-DsmK0501q8X:-NusbfiU7yJqc5PJo0GW:b-q7x406) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51ca988d14f393d4a098a35deb85593f427147be/src/external_transaction_test.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This is hitting a previous discussion we had (I'm not sure if you were present) about reusing testing fixtures between SNAPI/blockifier/papyrus.

I'm assuming this test util duplicates an existing testing util in blockifier?
</blockquote></details>

I didn't copy this util from another repo. Not sure if we have a similar util in Blockifier.
What was the conclusion of the discussion?
___
*[`src/external_transaction_test.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-Nus7PuODYBN2kcUblmt:-NuwW01V3TdeqFYfFh4Y:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51ca988d14f393d4a098a35deb85593f427147be/src/external_transaction_test.rs#L86)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Use `rstest` test cases, and remove the `name` part, it can be encoded in the rstest case
</blockquote></details>

Done.

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-:-NuxN5DOALyHHS-z9S69:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`src/external_transaction_test.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/224#-Nus5tPB-DsmK0501q8X:-NuxKHfx-2UiQ1H367JY:b-wwtssw) ([raw file](https://github.com/starkware-libs/starknet-api/blob/51ca988d14f393d4a098a35deb85593f427147be/src/external_transaction_test.rs#L24)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I didn't copy this util from another repo. Not sure if we have a similar util in Blockifier.
What was the conclusion of the discussion?
</blockquote></details>

We have these in the blockifier, but let's duplicate for now, to not block.
There's already a ticket.

**Comment by MohammadNassar1** [comment]
Reopen the PR

**Comment by MohammadNassar1** [comment]
trying to re-open

**Pull request merged**
