### PR TITLE
feat: concat_counts into a single felt

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`src/block_hash/block_hash_calculator.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRTkpHBGUpNcgc3IUy:-NxRTkpHBGUpNcgc3IUz:bbl7t2g) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e60bb7a266a912ae7db872cdb743a3c2968ffa82/src/block_hash/block_hash_calculator.rs#L1)):*
> ```XML
> use crate::data_availability::L1DataAvailabilityMode;
> ```

Rename this file to util
___
*[`src/block_hash/block_hash_calculator.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRVFct2ZLDSSfJjPjy:-NxRVFct2ZLDSSfJjPjz:b-pi5m5e) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e60bb7a266a912ae7db872cdb743a3c2968ffa82/src/block_hash/block_hash_calculator.rs#L37)):*
> ```XML
> fn to_64_bits(num: usize, error_message: String) -> Result<[u8; 8], StarknetApiError> {
>     let sized_transaction_count: u64 =
>         num.try_into().map_err(|_| StarknetApiError::OutOfRange { string: error_message })?;
> ```

usize to u64 will always succeed on almost all computers. You can use expect instead of map_err
___
*[`src/block_hash/block_hash_calculator_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRTsH8CFf3VXa8r8Ka:-NxRTsH8CFf3VXa8r8Kb:bt166im) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e60bb7a266a912ae7db872cdb743a3c2968ffa82/src/block_hash/block_hash_calculator_test.rs#L1)):*
> ```XML
> use super::concat_counts;
> ```

And this to util_test

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`src/block_hash/block_hash_calculator.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRTkpHBGUpNcgc3IUy:-NxRVq7h2tQ3e2HcgBIk:b-sikxdw) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e60bb7a266a912ae7db872cdb743a3c2968ffa82/src/block_hash/block_hash_calculator.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Rename this file to util
</blockquote></details>

I plan to add `fn calculate_block_hash` to this file in the next PR.
___
*[`src/block_hash/block_hash_calculator.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRVFct2ZLDSSfJjPjy:-NxRZ8-w22Klw5wkkOhs:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e60bb7a266a912ae7db872cdb743a3c2968ffa82/src/block_hash/block_hash_calculator.rs#L37)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

usize to u64 will always succeed on almost all computers. You can use expect instead of map_err
</blockquote></details>

Done.
___
*[`src/block_hash/block_hash_calculator_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRTsH8CFf3VXa8r8Ka:-NxRZCeP-qUscccnTOFD:b-ya81ng) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e60bb7a266a912ae7db872cdb743a3c2968ffa82/src/block_hash/block_hash_calculator_test.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

And this to util_test
</blockquote></details>

Same as above

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-:-NxRZkrYCwQObO6pG8vb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`src/block_hash/block_hash_calculator.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRZoQH-J2jRiSuL2N6:-NxRZoQH-J2jRiSuL2N7:bj0hmuo) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3533d8c88b6136e212b13608bda3c225152e5cdb/src/block_hash/block_hash_calculator.rs#L19)):*
> ```XML
>     state_diff_length: usize,
>     l1_data_availability_mode: L1DataAvailabilityMode,
> ) -> Result<StarkFelt, StarknetApiError> {
> ```

Change the return type

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`src/block_hash/block_hash_calculator.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRZoQH-J2jRiSuL2N6:-NxR_Zik2hLJL8HLSQDL:bie5mpm) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3533d8c88b6136e212b13608bda3c225152e5cdb/src/block_hash/block_hash_calculator.rs#L19)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change the return type
</blockquote></details>

This Result comes from the new StrakFelt.
IMO `new_unchecked` is fine here.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`src/block_hash/block_hash_calculator.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/247#-NxRZoQH-J2jRiSuL2N6:-NxRa1Mx1L6vSfJ7ihpV:b7fkmjz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3533d8c88b6136e212b13608bda3c225152e5cdb/src/block_hash/block_hash_calculator.rs#L19)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

This Result comes from the new StrakFelt.
IMO `new_unchecked` is fine here.
</blockquote></details>

I agree with you. use new_unchecked

**Review by ShahakShama — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/247)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
