### PR TITLE
Remove implementations of defaults

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/11)

### CODE REVIEW

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/11#-:-NK8qFyaCsXVdG4ZJj6F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by giladchase — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/11#-:-NKCw4K4BKx-mlH0NwK5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by anatgstarkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/11#-:-NKgERJE4nwT145JpUeV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
