### PR TITLE
feat: implement event hash

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)

### CODE REVIEW

**Review by Yoni-Starkware — COMMENTED** [review]
Note that the old block hash should be implemented somewhere in papyrus

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-:-Nu0X0Q-2WRahr3ysSvL:b-g890ir)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @noaov1)

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @ShahakShama)

___
*[`src/block_hash.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nu0-_rC0POaKFEqGVaA:-Nu2Ufqu6QVhgbgmXdpG:bht2ehi) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ca9c701e886ca24720ebcc372cb7e9afd9ff7095/src/block_hash.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

(blocking self) replace this crate's `pedersen_hash` directly (in a previous PR; maybe need to implement `hash_array` as well)
</blockquote></details>

I think we should use Poseidon whenever we can now. Right @ShahakShama?

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`src/block_hash.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nu0-_rC0POaKFEqGVaA:-Nu2skW15pWnpwEKri4Y:b-9sf4px) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ca9c701e886ca24720ebcc372cb7e9afd9ff7095/src/block_hash.rs#L6)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think we should use Poseidon whenever we can now. Right @ShahakShama?
</blockquote></details>

It depends if the goal of this PR is to implement the new hash that will appear from 0.13.2 or the current hash

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`src/block_hash.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nu0-_rC0POaKFEqGVaA:-Nu2suYD87edYzqIhH_i:b1kkijm) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ca9c701e886ca24720ebcc372cb7e9afd9ff7095/src/block_hash.rs#L6)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

It depends if the goal of this PR is to implement the new hash that will appear from 0.13.2 or the current hash
</blockquote></details>

If it's the former, then that hash is not final yet, and we should advance finalizing it if we want to implement it already

**Review by ShahakShama — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`src/block_hash.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva2E5D9DJ-duGYXGGc:-Nva2E5D9DJ-duGYXGGd:bl1cxho) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L1)):*
> ```XML
> #[cfg(test)]
> ```

Consider making block_hash a directory with submodule for each subcomponent that has a hash function (event, transaction, class, state_diff)
___
*[`src/block_hash.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva2YGSDfvY6aGVGhgV:-Nva2YGSDfvY6aGVGhgW:b-lnxtvi) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L10)):*
> ```XML
> use crate::transaction::{Event, TransactionHash};
> 
> pub fn calculate_event_hash(event: &Event, tx_hash: &TransactionHash) -> PoseidonHash {
> ```

tx_hash -> transaction_hash
___
*[`src/block_hash.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva0k1ECHgVZAeuxo8Q:-Nva0k1ECHgVZAeuxo8R:b8kpoun) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L11)):*
> ```XML
> 
> pub fn calculate_event_hash(event: &Event, tx_hash: &TransactionHash) -> PoseidonHash {
>     // Poseidon(
> ```

Maybe put this above the function? It looks like an erased code that you want to leave around just in case
___
*[`src/block_hash.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva2dHF3fSolLi0Yjey:-Nva2dHF3fSolLi0Yjez:bxpoq6m) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L18)):*
> ```XML
>     poseidon_hash_array(
>         &[
>             &[*event.from_address.0.key(), tx_hash.0, Felt::from(event.content.keys.len()).into()],
> ```

Consider adding a utility function for hashing an array that first puts the length and then the array itself

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`src/block_hash.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva47Vn4wZ9ZjQJTbSu:-Nva47Vn4wZ9ZjQJTbSv:b-gai4c9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L20)):*
> ```XML
>             &[*event.from_address.0.key(), tx_hash.0, Felt::from(event.content.keys.len()).into()],
>             event.content.keys.iter().map(|k| k.0).collect::<Vec<_>>().as_slice(),
>             &[Felt::from(event.content.data.0.len()).into()],
> ```

Can you define a utility for this? (converting len to Felt)
I guess we will see it a lot



_Code quote:_
```XML
Felt::from(event.content.data.0.len()).into()
```
___
*[`src/block_hash.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva3njg2Xe93Y3xZ403:-Nva3njhAS9vNDnFVlZf:b-fghkpu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L23)):*
> ```XML
>             event.content.data.0.as_slice(),
>         ]
>         .concat(),
> ```

Extract these out for readability 
```rust
        let keys = event.content.keys.iter().map(|k| k.0).collect::<Vec<_>>();
        let data = event.content.data.0;
```



_Code quote:_
```XML
    poseidon_hash_array(
        &[
            &[*event.from_address.0.key(), tx_hash.0, Felt::from(event.content.keys.len()).into()],
            event.content.keys.iter().map(|k| k.0).collect::<Vec<_>>().as_slice(),
            &[Felt::from(event.content.data.0.len()).into()],
            event.content.data.0.as_slice(),
        ]
        .concat(),
```

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @ShahakShama)

___
*[`src/block_hash_test.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva6KKR2Mbmt1zZnjIr:-Nva6KKR2Mbmt1zZnjIs:bb76mu4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash_test.rs#L13)):*
> ```XML
>         content: EventContent {
>             keys: [2_u8, 3].iter().map(|key| EventKey(stark_felt!(*key))).collect(),
>             data: EventData([4_u8, 5, 6].into_iter().map(StarkFelt::from).collect()),
> ```

Why?



_Suggestion:_
```XML
        from_address: contract_address!(10),
        content: EventContent {
            keys: [2, 3].iter().map(|key| EventKey(stark_felt!(*key))).collect(),
            data: EventData([4, 5, 6].into_iter().map(StarkFelt::from).collect()),
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`src/block_hash.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva47Vn4wZ9ZjQJTbSu:-Nva9yEMBcagQyNs8G4e:b-m5swim) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L20)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you define a utility for this? (converting len to Felt)
I guess we will see it a lot
</blockquote></details>

added `impl From<usize> for StarkFelt`
___
*[`src/block_hash.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva3njg2Xe93Y3xZ403:-NvaA97ADd9cQBNDs2N2:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash.rs#L23)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Extract these out for readability 
```rust
        let keys = event.content.keys.iter().map(|k| k.0).collect::<Vec<_>>();
        let data = event.content.data.0;
```
</blockquote></details>

Done.
___
*[`src/block_hash_test.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-Nva6KKR2Mbmt1zZnjIr:-NvaAGH92zoM05-Pn49E:bmcew2r) ([raw file](https://github.com/starkware-libs/starknet-api/blob/75d44da2536b9719bcff1e6e2415e366e2c53c11/src/block_hash_test.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

no; compiler auto-deduces type as `i32`, and `StarkFelt::from` is not implemented for this type.
`StarkFelt::from` is implemented for all unsigned int types, so the compiler can't guess which integer type is correct...
by providing explicit type we mitigate these errors.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @ShahakShama)

___
*[`src/block_hash/utils.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-NvaC7bn2BD_0B73E9M7:-NvaC7bn2BD_0B73E9M8:b9dtuys) ([raw file](https://github.com/starkware-libs/starknet-api/blob/6c3a696c6c9cdb9aedc1299be69b991c4574446a/src/block_hash/utils.rs#L4)):*
> ```XML
> 
> pub(crate) fn hash_array_preimage(array: &Vec<StarkFelt>) -> Vec<StarkFelt> {
>     [vec![array.len().into()], array.iter().map(|f| *f).collect::<Vec<StarkFelt>>()].concat().into()
> ```

Can you do something simple like clone? (same complexity, right?)



_Code quote:_
```XML
array.iter().map(|f| *f).collect::<Vec<StarkFelt>>()
```

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @noaov1 and @ShahakShama)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-:-NwsEnNb8GRCWwod5zZ3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`src/block_hash/event_hash.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-NwsFJOz-xx8Bj49FqOD:-NwsFJOz-xx8Bj49FqOE:bvqbs2w) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f24badd98371a9ef3a6ccad5220277863f1d6b39/src/block_hash/event_hash.rs#L15)):*
> ```XML
> /// ).
> pub fn calculate_event_hash(event: &Event, transaction_hash: &TransactionHash) -> PoseidonHash {
>     let keys = &event.content.keys.iter().map(|k| k.0).collect::<Vec<_>>();
> ```

Consider changing hash_array_preimage to receive anything that implements IntoIterator instead of Vec and not collecting here

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/206)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @ShahakShama)

___
*[`src/block_hash/event_hash.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/206#-NwsFJOz-xx8Bj49FqOD:-NwsJ2OrAhErrCJNl5rp:b4fnzpr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f24badd98371a9ef3a6ccad5220277863f1d6b39/src/block_hash/event_hash.rs#L15)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider changing hash_array_preimage to receive anything that implements IntoIterator instead of Vec and not collecting here
</blockquote></details>

If `changing hash\_array\_preimage' receives an iterator, it can't take its length first.

**Pull request merged**
