### PR TITLE
feat: make deprecated classes serialization be sorted by keys for has…

### PR DESCRIPTION
**Pull request by yair-starkware**
…h calculation

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/213)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/213)* status: all files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`src/deprecated_contract_class.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3wmJp1g19AAZjtAoH:-Nu45tUt2lq4AsIc8HpF:b-88dm9q) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L30)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Need to make the enum untagged so its serialization will be sorted by key (this is the default behavior of serde for enums)
</blockquote></details>

Make this a comment in the code
___
*[`src/deprecated_contract_class.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3xH8n7X4HpF3ITUux:-Nu45qju-Af9SaZdxlnD:b-88dm9q) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L40)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Arranging the members lexicographic
</blockquote></details>

Make this a comment in the code
___
*[`src/deprecated_contract_class.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3xZyp4Vnjr6-RK4Lg:-Nu45xCR95N7zX0ZiBmW:b-88dm9q) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L113)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Avoiding the use of flatten to control the order of the keys
</blockquote></details>

Make this a comment in the code

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/213)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`src/deprecated_contract_class.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3wmJp1g19AAZjtAoH:-NuJLFc2B1Keve-v1672:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this a comment in the code
</blockquote></details>

Done.
___
*[`src/deprecated_contract_class.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3xH8n7X4HpF3ITUux:-NuJLT7o225HophAA6-G:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L40)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this a comment in the code
</blockquote></details>

Done.
___
*[`src/deprecated_contract_class.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3xZyp4Vnjr6-RK4Lg:-NuJLibF8RK-cMT_7vd3:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L113)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this a comment in the code
</blockquote></details>

Done.

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/213)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`src/deprecated_contract_class.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3wmJp1g19AAZjtAoH:-NuTCIMt0-sqRvT9fZE6:b882msn) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L30)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it the inner serialization of the *AbiEntry struct? If yes, please state that

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/213)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`src/deprecated_contract_class.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-Nu3wmJp1g19AAZjtAoH:-NuTGTGd3vI5YDdQnFPl:bnc96pj) ([raw file](https://github.com/starkware-libs/starknet-api/blob/9f5e30161c380a6aed89863d9c3bdf780f1ca05f/src/deprecated_contract_class.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Is it the inner serialization of the *AbiEntry struct? If yes, please state that
</blockquote></details>

Not sure what you mean. the serialization of the enum is the serialization of the inner sturcts (+ tag, but I marked the enum untagged and stated why)

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/213#-:-NuTH5rfAp6212SI0I8F:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)

**Pull request merged**
