### PR TITLE
Copy ThinSteaDiff from papyrus_storage crate to be used in blockifier crate.

### PR DESCRIPTION
**Pull request by noaov1**
(As a temporary solution)

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)

### CODE REVIEW

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaTVeT9ifthy8SNHs3:-NUaTVeT9ifthy8SNHs4:boxh9tl) (no related file):*
@dan-starkware, is it okay to move instead of copying?

___

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @noaov1)

___
*[`src/state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaXD_p3tKtfvRVxPkZ:-NUaXD_p3tKtfvRVxPk_:b5qvdgu) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a205c22938934d67dc94eb5009e0faace2a18194/src/state.rs#L59)):*
> ```XML
>     pub replaced_classes: IndexMap<ContractAddress, ClassHash>,
> }
> ```

Do we also need the `impl`s?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`src/state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaXD_p3tKtfvRVxPkZ:-NUoc0rj2y31Rm5HOL9i:bdnc3ki) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a205c22938934d67dc94eb5009e0faace2a18194/src/state.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we also need the `impl`s?
</blockquote></details>

If we just copy the structure, then no. But if we move the structure, then yes, because papyrus storage uses it, and we cannot defineit somewhere else:
we cannot define inherent `impl` for a type outside of the crate where the type is defined. 
Similarly for the `From`: only traits defined in the current crate can be implemented for types defined outside of the crate.

**Review by elintul — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @noaov1)

___
*[`src/state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaXD_p3tKtfvRVxPkZ:-NUowSLTDznkx8oMqJOQ:b-8rqghc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a205c22938934d67dc94eb5009e0faace2a18194/src/state.rs#L59)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

If we just copy the structure, then no. But if we move the structure, then yes, because papyrus storage uses it, and we cannot defineit somewhere else:
we cannot define inherent `impl` for a type outside of the crate where the type is defined. 
Similarly for the `From`: only traits defined in the current crate can be implemented for types defined outside of the crate.
</blockquote></details>

Are we going to use those methods in Blockifier?

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @elintul)

___
*[`src/state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaXD_p3tKtfvRVxPkZ:-NUp0a76BbnyeRQ-2Qq_:bezajjq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a205c22938934d67dc94eb5009e0faace2a18194/src/state.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we going to use those methods in Blockifier?
</blockquote></details>

I don't think so

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @noaov1)

___
*[`src/state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaXD_p3tKtfvRVxPkZ:-NUpcWCd-VTc_WzJCilw:b130t0d) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a205c22938934d67dc94eb5009e0faace2a18194/src/state.rs#L59)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't think so
</blockquote></details>

Then let's only copy the struct for now.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @elintul)

___
*[`src/state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaXD_p3tKtfvRVxPkZ:-NUq-q0D4du8_4nSBUtx:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/a205c22938934d67dc94eb5009e0faace2a18194/src/state.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Then let's only copy the struct for now.
</blockquote></details>

Done

**Comment by dan-starkware** [comment]
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@dan-starkware, is it okay to move instead of copying?
</blockquote></details>

WDYM by move?

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-:-NUqKQNoCZ8bbd2ut1ii:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaTVeT9ifthy8SNHs3:-NUqK6iF4rjWLP6HLIZM:bg1xcpb) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

WDYM by move?
</blockquote></details>

Move the definition to SN API and Papyrus uses it from there.
I don't really care how, I only need it in SN API to be able to return to Python all it needs for commitment (`class hash <> casm hash` mapping).

___

**Pull request merged**
