### PR TITLE
feat!: add state diff commitment

### PR DESCRIPTION
**Pull request by yair-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/179)

### CODE REVIEW

**Review by dan-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/179)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ShahakShama)

___
*[`src/block.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/179#-NqvevYb86yWC8vDPjRt:-NqvevYb86yWC8vDPjRu:b8z55gt) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fc11efc447b8e11693cb69b0be6968207eba87ed/src/block.rs#L60)):*
> ```XML
>     // It is an optional field, as it is not included in old blocks.
>     #[serde(skip_serializing)]
>     pub state_diff_hash: Option<StateDiffHash>,
> ```

Consider either moving this into `extra_data` or extract the latter. The latter it is



_Code quote:_
```XML
state_diff_hash: Option<StateDiffHash>,
```
___
*[`src/block.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/179#-Nqve7vd7pAgV_3emywx:-Nqve7vd7pAgV_3emywy:b-ba99ld) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fc11efc447b8e11693cb69b0be6968207eba87ed/src/block.rs#L64)):*
> ```XML
>     // It is an optional field, as it is not included in old blocks.
>     #[serde(skip_serializing)]
>     pub extra_data: Option<HeaderExtraData>,
> ```

Should be flatten



_Code quote:_
```XML
pub extra_data: Option<HeaderExtraData>,
```

**Review by yair-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/179)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)

___
*[`src/block.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/179#-NqvevYb86yWC8vDPjRt:-Nqw1JYN2Y3DdxfhAOz_:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fc11efc447b8e11693cb69b0be6968207eba87ed/src/block.rs#L60)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider either moving this into `extra_data` or extract the latter. The latter it is
</blockquote></details>

Done
___
*[`src/block.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/179#-Nqve7vd7pAgV_3emywx:-Nqw1KKl8qquC9YkCVZZ:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/fc11efc447b8e11693cb69b0be6968207eba87ed/src/block.rs#L64)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Should be flatten
</blockquote></details>

Done

**Review by dan-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/179#-:-NqwEWP0D67vIvcTxcce:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Comment by dan-starkware** [comment]
Please verify the version is > last published (bump if necessary)

**Pull request merged**
