### PR TITLE
feat(transaction): derive  for transaction version wrapper enum types

### PR DESCRIPTION
**Pull request by tdelabro**
It's useful to have this kind of wrapper type implement `Form`

```rust
#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub enum DeclareTransaction {
    V0(DeclareTransactionV0V1),
    V1(DeclareTransactionV0V1),
    V2(DeclareTransactionV2),
}
```

Because V0 and V1 are internally the same types, it is not possible to derive `From` on this enum. Which is a bit weird. Did you consider something like this:
```rust
pub enum DeclareTransaction {
    V0V1(DeclareTransactionV0V1),
    V2(DeclareTransactionV2),
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/48)

### CODE REVIEW

**Comment by tdelabro** [comment]
@yair-starkware I believe you were the one doing those changes. Can you review this PR?

**Review by giladchase — APPROVED** [review]
:lgtm:

RE v0v1, we'll need to look into it separately since (I think) this enum is the only way of distinguishing between v0 and v1 at compile-time. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/48#-:-NTN19s7EgYdotmeI0wF:b-zbrhow)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Comment by tdelabro** [comment]
@giladchase Can we merge?

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/48#-:-NV8WeBrAFbl-5Hbm2QT:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tdelabro)

**Comment by tdelabro** [comment]
@giladchase can you rebase and merge it?

**Review by giladchase — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/48#-:-NVyuQip3uxAJhF8kpJJ:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Review by yair-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/48#-:-NW115Wx22Vv14YwgZwI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tdelabro)

**Pull request merged**
