### PR TITLE
Add a tip getter for internal transaction

### PR DESCRIPTION
**Pull request by ayeletstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/239)

### CODE REVIEW

**Review by MohammadNassar1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/239)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/239)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`src/internal_transaction.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/239#-NwnOOCu7l5WvvEWWBJW:-NwnOOCu7l5WvvEWWBJX:b-t1k0s) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b657844af8d5320ca4284331d29ef9efd438d1a1/src/internal_transaction.rs#L29)):*
> ```XML
>             InternalTransaction::DeployAccount(tx_data) => tx_data.tx.nonce(),
>             InternalTransaction::Invoke(tx_data) => tx_data.tx.nonce(),
>         }
> ```

Same Q here: can we utilize `macro`s to reduce code duplication?

**Review by ayeletstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/239)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

___
*[`src/internal_transaction.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/239#-NwnOOCu7l5WvvEWWBJW:-Nwn_tuFBSwAPeKtc_p4:b-83b7e1) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b657844af8d5320ca4284331d29ef9efd438d1a1/src/internal_transaction.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Same Q here: can we utilize `macro`s to reduce code duplication?
</blockquote></details>

will do in a different PR

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/239#-:-Nwnaxgj572wwXxTmutN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @giladchase)

**Pull request merged**
