### PR TITLE
Refactor: const transaction versions instead of creating them when us…

### PR DESCRIPTION
**Pull request by barak-b-starkware**
…ing TransactionVersion.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/133)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/133#-:-NdxRlz80yb1EoEoZJnE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Comment by barak-b-starkware** [comment]
Merged in [this](https://github.com/starkware-libs/starknet-api/pull/135) PR.

**Pull request closed without merging**
