### PR TITLE
feat: calculate block hash

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`src/block_hash/block_hash_calculator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/248#-NxSG3ZV3Ov3FsZ0sJy3:-NxSG3ZV3Ov3FsZ0sJy4:bu0zhtl) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f1d217be2fdb469d52e599387b9fb0ec1b197be2/src/block_hash/block_hash_calculator.rs#L46)):*
> ```XML
> ///     data_gas_price_wei, data_gas_price_fri, starknet_version, 0, parent_block_hash
> /// ).
> pub fn calculate_block_hash(block_hash_input: &BlockHashInput<'_, '_, '_, '_>) -> BlockHash {
> ```

Why not receive Block?

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`src/block_hash/block_hash_calculator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/248#-NxSG3ZV3Ov3FsZ0sJy3:-NxSNi_TCrkKYTnwx7dM:b-7mrmpz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f1d217be2fdb469d52e599387b9fb0ec1b197be2/src/block_hash/block_hash_calculator.rs#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why not receive Block?
</blockquote></details>

Because Block contains `block_hash` and optional commitments.
Should I define a new struct, BlockWithoutHash?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248#-:-NyuBLmo9gDeJSefsqDX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`src/block_hash/block_hash_calculator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/248#-NxSG3ZV3Ov3FsZ0sJy3:-NyuIMxH2dQzCEG_EWKi:b-ub88vn) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f1d217be2fdb469d52e599387b9fb0ec1b197be2/src/block_hash/block_hash_calculator.rs#L46)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Because Block contains `block_hash` and optional commitments.
Should I define a new struct, BlockWithoutHash?
</blockquote></details>

Yes, I'd rename the current Block to BlockWithCommitments. You can put a TODO for now

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248)* status: all files reviewed, 1 unresolved discussion (waiting on @ShahakShama)

___
*[`src/block_hash/block_hash_calculator.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/248#-NxSG3ZV3Ov3FsZ0sJy3:-NyuJgui03MePGI9-PC2:b-8r2j2y) ([raw file](https://github.com/starkware-libs/starknet-api/blob/f1d217be2fdb469d52e599387b9fb0ec1b197be2/src/block_hash/block_hash_calculator.rs#L46)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Yes, I'd rename the current Block to BlockWithCommitments. You can put a TODO for now
</blockquote></details>

The structure of `Block` should change and contain: `BlockHeader` (currently BlockHeaderWithoutHash), `BlockBody`, `BlockHeaderCommitments` and `BlockHash`.
It's a breaking change that is bigger than a renaming TODO.

**Review by ShahakShama — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
