### PR TITLE
Remove nightly version

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/140)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/140)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, @elintul, and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/140#-Nfps8pnB4cQ4LealuAP:-Nfpyaun9XoCc8wPM64x:b-s7of4v) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

In slack
</blockquote></details>

tl;dr; and if I'm not mistaken,
after this change our toolchain should be on `stable` rust compiler version, not set to some nightly build.
this is required because cairo-compiler repo has deps that break on old compiler versions.

___

**Review by elintul — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/140#-:-Nfq-xNL0tTvfkytyKwc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @dan-starkware, and @giladchase)

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware, @dan-starkware, and @giladchase)

**Review by giladchase — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @dan-starkware)

**Pull request merged**
