### PR TITLE
Add DataAvailabilityMode enum.

### PR DESCRIPTION
**Pull request by barak-b-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)

### CODE REVIEW

**Review by noaov1 — DISMISSED** [review]
As discussed- should also include the implementation of `TryFrom<StarkFelt> for DataAvailabilityMode`.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-:-NcbGTCtAyt_8YrdK-Ey:b135kq7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @dan-starkware, and @noaov1)

___
*[`src/data_availability.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NclktXg11PUks7ogxAY:-NclktXg11PUks7ogxAZ:b-drp2w) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L22)):*
> ```XML
>     fn try_from(felt: StarkFelt) -> Result<Self, Self::Error> {
>         let zero = StarkFelt::from(0_u8);
>         let one = StarkFelt::from(1_u8);
> ```

Are  those variable needed?



_Code quote:_
```XML
        let zero = StarkFelt::from(0_u8);
        let one = StarkFelt::from(1_u8);
```

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`src/data_availability.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpR-RBE9qHYitg9jqZ:-NcpR-RBE9qHYitg9jq_:bbk8lz8) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L9)):*
> ```XML
>     L1 = 0,
>     L2 = 1,
> }
> ```

There is only one `L2` availability mode?



_Code quote:_
```XML
pub enum DataAvailabilityMode {
    L1 = 0,
    L2 = 1,
}
```
___
*[`src/data_availability.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpRC_26uWqDmWUtHAL:-NcpRC_26uWqDmWUtHAM:bj09c3h) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L29)):*
> ```XML
>         } else {
>             Err(DataAvailabilityError::InvalidDataAvailabilityMode { data_availability_mode: felt })
>         }
> ```

match instead?



_Code quote:_
```XML
        if felt == zero {
            Ok(DataAvailabilityMode::L1)
        } else if felt == one {
            Ok(DataAvailabilityMode::L2)
        } else {
            Err(DataAvailabilityError::InvalidDataAvailabilityMode { data_availability_mode: felt })
        }
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`src/data_availability.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NclktXg11PUks7ogxAY:-NcsxMdT0O7xaVg9yZEU:bcdz8gh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L22)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are  those variable needed?
</blockquote></details>

They are not needed. I’ve added them for readability.
Removed.
___
*[`src/data_availability.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpRC_26uWqDmWUtHAL:-Ncsx9Iz9LYGoyGX-vUU:bub91c7) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L29)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

match instead?
</blockquote></details>

I didn’t use the `match` mechanism and preferred the `if...else...` here. I had difficulty using variables in the `match` arms.
I asked @noaov1 and she said it was okay (:
Do you know any better way to handle it?

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul, @EvyatarO, and @noaov1)

___
*[`src/data_availability.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpR-RBE9qHYitg9jqZ:-NcsyW8m8fjrcJu9y36K:b5bji84) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L9)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

There is only one `L2` availability mode?
</blockquote></details>

Currently, this is what @EvyatarO wants.
We seem to have many alternatives “to grow up” with this enum, and that choice is the most general and enabling.
IMO once we’ve agreed on the enum name `DataAvailabilityMode`, it would be easier to change/add/remove the variant names.

**Review by elintul — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @EvyatarO and @noaov1)

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @EvyatarO and @noaov1)

**Review by noaov1 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-:-NcwSZznENQzEwjjsPfo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @EvyatarO)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @EvyatarO)

**Review by dan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @EvyatarO and @noaov1)

___
*[`src/data_availability.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpRC_26uWqDmWUtHAL:-NcwQEAx0derNCjM5b2I:brxk0ud) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L29)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I didn’t use the `match` mechanism and preferred the `if...else...` here. I had difficulty using variables in the `match` arms.
I asked @noaov1 and she said it was okay (:
Do you know any better way to handle it?
</blockquote></details>

Not sure it's better, but something like this should work.

Personally I would change the const `one` function to `pub const ONE: Self = Self::from(1_u8);` , add the same for `ZERO` and use these in the match.



_Code snippet:_
```XML
fn try_from(felt: StarkFelt) -> Result<Self, Self::Error> {
        match felt {
            zero if zero.eq(&StarkFelt::default()) => Ok(DataAvailabilityMode::L1),
            one if one.eq(&StarkFelt::one()) => Ok(DataAvailabilityMode::L1),
            _ => Err(DataAvailabilityError::InvalidDataAvailabilityMode {
                data_availability_mode: felt,
            }),
        }
    }
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @EvyatarO, and @noaov1)

___
*[`src/data_availability.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpRC_26uWqDmWUtHAL:-Ncy3gjvBbekyvkIImDG:bl491qb) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L29)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not sure it's better, but something like this should work.

Personally I would change the const `one` function to `pub const ONE: Self = Self::from(1_u8);` , add the same for `ZERO` and use these in the match.
</blockquote></details>

Nice! thank you!
@noaov1 @elintul WDYT?
We have a convention that we can follow in this case? maybe something specific for the `starknet_api` repo?

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @elintul, and @EvyatarO)

___
*[`src/data_availability.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpRC_26uWqDmWUtHAL:-Nd-8wGRDj3FRPLuuu_g:b-r105jk) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L29)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Nice! thank you!
@noaov1 @elintul WDYT?
We have a convention that we can follow in this case? maybe something specific for the `starknet_api` repo?
</blockquote></details>

Not that I know :)
What is `eq()`? An equality trait of `StarkFelt`?
I wonder if it's more readable :thinking: 
___
*[`src/data_availability.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-Nd-8ZBoCekEYzIRRCaq:-Nd-8ZBoCekEYzIRRCar:b-4czzy9) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2fd8d70de0affefddbb268df30cbd49df4975a0e/src/data_availability.rs#L27)):*
> ```XML
>             Ok(DataAvailabilityMode::L2)
>         } else {
>             Err(DataAvailabilityError::InvalidDataAvailabilityMode { data_availability_mode: felt })
> ```

Why not use `StarknetApiError::OutOfRange`? It seems that all the `TryFrom` implementations use it. 



_Code quote:_
```XML
Err(DataAvailabilityError::InvalidDataAvailabilityMode { data_availability_mode: felt })
```

**Review by barak-b-starkware — COMMENTED** [review]
@Yoni-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-:-Nd-FWymDW4sI9G5vkqW:b-4rx1h1)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @EvyatarO, and @Yoni-Starkware)

**Review by elintul — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @dan-starkware, @EvyatarO, @noaov1, and @Yoni-Starkware)

___
*[`src/data_availability.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpRC_26uWqDmWUtHAL:-Nd-cGA02iJO8-zegV5U:b-ieribx) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L29)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not that I know :)
What is `eq()`? An equality trait of `StarkFelt`?
I wonder if it's more readable :thinking:
</blockquote></details>

How is `pub const ONE: Self = Self::from(1_u8);` possible? `StarkFelt`'s c-tor isn't `const`. Or did you mean it for `DataAvailabilityMode`?

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dan-starkware, @elintul, @EvyatarO, @noaov1, and @Yoni-Starkware)

___
*[`src/data_availability.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NcpRC_26uWqDmWUtHAL:-Nd-uv_D4S-2J1aEaPx-:bd4a9dq) ([raw file](https://github.com/starkware-libs/starknet-api/blob/4bced750c89b720ded1e246fcaaaf8c62672725c/src/data_availability.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How is `pub const ONE: Self = Self::from(1_u8);` possible? `StarkFelt`'s c-tor isn't `const`. Or did you mean it for `DataAvailabilityMode`?
</blockquote></details>

@dan-starkware's suggestion with the constants works and IMO most elegant.
___
*[`src/data_availability.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-Nd-8ZBoCekEYzIRRCaq:-Nd-utS0AjYkxWx9cTQX:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2fd8d70de0affefddbb268df30cbd49df4975a0e/src/data_availability.rs#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not use `StarknetApiError::OutOfRange`? It seems that all the `TryFrom` implementations use it.
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @EvyatarO, @noaov1, and @Yoni-Starkware)

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`src/data_availability.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-Ndt1UHBC_zsAAKWtchj:-Ndt1UHBC_zsAAKWtchk:b-p5rwct) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cce98c2c6e0db24e0b710bce45d07a36c7bc4d63/src/data_availability.rs#L7)):*
> ```XML
> 
> #[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
> pub enum DataAvailabilityMode {
> ```

Isn't `u32` too big?

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`src/data_availability.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-Ndt1UHBC_zsAAKWtchj:-Ndtj8Dy5N2br761thQR:b4i8m9t) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cce98c2c6e0db24e0b710bce45d07a36c7bc4d63/src/data_availability.rs#L7)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't `u32` too big?
</blockquote></details>

It's from the SNIP: `nonce_data_availability_mode: u32`:
https://github.com/EvyatarO/SNIPs/blob/snip-8/SNIPS/snip-8.md
IMO, `u8` should be enough, but I don't know why they wrote `u32`.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`src/data_availability.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-Ndt1UHBC_zsAAKWtchj:-NdxSW-a344lmiNV2XDO:b3dnkxr) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cce98c2c6e0db24e0b710bce45d07a36c7bc4d63/src/data_availability.rs#L7)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It's from the SNIP: `nonce_data_availability_mode: u32`:
https://github.com/EvyatarO/SNIPs/blob/snip-8/SNIPS/snip-8.md
IMO, `u8` should be enough, but I don't know why they wrote `u32`.
</blockquote></details>

`u32` is for all types, here you give this domain to _each variant_.

**Review by elintul — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @Yoni-Starkware)

___
*[`src/data_availability.rs` line 28 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxSg636Fwx8UdpGeEg:-NdxSg636Fwx8UdpGeEh:bzdh2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L28)):*
> ```XML
> impl From<DataAvailabilityMode> for StarkFelt {
>     fn from(data_availability_mode: DataAvailabilityMode) -> StarkFelt {
>         match data_availability_mode {
> ```

Call it `mode`?

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @EvyatarO)

___
*[`src/data_availability.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-Ndt1UHBC_zsAAKWtchj:-NdxsBc00xvXEatGunBG:b-bo0rm1) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cce98c2c6e0db24e0b710bce45d07a36c7bc4d63/src/data_availability.rs#L7)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`u32` is for all types, here you give this domain to _each variant_.
</blockquote></details>

@EvyatarO didn't we say u8?

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @EvyatarO)

___
*[`src/data_availability.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxuFfH1ui_VefzS4RH:-NdxuFfH1ui_VefzS4RI:b84uej4) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L9)):*
> ```XML
> pub enum DataAvailabilityMode {
>     L1(u32),
>     L2(u32),
> ```

Can it be a concrete integer? Like 0 and 1?



_Code quote:_
```XML
    L1(u32),
    L2(u32),
```
___
*[`src/data_availability.rs` line 18 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxuBip8-lWOw19S2Lv:-NdxuBiq3DtBcrtYHCvx:undefined) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L18)):*
> ```XML
>         match felt {
>             StarkFelt::ZERO => Ok(DataAvailabilityMode::L1(0_u32)),
>             StarkFelt::ONE => Ok(DataAvailabilityMode::L2(0_u32)),
> ```





_Suggestion:_
```XML
            StarkFelt::ONE => Ok(DataAvailabilityMode::L2(1_u32)),
```

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @EvyatarO)

___
*[`src/data_availability.rs` line 32 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxvBIG4g-SbCoeU903:-NdxvBIG4g-SbCoeU904:bukt1do) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L32)):*
> ```XML
>             DataAvailabilityMode::L2(version) => {
>                 StarkFelt::from((1_u64 << 32) + u64::from(version))
>             }
> ```

Not sure what's going on



_Code quote:_
```XML
            DataAvailabilityMode::L2(version) => {
                StarkFelt::from((1_u64 << 32) + u64::from(version))
            }
```

**Review by barak-b-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @elintul, @EvyatarO, and @Yoni-Starkware)

___
*[`src/data_availability.rs` line 7 at r7](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-Ndt1UHBC_zsAAKWtchj:-Ndz50Gh-CQV0SZuwgy-:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cce98c2c6e0db24e0b710bce45d07a36c7bc4d63/src/data_availability.rs#L7)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@EvyatarO didn't we say u8?
</blockquote></details>

Done.
___
*[`src/data_availability.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxuFfH1ui_VefzS4RH:-Ndz51xe2p86_1viJNXA:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L9)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can it be a concrete integer? Like 0 and 1?
</blockquote></details>

Done.
___
*[`src/data_availability.rs` line 18 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxuBip8-lWOw19S2Lv:-Ndz53HbA6LQ7YSWfCAF:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L18)):*
> ```XML
>         match felt {
>             StarkFelt::ZERO => Ok(DataAvailabilityMode::L1(0_u32)),
>             StarkFelt::ONE => Ok(DataAvailabilityMode::L2(0_u32)),
> ```

Done.
___
*[`src/data_availability.rs` line 28 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxSg636Fwx8UdpGeEg:-Ndz5EJz8orBMahXIr9Y:bcnxa06) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L28)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Call it `mode`?
</blockquote></details>

I can change it, but then when we call it (if we use `data_availability_mode` var from somewhere) we'll write:
```
StarkFelt::from(mode: data_availability_mode)
```
Instead of:
```
StarkFelt::from(data_availability_mode)
```
WDYT?
___
*[`src/data_availability.rs` line 32 at r9](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-NdxvBIG4g-SbCoeU903:-Ndz5hT11aands9zS_1m:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/3433ba51b27c8a488ae27e82a0ae6365cc1d2a7f/src/data_availability.rs#L32)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not sure what's going on
</blockquote></details>

Done.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @Yoni-Starkware)

**Review by Yoni-Starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 2 files at r7, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123#-:-Ne21RsuAaaxN3Fdh_AK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)

**Pull request closed without merging**
