### PR TITLE
Add test to calculate_contract_address.

### PR DESCRIPTION
**Pull request by noaov1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/22)

### CODE REVIEW

**Review by elintul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-:-NLVX8N98hI3G5iAo-lN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by dan-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/22)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`src/core_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_EPdD3i64W46UMzvw:-NL_EPdEBqlaIYcN6_29:bocemms) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L44)):*
> ```XML
> #[test]
> fn test_calculate_contract_address() {
>     let salt = ContractAddressSalt(stark_felt!(1337));
> ```

How do you decide on default vs. ad hoc values?



_Code quote:_
```XML
    let salt = ContractAddressSalt(stark_felt!(1337));
    let class_hash = ClassHash::default();
```
___
*[`src/core_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_Eg8YECMSgxbFhLvg:-NL_Eg8YECMSgxbFhLvh:bt6dm38) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L63)):*
> ```XML
>         constructor_calldata_hash,
>     ]);
>     let mod_address = FieldElement::from(address) % *L2_ADDRESS_UPPER_BOUND;
> ```

It seems that the test pretty much repeats the function itself. 



_Code quote:_
```XML
    let constructor_calldata_hash = pedersen_hash_array(&constructor_calldata.0);
    let address = pedersen_hash_array(&[
        StarkFelt::try_from(format!("0x{}", hex::encode(CONTRACT_ADDRESS_PREFIX)).as_str())
            .unwrap(),
        *deployer_address.0.key(),
        salt.0,
        class_hash.0,
        constructor_calldata_hash,
    ]);
    let mod_address = FieldElement::from(address) % *L2_ADDRESS_UPPER_BOUND;
    let expected_address = ContractAddress::try_from(StarkFelt::from(mod_address)).unwrap();
```

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`src/core_test.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_EPdD3i64W46UMzvw:-NL_Hu4OBLTRVJbw6QVp:b-c6umev) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L44)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

How do you decide on default vs. ad hoc values?
</blockquote></details>

I was inspired by the python code. It might be better to change the `class_hash` to a different value than the default value (in the python code we calculate it from a `contract_class`defined in the test).
The deployer address has a default value as in `DeployAccount` transaction.  
___
*[`src/core_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_Eg8YECMSgxbFhLvg:-NL_HYQW26w7js7Zjw8Q:b-q9oc4h) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L63)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

It seems that the test pretty much repeats the function itself. 
</blockquote></details>

Correct. This test is meant to ensure that the contract address calculation is done as we expect.

**Review by elintul — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`src/core_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_Eg8YECMSgxbFhLvg:-NL_U1G8CF0EmjQd0xTI:boxirkh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L63)):*
<details><summary><i>Previously, noaov1 wrote…</i></summary><blockquote>

Correct. This test is meant to ensure that the contract address calculation is done as we expect.
</blockquote></details>

What's your suggestion to test it?

**Comment by dan-starkware** [comment]
*[`src/core_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_Eg8YECMSgxbFhLvg:-NL_Wyg49TTOcVfKPC1J:bg5z1gj) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L63)):*
> Correct. This test is meant to ensure that the contract address calculation is done as we expect.

I think this test is meant to ensure that the calculation yields the right output, not how it is done.

IMO using an hard-code value or a different calculation (for example if we have python/cairo implementation) is better for such tests. In this specific case I would use a hard-coded value and explain in a comment how it was derived.

**Review by elintul — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware)

___
*[`src/core_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_Eg8YECMSgxbFhLvg:-NL_vuDQ6QwexkLL1p_-:bl8ctpc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L63)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

> Correct. This test is meant to ensure that the contract address calculation is done as we expect.

I think this test is meant to ensure that the calculation yields the right output, not how it is done.

IMO using an hard-code value or a different calculation (for example if we have python/cairo implementation) is better for such tests. In this specific case I would use a hard-coded value and explain in a comment how it was derived. 
</blockquote></details>

A hard-coded test is harder to maintain, if the calc. changes.
Re another implementation, how would you use it?

**Comment by dan-starkware** [comment]
*[`src/core_test.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/22#-NL_Eg8YECMSgxbFhLvg:-NLaAANH7iUWh1EMXp4b:b-9x9wmz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/2423ffb25847977bebc56dc8205661cb49c96bf7/src/core_test.rs#L63)):*
> if the calc. changes
WDYM?

**Review by dan-starkware — APPROVED** [review]

**Pull request merged**
