### PR TITLE
Impl. `TryFrom<StarkFelt>` for `EthAddress`.

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/13)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/13)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @elintul, and @giladchase)

___
*[`src/transaction.rs` line 251 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/13#-NKNt6v36lWOVtpnp7yT:-NKNt6v36lWOVtpnp7yU:b-e54y00) ([raw file](https://github.com/starkware-libs/starknet-api/blob/89d57097c267673e10cc9b814f049cc99ed7afa5/src/transaction.rs#L251)):*
> ```XML
> pub struct EthAddress(pub H160);
> 
> impl TryFrom<StarkFelt> for EthAddress {
> ```

Maybe this should be in `hash.rs` next to the other conversions?
___
*[`src/transaction.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/13#-NKNpjOH3IeF9q0hcyk4:-NKNpjOH3IeF9q0hcyk5:b-jolw6o) ([raw file](https://github.com/starkware-libs/starknet-api/blob/89d57097c267673e10cc9b814f049cc99ed7afa5/src/transaction.rs#L254)):*
> ```XML
>     type Error = StarknetApiError;
>     fn try_from(felt: StarkFelt) -> Result<Self, Self::Error> {
>         const COMPLIMENT_OF_H160: usize = 32 - H160::len_bytes();
> ```

In this case, you know the sizes in advance (unlike usize which can vary). You can use that to make the code simpler if you'd like:



_Suggestion:_
```XML
        let felt_bytes = felt.bytes();
        if felt_bytes[..12] != [0u8; 12] {
            return Err(StarknetApiError::OutOfRange { string: felt.to_string() });
        }

        Ok(EthAddress(H160::from_slice(&felt_bytes[12..])))
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/13)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @anatgstarkware, and @giladchase)

___
*[`src/transaction.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/13#-NKNpjOH3IeF9q0hcyk4:-NKNwpi50naGdGFHh8xr:b-rbokzv) ([raw file](https://github.com/starkware-libs/starknet-api/blob/89d57097c267673e10cc9b814f049cc99ed7afa5/src/transaction.rs#L254)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

In this case, you know the sizes in advance (unlike usize which can vary). You can use that to make the code simpler if you'd like:
</blockquote></details>

I actually like the split, because it gives me the two numbers in a single action. Also, I prefer to leave the subtraction to get `12` since it explains to the reader where this number is from without runtime cost.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/13#-:-NKO-V_2-kkr2GWzTtcw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @elintul, and @giladchase)

___
*[`src/hash.rs` line 190 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/13#-NKO-BVR55iY1tZhDrs3:-NKO-BVR55iY1tZhDrs4:b-cy1sr2) ([raw file](https://github.com/starkware-libs/starknet-api/blob/e8f045bd991e13cefdaecea4c658be2c73847865/src/hash.rs#L190)):*
> ```XML
> impl TryFrom<StarkFelt> for usize {
>     type Error = StarknetApiError;
>     fn try_from(val: StarkFelt) -> Result<Self, Self::Error> {
> ```

For consistency.



_Suggestion:_
```XML
felt
```
___
*[`src/transaction.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/13#-NKNpjOH3IeF9q0hcyk4:-NKNz3Lh86uIrfKpq8E_:b-q03896) ([raw file](https://github.com/starkware-libs/starknet-api/blob/89d57097c267673e10cc9b814f049cc99ed7afa5/src/transaction.rs#L254)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I actually like the split, because it gives me the two numbers in a single action. Also, I prefer to leave the subtraction to get `12` since it explains to the reader where this number is from without runtime cost. 
</blockquote></details>

In that case, maybe we should also change `32` to `std::mem::size_of::<StarkFelt>()` (also coupling it in case the size changes). If you do, please change it in the `usize` conversion also.

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/13)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @elintul, and @giladchase)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware and @giladchase)

**Pull request merged**
