### PR TITLE
Adding new structs for transaction V3

### PR DESCRIPTION
**Pull request by MohammadNassar1**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)

### CODE REVIEW

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-NafTTSK7yqPD_RCwA6H:-NafTTSK7yqPD_RCwA6I:bacoxtk) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b63273fd6d82c313fb759c620c7f0e720475964b/src/transaction.rs#L389)):*
> ```XML
> /// A Resourcs.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> pub struct ResourceBounds(pub HashMap<String, (u128, u128)>);
> ```

WDYT?
And add the relevant documentation. 



_Suggestion:_
```XML
pub enum Resource {
    L1Gas,
    L2Gas,
}

pub struct ResourceBounds {
    pub max_amount: u128,
    pub max_price_per_unit: u128,
}

pub struct ResourcesBounds(pub HashMap<Resource, (u128, u128)>);
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`src/transaction.rs` line 389 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-NafTTSK7yqPD_RCwA6H:-NafdDdk2orzt0KnFGsM:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/b63273fd6d82c313fb759c620c7f0e720475964b/src/transaction.rs#L389)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYT?
And add the relevant documentation. 
</blockquote></details>

Done.

**Review by noaov1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 403 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-NafsH6p5qLgxa-axnC0:-NafsH6p5qLgxa-axnC1:b3gf9bc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/048a2d3084d81863165199a958fb110850da011f/src/transaction.rs#L403)):*
> ```XML
>     pub max_price_per_unit: u128, /* Specifies the maximum price the user is willing to pay for
>                                    * each resource unit. */
> }
> ```

Can you please write the comment above the field?



_Code quote:_
```XML
    pub max_amount: u128, /* Specifies the maximum amount of each resource allowed for usage
                           * during the execution */
    pub max_price_per_unit: u128, /* Specifies the maximum price the user is willing to pay for
                                   * each resource unit. */
}
```
___
*[`src/transaction.rs` line 427 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-Nak57zK0MCX59IeDdDE:-Nak57zK0MCX59IeDdDF:b-iq7m3f) ([raw file](https://github.com/starkware-libs/starknet-api/blob/048a2d3084d81863165199a958fb110850da011f/src/transaction.rs#L427)):*
> ```XML
>                     if key_cmp != Ordering::Equal {
>                         return key_cmp;
>                     }
> ```

Why do you return the `key_cmp`? What does it mean?



_Code quote:_
```XML
                    if key_cmp != Ordering::Equal {
                        return key_cmp;
                    }
```
___
*[`src/transaction.rs` line 452 at r2](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-Nak6O7D5DBO7uuaZ68w:-Nak6O7D5DBO7uuaZ68x:bwpyogi) ([raw file](https://github.com/starkware-libs/starknet-api/blob/048a2d3084d81863165199a958fb110850da011f/src/transaction.rs#L452)):*
> ```XML
> impl Hash for ResourcesBounds {
>     fn hash<H: Hasher>(&self, state: &mut H) {
>         self.0.len().hash(state);
> ```

Why did you choose to include the length in the hash? (just curious)



_Code quote:_
```XML
self.0.len().hash(state);
```

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-Nap3oGU1uz1D-9xqCP7:-Nap3oGU1uz1D-9xqCP8:bxtub52) ([raw file](https://github.com/starkware-libs/starknet-api/blob/92d21e2ff67024f4ab9ef466517d52fa9748ef92/src/transaction.rs#L3)):*
> ```XML
> use std::collections::BTreeMap;
> use std::fmt::Display;
> use std::hash::Hash;
> ```

Is it needed?



_Code quote:_
```XML
use std::hash::Hash;
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`src/transaction.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-Nap3oGU1uz1D-9xqCP7:-Nap6ObT4ZAB_Fp653Xz:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/92d21e2ff67024f4ab9ef466517d52fa9748ef92/src/transaction.rs#L3)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @MohammadNassar1)

**Review by noaov1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`src/transaction.rs` line 402 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-NaqJkvW7EPXxJe95odH:-NaqJkvW7EPXxJe95odI:ba2sumn) ([raw file](https://github.com/starkware-libs/starknet-api/blob/291a0c127dd3ba51683fb93aa63b6c18a31db3de/src/transaction.rs#L402)):*
> ```XML
> impl From<Tip> for PrefixedBytesAsHex<8_usize> {
>     fn from(tip: Tip) -> Self {
>         Self(tip.0.to_be_bytes())
> ```

Do you know why is it needed?



_Code quote:_
```XML
impl From<PrefixedBytesAsHex<8_usize>> for Tip {
    fn from(val: PrefixedBytesAsHex<8_usize>) -> Self {
        Self(u64::from_be_bytes(val.0))
    }
}

impl From<Tip> for PrefixedBytesAsHex<8_usize> {
    fn from(tip: Tip) -> Self {
        Self(tip.0.to_be_bytes())
```

**Review by MohammadNassar1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/111)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`src/transaction.rs` line 402 at r5](https://reviewable.io/reviews/starkware-libs/starknet-api/111#-NaqJkvW7EPXxJe95odH:-Navj3IJ8o-y_sryYvWr:b9j57dv) ([raw file](https://github.com/starkware-libs/starknet-api/blob/291a0c127dd3ba51683fb93aa63b6c18a31db3de/src/transaction.rs#L402)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do you know why is it needed?
</blockquote></details>

For Deserialize and Serialize traits.

**Pull request merged**
