### PR TITLE
Utility macros for tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/104)

### CODE REVIEW

**Review by yair-starkware — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/104#-:-Na1EeeWEtER5XfiMkbs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

**Review by noaov1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/104)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`src/core.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/104#-Na1GXPG-2JiAWDKa5cu:-Na1GXPG-2JiAWDKa5cv:b5qf77j) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ab59507b64ce2f757aa6f44ebca3e3c2f1f64ec7/src/core.rs#L197)):*
> ```XML
> }
> 
> /// A utility macro to create a [`ClassHash`] from a hex string representation.
> ```

It will also work for expressions of type `u128`, no? (not sure if its the right way to use it though).



_Code quote:_
```XML
/// A utility macro to create a [`ClassHash`] from a hex string representation.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/104)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`src/core.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/104#-Na1GXPG-2JiAWDKa5cu:-Na1ZGDqBqdpXZcac6hR:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ab59507b64ce2f757aa6f44ebca3e3c2f1f64ec7/src/core.rs#L197)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It will also work for expressions of type `u128`, no? (not sure if its the right way to use it though).
</blockquote></details>

Done.

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/104)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @yair-starkware)

___
*[`src/core.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/starknet-api/104#-Na1GXPG-2JiAWDKa5cu:-Na5tusO9sn8eTo8sE4-:b6tgesz) ([raw file](https://github.com/starkware-libs/starknet-api/blob/ab59507b64ce2f757aa6f44ebca3e3c2f1f64ec7/src/core.rs#L197)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In another PR: We should also change it in the `stark_felt` macro.

**Pull request merged**
