### PR TITLE
Move EthAddress to core and serde it without leading zeroes.

### PR DESCRIPTION
**Pull request by DvirYo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/97)

### CODE REVIEW

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/97)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-api/97#-N_UCd0B6G9LdQgRQ9yw:-N_UCd0B6G9LdQgRQ9yx:bxtkclv) (no related file):*
1. I think a better location for that is the core module, what do you think?
2. The serde thing is to make us return EthAddress in the format specified in the spec - without leading zeroes.

___

**Comment by yair-starkware** [comment]
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. I think a better location for that is the core module, what do you think?
2. The serde thing is to make us return EthAddress in the format specified in the spec - without leading zeroes.
</blockquote></details>

Is it breaking the Blockifier code?

**Review by noaov1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/97)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @yair-starkware)

___
*[`src/core.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/97#-NaHNTMs3_6q-6FaRZMR:-NaHNTMs3_6q-6FaRZMS:b-wkbdtc) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cfe90268abe0aa565fe7c9857bcefd9f33a8bf1e/src/core.rs#L222)):*
> ```XML
>     Debug, Copy, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord,
> )]
> #[serde(try_from = "PrefixedBytesAsHex<20_usize>", into = "PrefixedBytesAsHex<20_usize>")]
> ```

Can you please explain how this line leading to the desired result (serialization without leading zeroes)?



_Code quote:_
```XML
#[serde(try_from = "PrefixedBytesAsHex<20_usize>", into = "PrefixedBytesAsHex<20_usize>")]
```

**Review by DvirYo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-api/97)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dan-starkware, @noaov1, and @yair-starkware)

___
*[`src/core.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/starknet-api/97#-NaHNTMs3_6q-6FaRZMR:-NaHSOtE1JPrspBpS8Kf:b-zjtoh) ([raw file](https://github.com/starkware-libs/starknet-api/blob/cfe90268abe0aa565fe7c9857bcefd9f33a8bf1e/src/core.rs#L222)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain how this line leading to the desired result (serialization without leading zeroes)?
</blockquote></details>

The "into = PrefixedBytesAsHex<20_usize>" means that to serialize this struct, first convert it to the type PrefixedBytesAsHex<20_usize> and then serialize it. Because the serialization of PrefixedBytesAsHex<20_usize> is without leading zeroes, we get the desired result.

**Pull request merged**
